const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),M=require('../frontend/chart-math.js');
test('WebSocket updates current/new candle without setData, rejects wrong symbols and old bars',async()=>{
 const elements=new Map(),el=id=>{if(!elements.has(id))elements.set(id,{textContent:'',checked:['ind-volume','ind-sma'].includes(id),value:id==='chart-period'?'6':'',addEventListener(){}});return elements.get(id);};let sets=0,updates=0;const series=()=>({setData(){sets++;},update(){updates++;},createPriceLine(){}});const scale={getVisibleLogicalRange:()=>null,setVisibleLogicalRange(){},fitContent(){}};const chart={addSeries:series,removeSeries(){},panes:()=>[{setHeight(){}}],applyOptions(){},subscribeCrosshairMove(){},timeScale:()=>scale};
 class WS{static OPEN=1;constructor(){this.readyState=1;}send(){}close(){}}
 const ctx={window:{LightweightCharts:{createChart:()=>chart,CrosshairMode:{Normal:0}},FinChartMath:M,addEventListener(){}},document:{currentScript:{src:'https://test/chart-engine.js',dataset:{}},getElementById:el,addEventListener(){}},location:{href:'https://test/'},URL,AbortController,AbortSignal,WebSocket:WS,Date,Map,Set,Math,Number,JSON,console,setTimeout:()=>1,clearTimeout(){},fetch:async url=>({ok:true,json:async()=>url.includes('config')?{websocketUrl:'wss://test/stream'}:{symbol:'MBB',unit:'VND',collectedAt:'2026-09-25T07:00:00Z',bars:[{time:'2026-09-24',open:20,high:22,low:19,close:21,volume:100}]}})};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../frontend/chart-engine.js'),'utf8'),ctx);const c=ctx.window.FinChart.create('https://test/',()=>{});await c.configPromise;c.symbol='MBB';await c.load();const initial=sets;
 const send=(time,symbol='MBB',volume=150)=>c.socket.onmessage({data:JSON.stringify({type:'candle',symbol,interval:'1d',unit:'VND',bar:{time,open:20,high:23,low:19,close:22,volume}})});
 send('2026-09-24');assert.equal(sets,initial);assert.ok(updates>0);assert.equal(c.bars.length,1);assert.equal(c.bars[0].volume,150);
 send('2026-09-25');assert.equal(c.bars.length,2);const count=updates;send('2026-09-23');send('2026-09-25','FPT');assert.equal(updates,count);assert.equal(sets,initial);assert.equal(c.bars[1].close,22);
});
