const $ = (id) => document.getElementById(id);
const fmt = new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 });
let currentRange = '5y';
let latestPayload = null;
let staticBenchmarks = null;
let staticSectors = null;
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const sd=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1));};
const pct=x=>`${(x*100).toFixed(2)}%`;
function returns(rows){const out=[];for(let i=1;i<rows.length;i++){const a=rows[i-1].close,b=rows[i].close;out.push(a>0&&b>0?Math.log(b/a):0)}return out}
function rollingVol(rows,w=20){return sd(returns(rows).slice(-w))*Math.sqrt(252)}
function drawdown(rows,w=60){const x=rows.slice(-w).map(r=>r.close).filter(v=>v>0);if(!x.length)return 0;const p=Math.max(...x),l=x.at(-1);return p?l/p-1:0}
function momentum(rows,w=20){const x=rows.slice(-(w+1));return x.length>=2?x.at(-1).close/x[0].close-1:0}
function percentileRank(v,h){const x=h.filter(Number.isFinite);return x.length?x.filter(a=>a<=v).length/x.length:.5}
function volPercentile(rows){if(rows.length<30)return .5;const vs=[];for(let i=21;i<=rows.length;i++)vs.push(rollingVol(rows.slice(0,i),20));return percentileRank(vs.at(-1),vs.slice(-252))}
function anomaly(rows){const r=returns(rows);if(r.length<21)return{z:0,score:0};const h=r.slice(-21,-1),last=r.at(-1),s=sd(h),m=mean(h),z=s?Math.abs((last-m)/s):0;return{z,score:clamp(z/4)}}
function riskForSlice(rows){const vol=rollingVol(rows),volP=volPercentile(rows),dd=drawdown(rows),mom=momentum(rows),an=anomaly(rows);const vp=clamp((volP-.35)/.65),dp=clamp(Math.abs(Math.min(dd,0))/.20),mp=clamp(Math.abs(Math.min(mom,0))/.15),ap=an.score;return{score:100*(.35*vp+.25*dp+.20*mp+.20*ap),vol,dd,mom,anomaly:an.z,drivers:{volPressure:vp,ddPressure:dp,momPressure:mp,anomalyPressure:ap}}}
function stateForScore(s){if(s>=65)return{label:'HIGH',cls:'danger',light:'high'};if(s>=35)return{label:'WATCH',cls:'warn',light:'medium'};return{label:'LOW',cls:'ok',light:'low'}}
function compactReason(r){const d=[];if(r.drivers.volPressure>.6)d.push('high volatility');if(r.drivers.ddPressure>.45)d.push('drawdown');if(r.drivers.momPressure>.45)d.push('negative momentum');if(r.drivers.anomalyPressure>.5)d.push('return anomaly');return d.length?d.join(', '):'normal conditions'}
function cleanRows(rows){const m=new Map();for(const q of rows||[]){const date=String(q.date||'').slice(0,10),close=Number(q.close);if(!date||!Number.isFinite(close)||close<=0)continue;m.set(date,{date,open:Number(q.open)||close,high:Number(q.high)||close,low:Number(q.low)||close,close,volume:Number(q.volume)||0})}return[...m.values()].sort((a,b)=>a.date.localeCompare(b.date))}
async function fetchFallback(){const r=await fetch('./data/fallback-market.json',{cache:'no-store'});if(!r.ok)throw new Error('Fallback unavailable');return r.json()}
async function fetchMarket(range=currentRange){try{const r=await fetch(`/api/market?range=${encodeURIComponent(range)}`,{cache:'no-store'});if(!r.ok)throw new Error(`API ${r.status}`);const p=await r.json(),rows=cleanRows(p.rows);if(rows.length<10)throw new Error('Too few rows');return{...p,rows,isFallback:false}}catch(e){console.warn(e);const fb=await fetchFallback();return{...fb,rows:cleanRows(fb.rows),isFallback:true}}}
function setupCanvas(c){const r=c.getBoundingClientRect(),d=Math.max(1,Math.min(2,devicePixelRatio||1)),w=Math.max(220,Math.floor(r.width||c.parentElement.clientWidth||600)),h=Math.max(120,Math.floor(r.height||c.parentElement.clientHeight||300));c.width=w*d;c.height=h*d;const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{ctx,w,h}}
function lineChart(c,pts,o={}){const{ctx,w,h}=setupCanvas(c);ctx.clearRect(0,0,w,h);if(!pts.length)return;const p={l:10,r:50,t:10,b:26},vals=pts.map(x=>x.y).filter(Number.isFinite);let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min--;max++}const e=(max-min)*.06;min-=e;max+=e;const X=i=>p.l+(w-p.l-p.r)*(i/Math.max(1,pts.length-1)),Y=v=>p.t+(h-p.t-p.b)*(1-(v-min)/(max-min));ctx.font='10px monospace';ctx.fillStyle='#6f879f';ctx.strokeStyle='#14283b';for(let i=0;i<4;i++){const y=p.t+(h-p.t-p.b)*i/3;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillText(fmt.format(max-(max-min)*i/3),w-p.r+7,y+3)}if(o.fill){const g=ctx.createLinearGradient(0,p.t,0,h-p.b);g.addColorStop(0,'rgba(71,215,255,.18)');g.addColorStop(1,'rgba(71,215,255,0)');ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(X(i),Y(q.y)):ctx.moveTo(X(i),Y(q.y)));ctx.lineTo(X(pts.length-1),h-p.b);ctx.lineTo(X(0),h-p.b);ctx.closePath();ctx.fillStyle=g;ctx.fill()}ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(X(i),Y(q.y)):ctx.moveTo(X(i),Y(q.y)));ctx.strokeStyle=o.color||'#47d7ff';ctx.lineWidth=1.7;ctx.stroke();if(o.stress)for(const s of o.stress){if(!s||s.i<0||s.i>=pts.length)continue;ctx.beginPath();ctx.arc(X(s.i),Y(pts[s.i].y),3.2,0,Math.PI*2);ctx.fillStyle='#ffca63';ctx.fill()}const ticks=Math.min(6,pts.length);ctx.fillStyle='#677f98';for(let t=0;t<ticks;t++){const i=Math.round((pts.length-1)*t/Math.max(1,ticks-1));ctx.fillText(pts[i].x,X(i)-25,h-7)}}
function miniLine(c,pts){const{ctx,w,h}=setupCanvas(c);ctx.clearRect(0,0,w,h);if(pts.length<2)return;const vals=pts.map(p=>p.y),min=Math.min(...vals),max=Math.max(...vals),rng=max-min||1,X=i=>w*i/(pts.length-1),Y=v=>8+(h-16)*(1-(v-min)/rng);ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(X(i),Y(p.y)):ctx.moveTo(X(i),Y(p.y)));ctx.strokeStyle='#47d7ff';ctx.lineWidth=1.5;ctx.stroke()}
function horizontalBars(c,items){const{ctx,w,h}=setupCanvas(c);ctx.clearRect(0,0,w,h);if(!items.length)return;const max=Math.max(...items.map(x=>x.value))*1.08,left=Math.min(160,w*.38),right=40,top=12,row=(h-24)/items.length;ctx.font='10px system-ui';items.forEach((it,i)=>{const y=top+i*row+row*.18,bh=row*.55,bw=(w-left-right)*(it.value/max);ctx.fillStyle='#8298ad';ctx.fillText(it.label,6,y+bh*.75);ctx.fillStyle=i===0?'rgba(255,202,99,.78)':'rgba(71,215,255,.58)';ctx.fillRect(left,y,bw,bh);ctx.fillStyle='#9bb1c5';ctx.fillText(`${it.value.toFixed(2)}%`,left+bw+7,y+bh*.75)})}
function sliceForDisplay(rows,r){if(r==='1y')return rows.slice(-260);if(r==='5y')return rows.slice(-1260);if(rows.length>2200){const step=Math.ceil(rows.length/1800);return rows.filter((_,i)=>i%step===0||i===rows.length-1)}return rows}
function renderMarketCharts(rows,r){const d=sliceForDisplay(rows,r),pts=d.map(x=>({x:x.date,y:x.close})),stress=[];const start=Math.max(25,d.length-400);for(let i=start;i<d.length;i++){if(i<d.length-90&&i%5!==0)continue;const rr=riskForSlice(d.slice(0,i+1));if(rr.score>=65)stress.push({i})}lineChart($('marketChart'),pts,{fill:true,stress});miniLine($('miniChart'),pts.slice(-80))}
function setDelta(el,c){el.textContent=`${c>=0?'+':''}${c.toFixed(2)}%`;el.classList.remove('pos','neg','neutral-text');el.classList.add(c>0?'pos':c<0?'neg':'neutral-text')}
function renderKPIs(p){const rows=p.rows,last=rows.at(-1),prev=rows.at(-2)||last,change=(last.close/prev.close-1)*100,r=riskForSlice(rows),s=stateForScore(r.score),price=fmt.format(last.close);$('heroPrice').textContent=price;$('kpiPrice').textContent=price;setDelta($('heroChange'),change);$('kpiChange').textContent=`${change>=0?'+':''}${change.toFixed(2)}%`;$('kpiChange').className=`chip ${change>=0?'ok':'danger'}`;$('heroRisk').textContent=r.score.toFixed(0);$('kpiRisk').textContent=r.score.toFixed(0);$('kpiRiskState').textContent=s.label;$('kpiRiskState').className=`chip ${s.cls}`;$('heroVol').textContent=pct(r.vol);$('kpiVol').textContent=pct(r.vol);$('heroDD').textContent=pct(r.dd);$('heroDate').textContent=last.date;$('kpiAnomaly').textContent=`${r.anomaly.toFixed(2)}σ`;$('gaugeValue').textContent=r.score.toFixed(0);$('riskState').textContent=`${s.label} RISK`;$('riskLight').className=`risk-light ${s.light}`;$('riskGauge').style.setProperty('--score',`${r.score*3.6}deg`);const vals=[r.drivers.volPressure,r.drivers.ddPressure,r.drivers.momPressure,r.drivers.anomalyPressure];[...$('driverList').querySelectorAll('b')].forEach((e,i)=>e.textContent=`${Math.round(vals[i]*100)}/100`);$('feedBadge').textContent=p.isFallback?'FALLBACK':'LIVE';$('feedBadge').className=`status-badge ${p.isFallback?'fallback':'live'}`;$('feedNote').textContent=p.isFallback?`Live feed unavailable. Showing fallback data through ${last.date}.`:`${p.source||'Market feed'} · latest session ${last.date}`;$('footerFreshness').textContent=`Data freshness: ${last.date} · ${p.isFallback?'fallback':'live adapter'}`}
function renderAlertRows(rows){const b=$('alertRows');b.innerHTML='';for(let i=rows.length-1;i>=Math.max(25,rows.length-8);i--){const r=riskForSlice(rows.slice(0,i+1)),s=stateForScore(r.score),prev=rows[i-1]||rows[i],ret=rows[i].close/prev.close-1,tr=document.createElement('tr');tr.innerHTML=`<td>${rows[i].date}</td><td>${fmt.format(rows[i].close)}</td><td class="${ret>=0?'pos':'neg'}">${ret>=0?'+':''}${pct(ret)}</td><td>${r.score.toFixed(0)}</td><td><span class="chip ${s.cls}">${s.label}</span></td><td>${compactReason(r)}</td>`;b.appendChild(tr)}}
async function renderStaticResearch(){const[b,s]=await Promise.all([fetch('./data/research-benchmarks.json').then(r=>r.json()),fetch('./data/sector-stats.json').then(r=>r.json())]);staticBenchmarks=b;staticSectors=s;$('aucBars').innerHTML=b.classifier_auc.map(x=>`<div class="bar-row"><span>${x.model}</span><div class="bar-track"><div class="bar-fill" style="width:${x.auc*100}%"></div></div><b>${x.auc.toFixed(3)}</b></div>`).join('');lineChart($('stressChart'),b.stress_test.map(x=>({x:`${x.days_ahead}d`,y:x.accuracy*100})),{fill:true});const sorted=[...s].sort((a,b)=>b.stdev-a.stdev);horizontalBars($('sectorChart'),sorted.map(x=>({label:x.sector,value:x.stdev*100})));$('sectorRows').innerHTML=s.map(x=>`<tr><td>${x.sector}</td><td>${x.mean.toFixed(6)}</td><td>${x.stdev.toFixed(6)}</td><td>${x.skewness.toFixed(6)}</td></tr>`).join('')}
async function loadMarket(r=currentRange,n=false){if(n)toast('Refreshing market data…');const p=await fetchMarket(r);latestPayload=p;renderKPIs(p);renderMarketCharts(p.rows,r);renderAlertRows(p.rows);if(n)toast(p.isFallback?'Live source unavailable — fallback loaded.':'Market data refreshed.')}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2200)}
function redraw(){if(latestPayload)renderMarketCharts(latestPayload.rows,currentRange);if(staticBenchmarks)lineChart($('stressChart'),staticBenchmarks.stress_test.map(x=>({x:`${x.days_ahead}d`,y:x.accuracy*100})),{fill:true});if(staticSectors){const s=[...staticSectors].sort((a,b)=>b.stdev-a.stdev);horizontalBars($('sectorChart'),s.map(x=>({label:x.sector,value:x.stdev*100})))}}
document.addEventListener('DOMContentLoaded',async()=>{try{await renderStaticResearch()}catch(e){console.error(e)}try{await loadMarket()}catch(e){console.error(e);$('feedBadge').textContent='ERROR';$('feedNote').textContent='Market data could not be loaded.'}document.querySelectorAll('.range-btn').forEach(btn=>btn.addEventListener('click',async()=>{document.querySelectorAll('.range-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentRange=btn.dataset.range;await loadMarket(currentRange,true)}));$('refreshBtn').addEventListener('click',()=>loadMarket(currentRange,true));let timer;addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(redraw,120)})});