const $=id=>document.getElementById(id);let DATA=null;let quoteTimer=null;
const fmt=new Intl.NumberFormat('en-US',{maximumFractionDigits:2});const pct=(x,d=2)=>`${(x*100).toFixed(d)}%`;const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const INFO={
liveQuote:{title:'Live VN-Index quote',body:'The live quote is requested from Vnstock Community using the KBS-backed index quote endpoint. The full EWS model is recalculated from completed daily bars, while the quote is refreshed every 60 seconds so intraday price movement does not masquerade as a fully retrained daily model.'},
riskScore:{title:'Composite EWS score',body:'The operational score ranges from 0 to 100 and combines six transparent pressures: 25% volatility regime, 20% 60-day drawdown, 15% 20-day negative momentum, 15% distance below the 50-day moving average, 15% negative return shock, and 10% volume-confirmed stress. Each driver is normalized to recent history. This is an independently implemented live EWS, not the original ANFIS/VAE output from the thesis.'},
horizons:{title:'Forward warning horizons',body:'For 5, 20 and 60 trading-day horizons, the system finds the 40 closest historical market states in a standardized feature space. It then measures how often those analog states were followed by a tail drawdown at or below the historical 5th percentile for that horizon. This historical analog stress rate is empirical evidence, not a guaranteed probability.'},
crashTrigger:{title:'3.09σ crash diagnostic',body:'The thesis selects a CRASH-style criterion based on returns falling 3.09 standard deviations below the mean. VMEWS shows a thesis-aligned 5-session log-return diagnostic as a realized tail-event check. It is deliberately kept separate from the predictive EWS score because a realized crash trigger is not itself an early warning.'},
alerts:{title:'Active alerts',body:'An alert appears when a normalized risk pressure crosses an operational threshold. Alerts explain the exact driver rather than only showing a red/green state. This gives a reviewer a traceable reason for escalation and reduces the risk of acting on an opaque score.'},
playbook:{title:'Risk playbook',body:'The playbook converts the warning state into risk-management review actions: concentration checks, stress testing, limit review, liquidity review and escalation. These are governance prompts, not buy/sell instructions.'},
historyChart:{title:'Historical training window',body:'Vnstock Community documents a maximum of 8 years of daily OHLCV history. VMEWS requests that full available window on every model refresh. The exact start and end dates, observation count and data-quality checks are displayed so the user can verify what data actually ran the model.'},
scoreHistory:{title:'EWS score history',body:'Historical scores are recomputed from information available up to each date. The chart makes regime shifts visible and helps reviewers distinguish a one-day spike from sustained warning conditions.'},
analogs:{title:'Historical analogs',body:'Analogs are the nearest past observations based on volatility, drawdown, momentum, trend gap, return shock and volume stress. Future outcomes are shown only for those past analog dates. Recent observations are excluded from the analog pool until enough forward days exist, avoiding accidental look-ahead.'},
dataQuality:{title:'Data quality controls',body:'The API checks observation count, start/end coverage, stale calendar days, invalid rows, duplicate dates and unusually large gaps. A model output should not be trusted before its input data passes basic completeness, uniqueness, validity and timeliness controls.'},
holdout:{title:'Chronological holdout validation',body:'After feature warm-up, the first 70% of observations calibrate the alert threshold and the 20-day tail-drawdown target. The final 30% is evaluated as unseen chronological data. Precision, recall, F1, accuracy, ROC AUC and lift are computed only on that holdout segment.'},
modelCard:{title:'Operational model card',body:'The live model is a transparent risk ensemble designed for auditability. It does not claim to reproduce the unavailable original ANFIS/VAE weights. The source, feature definitions, target, validation split, refresh logic and limitations are made explicit.'},
calibration:{title:'Risk bucket calibration',body:'Holdout observations are grouped by the rank of the EWS score relative to the training sample. The chart shows the realized 20-day tail-event rate in each score bucket. A useful warning system should exhibit materially higher event frequency in higher-risk buckets.'},
stressLab:{title:'What-if Stress Lab',body:'Stress Lab applies hypothetical shocks to the current risk pressures. It is a sensitivity tool, not a forecast. The purpose is to answer: if the market fell sharply, volatility rose and trading volume became stressed, how would the warning state respond?'},
};
function infoHtml(text){return `<p>${text}</p><p><b>Interpretation rule:</b> use this metric with the other diagnostics, confirm data freshness, and review the model card before escalation.</p>`}
function openInfo(key){const x=INFO[key];if(!x)return;$('modalTitle').textContent=x.title;$('modalBody').innerHTML=infoHtml(x.body);$('infoModal').classList.add('open');$('infoModal').setAttribute('aria-hidden','false')}
function closeInfo(){$('infoModal').classList.remove('open');$('infoModal').setAttribute('aria-hidden','true')}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2300)}
function stateClass(s){return String(s||'LOW').toLowerCase()}
function setLive(ok,text){$('liveDot').className=`live-dot ${ok?'ok':'warn'}`;$('liveText').textContent=text}
function setupCanvas(c){const rect=c.getBoundingClientRect(),d=Math.max(1,Math.min(2,devicePixelRatio||1)),w=Math.max(260,Math.floor(rect.width||c.parentElement.clientWidth||600)),h=Number(c.getAttribute('height'))||300;c.width=w*d;c.height=h*d;const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{ctx,w,h}}
function lineChart(c,points,opt={}){const{ctx,w,h}=setupCanvas(c);ctx.clearRect(0,0,w,h);if(!points||points.length<2)return;const p={l:12,r:48,t:14,b:26},vals=points.map(x=>x.y).filter(Number.isFinite);let min=Math.min(...vals),max=Math.max(...vals);if(opt.min!=null)min=opt.min;if(opt.max!=null)max=opt.max;if(min===max){min--;max++}const extra=opt.fixed?0:(max-min)*.05;min-=extra;max+=extra;const X=i=>p.l+(w-p.l-p.r)*i/Math.max(1,points.length-1),Y=v=>p.t+(h-p.t-p.b)*(1-(v-min)/(max-min));ctx.font='9px ui-monospace,monospace';ctx.strokeStyle='#162b3d';ctx.fillStyle='#6e879d';for(let i=0;i<4;i++){const yy=p.t+(h-p.t-p.b)*i/3;ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke();ctx.fillText(fmt.format(max-(max-min)*i/3),w-p.r+6,yy+3)}if(opt.fill){const g=ctx.createLinearGradient(0,p.t,0,h-p.b);g.addColorStop(0,'rgba(75,220,255,.16)');g.addColorStop(1,'rgba(75,220,255,0)');ctx.beginPath();points.forEach((q,i)=>i?ctx.lineTo(X(i),Y(q.y)):ctx.moveTo(X(i),Y(q.y)));ctx.lineTo(X(points.length-1),h-p.b);ctx.lineTo(X(0),h-p.b);ctx.closePath();ctx.fillStyle=g;ctx.fill()}ctx.beginPath();points.forEach((q,i)=>i?ctx.lineTo(X(i),Y(q.y)):ctx.moveTo(X(i),Y(q.y)));ctx.strokeStyle=opt.color||'#4bdcff';ctx.lineWidth=1.6;ctx.stroke();if(opt.zones){for(const z of opt.zones){const y=Y(z.v);ctx.strokeStyle=z.color;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.setLineDash([])}}const ticks=Math.min(6,points.length);ctx.fillStyle='#657f96';for(let t=0;t<ticks;t++){const i=Math.round((points.length-1)*t/Math.max(1,ticks-1));ctx.fillText(points[i].x.slice(0,10),Math.max(0,X(i)-25),h-7)}}
function spark(c,rows){const pts=rows.slice(-100).map(r=>({x:r.date,y:r.close}));lineChart(c,pts,{fill:true})}
function renderQuote(q,rows){const last=rows.at(-1),prev=rows.at(-2)||last,price=q?.last||last.close;let ch=q?.percentChange;if(ch==null&&q?.change!=null&&price-q.change!==0)ch=q.change/(price-q.change)*100;if(ch==null)ch=(last.close/prev.close-1)*100;$('livePrice').textContent=fmt.format(price);$('lastClose').textContent=fmt.format(last.close);$('liveChange').textContent=`${ch>=0?'+':''}${ch.toFixed(2)}%`;$('liveChange').className=`delta ${ch>=0?'pos':'neg'}`}
function renderHeader(d){const q=d.dataQuality;$('coverageText').textContent=`${q.start} → ${q.end}`;$('rowsText').textContent=fmt.format(q.rows);$('modelAsOf').textContent=q.end;$('modelVersion').textContent=d.version;$('trainWindow').textContent=`${q.start} → ${q.end} (${fmt.format(q.rows)} daily bars)`;$('dataQualityBadge').textContent=q.status==='PASS'?'DATA PASS':'DATA REVIEW';$('dataQualityBadge').style.color=q.status==='PASS'?'#49e0a2':'#ffc766';$('sourceLine').textContent=`${d.source} · ${d.provider} · model closes through ${q.end}`;$('footerStatus').textContent=`Data status: ${q.status} · ${q.end}`;setLive(true,'Vnstock live');renderQuote(d.quote,d.rows);spark($('sparkChart'),d.rows)}
function renderRisk(d){const r=d.risk,c=d.current,s=stateClass(r.state);$('riskScore').textContent=r.score.toFixed(0);$('heroRisk').textContent=r.score.toFixed(0);$('heroState').textContent=r.state;$('riskState').textContent=`${r.state} RISK`;$('stateLight').className=`state-light ${s}`;$('riskRing').style.setProperty('--score',`${r.score*3.6}deg`);$('riskNarrative').textContent=r.narrative;$('horizonGrid').innerHTML=r.horizons.map(h=>`<div class="horizon-box"><div class="hz-top"><small>${h.days} TRADING DAYS</small><span class="chip ${stateClass(h.state)}">${h.state}</span></div><strong>${h.score.toFixed(0)}</strong><div class="hz-rate">Analog stress rate: ${(h.analogStressRate*100).toFixed(1)}%</div><div class="hz-desc">Tail threshold ${pct(h.tailThreshold)} · ${h.analogs} nearest states</div></div>`).join('');const cr=d.crashDiagnostic||{};$('weeklyReturn').textContent=cr.currentReturn==null?'—':pct(cr.currentReturn);$('crashThreshold').textContent=cr.threshold==null?'—':pct(cr.threshold);$('sigmaDistance').textContent=cr.sigmaDistance==null?'—':`${cr.sigmaDistance.toFixed(2)}σ`;$('crashTriggerStatus').textContent=cr.triggered?'TRIGGERED — realized tail-return threshold breached':'NOT TRIGGERED — current 5-session return remains above the 3.09σ threshold';$('crashTriggerStatus').className=`status-box ${cr.triggered?'alert':''}`;renderAlerts(r.alerts);renderPlaybook(r.playbook);renderDrivers(c)}
function renderAlerts(items){$('alertsList').innerHTML=(items||[]).map(a=>`<div class="alert-item"><span class="sev ${a.severity==='HIGH'?'high':a.severity==='WATCH'?'warn':''}">${a.severity}</span><div><b>${a.title}</b><p>${a.description}</p></div><span class="value">${a.pressure!=null?Math.round(a.pressure*100):0}/100</span></div>`).join('')}
function renderPlaybook(items){$('playbook').innerHTML=(items||[]).map((x,i)=>`<div class="play-step"><span>0${i+1}</span><div><b>${x}</b><p>${i===0?'Immediate review priority based on the current warning state.':'Use under the applicable portfolio mandate and governance process.'}</p></div></div>`).join('')}
function renderDrivers(c){const labels={volatility:['Volatility regime',pct(c.vol20)],drawdown:['60D drawdown',pct(c.dd60)],momentum:['20D momentum',pct(c.mom20)],trend:['50D trend gap',pct(c.trendGap)],shock:['Negative shock z',`${c.shockZ.toFixed(2)}σ`],volume:['Volume stress z',`${c.volumeZ.toFixed(2)}σ`]};$('driverGrid').innerHTML=Object.entries(c.pressures).map(([k,v])=>`<div class="driver-card"><div class="driver-top"><span>${labels[k][0]}</span><button class="info-btn" data-info="riskScore">i</button></div><strong>${labels[k][1]}</strong><p>Pressure ${Math.round(v*100)}/100 · contribution ${c.contributions[k].toFixed(1)} points</p><div class="bar"><i style="width:${Math.round(v*100)}%"></i></div></div>`).join('')}
function renderCharts(d){let rows=d.rows,step=Math.max(1,Math.ceil(rows.length/1500));let p=rows.filter((_,i)=>i%step===0||i===rows.length-1).map(r=>({x:r.date,y:r.close}));lineChart($('priceChart'),p,{fill:true});let s=d.scoreHistory,st=Math.max(1,Math.ceil(s.length/1200)),sp=s.filter((_,i)=>i%st===0||i===s.length-1).map(r=>({x:r.date,y:r.score}));lineChart($('scoreChart'),sp,{min:0,max:100,fixed:true,zones:[{v:32,color:'#ffc766'},{v:55,color:'#ff8f74'},{v:75,color:'#ff5f78'}]})}
function renderAnalogs(d){$('analogRows').innerHTML=(d.analogs||[]).map(a=>`<tr><td>${a.date}</td><td>${(a.similarity*100).toFixed(1)}%</td><td class="${a.forwardReturn20>=0?'pos':'neg'}">${pct(a.forwardReturn20)}</td><td class="${a.maxDrawdown20<0?'neg':''}">${pct(a.maxDrawdown20)}</td><td><span class="chip ${a.stress?'high':'low'}">${a.stress?'TAIL STRESS':'NORMAL'}</span></td></tr>`).join('');const q=d.dataQuality;const boxes=[['Rows',fmt.format(q.rows),q.rows>=1000],['Coverage start',q.start,true],['Latest daily bar',q.end,q.staleCalendarDays<=4],['Stale calendar days',String(q.staleCalendarDays),q.staleCalendarDays<=4],['Duplicates removed',String(q.duplicatesRemoved),true],['Invalid rows removed',String(q.invalidRemoved),q.invalidRemoved===0],['Large gaps >12d',String(q.largeGaps),q.largeGaps<=1],['Overall',q.status,q.status==='PASS']];$('qualityGrid').innerHTML=boxes.map(x=>`<div class="quality-box ${x[2]?'ok':'warn'}"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
function val(x){return x==null?'—':x.toFixed(3)}
function renderModel(d){const b=d.backtest||{};const metrics=[['ROC AUC',b.auc==null?'—':b.auc.toFixed(3),'ranking discrimination'],['Precision',b.precision==null?'—':pct(b.precision,1),'alerts that became tail events'],['Recall',b.recall==null?'—':pct(b.recall,1),'tail events captured'],['F1 score',b.f1==null?'—':b.f1.toFixed(3),'precision/recall balance'],['Alert lift',b.lift==null?'—':`${b.lift.toFixed(2)}×`,'event rate vs base rate']];$('backtestMetrics').innerHTML=metrics.map(m=>`<div class="metric-card"><small>${m[0]}</small><strong>${m[1]}</strong><span>${m[2]}</span></div>`).join('');$('holdoutDetails').innerHTML=`<div><span>Calibration observations</span><b>${fmt.format(b.trainN||0)}</b></div><div><span>Holdout observations</span><b>${fmt.format(b.testN||0)}</b></div><div><span>Holdout starts</span><b>${b.splitDate||'—'}</b></div><div><span>20D tail target</span><b>${b.stressThreshold20==null?'—':pct(b.stressThreshold20)}</b></div><div><span>Alert threshold</span><b>${b.alertThreshold==null?'—':b.alertThreshold.toFixed(1)+'/100'}</b></div><div><span>Holdout base event rate</span><b>${b.baseRate==null?'—':pct(b.baseRate,1)}</b></div>`;const cal=b.calibration||[];$('calibrationBars').innerHTML=cal.map((x,i)=>`<div class="cal-row"><span>${x.bucket} score rank</span><div class="cal-track"><i style="width:${Math.min(100,x.eventRate*400)}%"></i></div><b>${(x.eventRate*100).toFixed(1)}% · n=${x.n}</b></div>`).join('')}
function renderStress(){if(!DATA)return;const c=DATA.current,base=DATA.risk.score,ret=+$('shockReturn').value/100,vm=+$('volMultiplier').value,vz=+$('volumeShock').value;$('shockReturnLabel').textContent=`${(ret*100).toFixed(1)}%`;$('volMultiplierLabel').textContent=`${vm.toFixed(2)}×`;$('volumeShockLabel').textContent=`${vz.toFixed(1)}σ`;const p={...c.pressures};p.shock=clamp(Math.max(p.shock,Math.max(0,-ret)/.08));p.volatility=clamp(p.volatility+(vm-1)*.35);p.momentum=clamp(p.momentum+Math.max(0,-ret)/.12*.45);p.drawdown=clamp(p.drawdown+Math.max(0,-ret)/.18*.60);p.trend=clamp(p.trend+Math.max(0,-ret)/.10*.35);p.volume=clamp(Math.max(p.volume,Math.max(0,vz)/3*clamp(Math.max(0,-ret)/.04)));const score=25*p.volatility+20*p.drawdown+15*p.momentum+15*p.trend+15*p.shock+10*p.volume;const st=score>=75?'CRITICAL':score>=55?'HIGH':score>=32?'WATCH':'LOW';$('stressScore').textContent=score.toFixed(0);$('stressState').textContent=st;$('stressState').className=`chip ${stateClass(st)}`;$('stressDelta').textContent=`${score-base>=0?'+':''}${(score-base).toFixed(1)} points versus current EWS`;$('stressExplanation').innerHTML=[`Shock return contributes ${(p.shock*15).toFixed(1)} risk points.`,`Volatility pressure rises to ${Math.round(p.volatility*100)}/100.`,`Projected state moves from ${DATA.risk.state} to ${st}.`].map(x=>`<div>${x}</div>`).join('')}
function exportSnapshot(){if(!DATA)return;const slim={exportedAt:new Date().toISOString(),version:DATA.version,symbol:DATA.symbol,source:DATA.source,dataQuality:DATA.dataQuality,quote:DATA.quote,current:DATA.current,risk:DATA.risk,crashDiagnostic:DATA.crashDiagnostic,backtest:DATA.backtest,analogs:DATA.analogs,research:DATA.research};const blob=new Blob([JSON.stringify(slim,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`VMEWS_${DATA.dataQuality.end}_risk_snapshot.json`;a.click();URL.revokeObjectURL(a.href);toast('Risk snapshot exported')}
async function loadFull(notify=false){if(notify)toast('Refreshing full Vnstock history and EWS…');setLive(false,'Loading model');try{const r=await fetch(`/api/ews?t=${Date.now()}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.message||`API ${r.status}`);DATA=d;renderHeader(d);renderRisk(d);renderCharts(d);renderAnalogs(d);renderModel(d);renderStress();if(notify)toast(`Updated through ${d.dataQuality.end}`)}catch(e){console.error(e);setLive(false,'Data pipeline error');$('dataQualityBadge').textContent='PIPELINE ERROR';$('dataQualityBadge').style.color='#ff6e7f';$('riskNarrative').textContent=`Data pipeline error: ${e.message}. The dashboard intentionally does not fabricate live model values when the source fails.`;toast('Vnstock pipeline error — see warning console')}}
async function refreshQuote(){if(!DATA)return;try{const r=await fetch(`/api/ews?mode=quote&t=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const q=await r.json();DATA.quote=q.quote;renderQuote(q.quote,DATA.rows);setLive(true,'Vnstock live')}catch(e){console.warn('quote refresh',e)}}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('[data-info]');if(b)openInfo(b.dataset.info);if(e.target.closest('[data-close-modal]'))closeInfo()});$('refreshBtn').addEventListener('click',()=>loadFull(true));$('exportBtn').addEventListener('click',exportSnapshot);['shockReturn','volMultiplier','volumeShock'].forEach(id=>$(id).addEventListener('input',renderStress));$('resetStress').addEventListener('click',()=>{$('shockReturn').value=-3;$('volMultiplier').value=1.25;$('volumeShock').value=1;renderStress()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeInfo()});let rt;addEventListener('resize',()=>{clearTimeout(rt);rt=setTimeout(()=>{if(DATA){renderCharts(DATA);spark($('sparkChart'),DATA.rows)}},150)})}
document.addEventListener('DOMContentLoaded',async()=>{bind();await loadFull();quoteTimer=setInterval(refreshQuote,60000)});