(()=>{'use strict';
const API='https://vmews-risk-analytics-sojd.vercel.app/api/radar';
const CDN='https://cdn.githubraw.com/NCKHtop1/vmews-risk-analytics/main/data';
const $=s=>document.querySelector(s), pct=(x,d=2)=>Number.isFinite(+x)?`${(+x*100).toFixed(d)}%`:'—', money=x=>Number.isFinite(+x)?Math.round(+x).toLocaleString('en-US'):'—';
async function getJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`${r.status}`);return r.json()}
async function loadSymbol(sym){sym=String(sym||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8);if(!sym)throw Error('Enter a valid ticker.');let errors=[];try{return await getJSON(`${API}?mode=detail&symbol=${encodeURIComponent(sym)}`)}catch(e){errors.push('live API '+e.message)}for(const dir of ['deep-alerts','hose-fallbacks']){try{return await getJSON(`${CDN}/${dir}/${sym}.json?t=${Date.now()}`)}catch(e){errors.push(dir+' '+e.message)}}throw Error(`${sym}: price history unavailable (${errors.join(' · ')})`)}
function riskOf(d){if(Number.isFinite(+d?.current?.technical))return +d.current.technical;if(Number.isFinite(+d?.score))return +d.score;return 50}
function riskBand(x){return x>=78?'RED':x>=65?'YELLOW':x>=50?'WATCH':'GREEN'}
function draw(rows,res){const cv=$('#chart'),dpr=window.devicePixelRatio||1,rect=cv.getBoundingClientRect();cv.width=Math.max(300,rect.width*dpr);cv.height=Math.max(250,rect.height*dpr);const c=cv.getContext('2d');c.scale(dpr,dpr);const W=rect.width,H=rect.height,pad={l:56,r:25,t:22,b:38},hist=rows.slice(-75),last=+hist.at(-1).close,fc=[];for(let h=1;h<=5;h++){const x=res.horizons[h];if(x?.available)fc.push({h,price:last*Math.exp(x.forecast),low:last*Math.exp(x.low),high:last*Math.exp(x.high),pass:x.pass})}const vals=hist.map(r=>+r.close).concat(fc.flatMap(x=>[x.low,x.high,x.price])),mn=Math.min(...vals),mx=Math.max(...vals),rng=(mx-mn)||1,xHist=i=>pad.l+i*(W-pad.l-pad.r)*.78/(hist.length-1),xFc=h=>pad.l+(W-pad.l-pad.r)*(.78+.22*h/5),y=v=>pad.t+(mx-v)/rng*(H-pad.t-pad.b);c.clearRect(0,0,W,H);c.strokeStyle='#132a38';c.lineWidth=1;for(let i=0;i<5;i++){const yy=pad.t+i*(H-pad.t-pad.b)/4;c.beginPath();c.moveTo(pad.l,yy);c.lineTo(W-pad.r,yy);c.stroke();c.fillStyle='#718592';c.font='10px Arial';c.fillText(Math.round(mx-i*rng/4).toLocaleString(),4,yy+3)}c.strokeStyle='#dce7ed';c.lineWidth=1.7;c.beginPath();hist.forEach((r,i)=>{const xx=xHist(i),yy=y(+r.close);i?c.lineTo(xx,yy):c.moveTo(xx,yy)});c.stroke();const x0=xHist(hist.length-1),y0=y(last);c.strokeStyle='#e7b14f';c.lineWidth=2;c.setLineDash([6,5]);c.beginPath();c.moveTo(x0,y0);fc.forEach(z=>c.lineTo(xFc(z.h),y(z.price)));c.stroke();c.setLineDash([]);if(fc.length){c.fillStyle='rgba(102,200,207,.12)';c.beginPath();c.moveTo(x0,y0);fc.forEach(z=>c.lineTo(xFc(z.h),y(z.high)));for(let i=fc.length-1;i>=0;i--)c.lineTo(xFc(fc[i].h),y(fc[i].low));c.closePath();c.fill()}fc.forEach(z=>{c.fillStyle=z.pass?'#e7b14f':'#6c7b84';c.beginPath();c.arc(xFc(z.h),y(z.price),3.5,0,Math.PI*2);c.fill();c.fillStyle='#9fb0bb';c.font='10px Arial';c.fillText(`T+${z.h}`,xFc(z.h)-10,H-15)});c.fillStyle='#9fb0bb';c.font='10px Arial';c.fillText('Completed EOD',pad.l,H-15);c.fillText('AI forecast',W-pad.r-62,pad.t+12)}
function render(d,res){window.__lastRender={d,res};const risk=riskOf(d),rec=VMEWSForecastCore.recommendation(res,risk),last=+res.last.close,passed=[3,4,5].filter(h=>res.horizons[h]?.pass).length;$('#symbolTitle').textContent=`${d.symbol||''} · 3–5 session outlook`;$('#asof').textContent=`EOD ${res.last.date||d.modelAsOf||'—'}`;$('#stance').textContent=rec.label;$('#stance').className=`stance ${rec.tone}`;$('#aiText').textContent=rec.text;$('#confidence').textContent=rec.confidence;$('#validated').textContent=`${passed}/3 horizons`;$('#lastClose').textContent=money(last);$('#risk').textContent=`${Math.round(risk)}/100`;$('#riskBand').textContent=riskBand(risk);$('#historyN').textContent=res.rows.toLocaleString();$('#source').textContent=d?.source?.price||d?.provider||d?.source||'Completed EOD price history';$('#modelUse').textContent=passed?'Validated edge available':'No validated edge';$('#recommendationWhy').textContent=rec.text+' '+(passed?'The recommendation uses only horizons that passed the locked out-of-sample gate.':'Forecasts are displayed for transparency, but the AI withholds a directional stance when the evidence gate fails.');for(const h of [3,4,5]){const x=res.horizons[h],el=$(`#h${h}`);if(!x?.available){el.innerHTML=`<span>T+${h}</span><b>Unavailable</b><small>${x?.reason||'Insufficient history'}</small>`;continue}const pr=last*Math.exp(x.forecast),cls=x.forecast>0?'positive':x.forecast<0?'negative':'';el.innerHTML=`<span>T+${h} forecast</span><b class="${cls}">${pct(x.forecast)}</b><small>${money(pr)} · 80% range ${money(last*Math.exp(x.low))}–${money(last*Math.exp(x.high))} · ${x.pass?'validated':'withheld'}</small>`}draw(d.history||[],res)}
async function run(sym){$('#app').classList.add('loading');$('#error').classList.add('hidden');try{const d=await loadSymbol(sym),rows=d.history||[];if(rows.length<500)throw Error(`${sym}: only ${rows.length} completed sessions; at least 500 are required.`);const res=VMEWSForecastCore.run(rows);if(!res.ok)throw Error(res.reason);render(d,res);history.replaceState(null,'',`?symbol=${encodeURIComponent(sym)}`)}catch(e){$('#error').textContent=e.message||String(e);$('#error').classList.remove('hidden')}finally{$('#app').classList.remove('loading')}}
$('#go').addEventListener('click',()=>run($('#symbol').value));$('#symbol').addEventListener('keydown',e=>{if(e.key==='Enter')run($('#symbol').value)});window.addEventListener('resize',()=>{if(window.__lastRender)draw(window.__lastRender.d.history,window.__lastRender.res)});const q=new URLSearchParams(location.search).get('symbol')||'PNJ';$('#symbol').value=q;run(q);
})();
