(()=>{'use strict';
const GH='https://cdn.githubraw.com/NCKHtop1/vmews-risk-analytics/main',API='https://vmews-risk-analytics-sojd.vercel.app/api',q=s=>document.querySelector(s),pct=(x,d=1)=>Number.isFinite(+x)?`${(+x*100).toFixed(d)}%`:'—',num=x=>Number.isFinite(+x)?Math.round(+x).toLocaleString('vi-VN'):'—';let modelP,newsP,lastView;
async function js(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`${r.status}`);return r.json()}
const model=()=>modelP||(modelP=js(`${GH}/data/forecast-model-v4.json?t=${Date.now()}`).catch(()=>js('./data/forecast-model-v4.json'))),allNews=()=>newsP||(newsP=js(`${GH}/data/research-news.json?t=${Date.now()}`).catch(()=>({symbols:{}})));
async function detail(s){s=String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8);if(!s)throw Error('Mã cổ phiếu không hợp lệ.');const urls=[`${API}/radar?mode=detail&symbol=${s}`,`${API}/stocks?mode=detail&symbol=${s}`,`${GH}/data/deep-alerts/${s}.json?t=${Date.now()}`,`${GH}/data/hose-fallbacks/${s}.json?t=${Date.now()}`];let err=[];for(const u of urls)try{const d=await js(u);if((d.history||[]).length>=520)return d;err.push('thiếu lịch sử')}catch(e){err.push(e.message)}throw Error(`${s}: chưa lấy được tối thiểu 520 phiên dữ liệu.`)}
async function newsFor(s,d){if(d.news?.length)return d.news;try{return (await allNews()).symbols?.[s]||[]}catch{return[]}}
function toneScore(x){return !Number.isFinite(+x)?['CHƯA CÓ','']:x<40?['TÍCH CỰC','positive']:x>65?['TIÊU CỰC','negative']:['TRUNG TÍNH','neutral']}
function riskBand(x){return x>=78?'RED':x>=65?'YELLOW':x>=50?'WATCH':'GREEN'}
function draw(rows,fc){const cv=q('#chart'),r=cv.getBoundingClientRect(),dpr=window.devicePixelRatio||1;cv.width=Math.max(300,r.width*dpr);cv.height=Math.max(280,r.height*dpr);const c=cv.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);const W=r.width,H=r.height,p={l:58,r:24,t:20,b:34},hist=rows.slice(-90),last=+hist.at(-1).close,F=[1,2,3,4,5].map(h=>fc[h]).filter(Boolean).map(z=>({h,price:last*Math.exp(z.value),lo:last*Math.exp(z.low),hi:last*Math.exp(z.high),status:z.status})),vals=hist.map(x=>+x.close).concat(F.flatMap(x=>[x.lo,x.hi,x.price])),mn=Math.min(...vals),mx=Math.max(...vals),rg=mx-mn||1,xh=i=>p.l+i*(W-p.l-p.r)*.79/(hist.length-1),xf=h=>p.l+(W-p.l-p.r)*(.79+.21*h/5),y=v=>p.t+(mx-v)/rg*(H-p.t-p.b);c.clearRect(0,0,W,H);c.strokeStyle='#152a38';c.lineWidth=1;for(let i=0;i<5;i++){const yy=p.t+i*(H-p.t-p.b)/4;c.beginPath();c.moveTo(p.l,yy);c.lineTo(W-p.r,yy);c.stroke();c.fillStyle='#718592';c.font='10px Arial';c.fillText(num(mx-i*rg/4),4,yy+3)}c.strokeStyle='#dce7ed';c.lineWidth=1.6;c.beginPath();hist.forEach((z,i)=>i?c.lineTo(xh(i),y(+z.close)):c.moveTo(xh(i),y(+z.close)));c.stroke();if(F.length){c.fillStyle='rgba(92,198,207,.11)';c.beginPath();c.moveTo(xh(hist.length-1),y(last));F.forEach(z=>c.lineTo(xf(z.h),y(z.hi)));for(let i=F.length-1;i>=0;i--)c.lineTo(xf(F[i].h),y(F[i].lo));c.closePath();c.fill();c.strokeStyle='#e6ad45';c.lineWidth=2;c.setLineDash([6,5]);c.beginPath();c.moveTo(xh(hist.length-1),y(last));F.forEach(z=>c.lineTo(xf(z.h),y(z.price)));c.stroke();c.setLineDash([]);F.forEach(z=>{c.fillStyle=z.status==='PASS'?'#e6ad45':'#697985';c.beginPath();c.arc(xf(z.h),y(z.price),3.5,0,Math.PI*2);c.fill();c.fillStyle='#91a3af';c.font='10px Arial';c.fillText(`T+${z.h}`,xf(z.h)-10,H-12)})}}
function factor(d,k){return d?.modules?.macro?.factors?.[k]}
function renderNews(a){const box=q('#news');if(!a.length){box.innerHTML='<div class="muted">Chưa có tin phù hợp trong dữ liệu hiện tại.</div>';return}box.innerHTML=a.slice(0,4).map(x=>`<a href="${x.link||'#'}" target="_blank" rel="noopener">${String(x.title||'').replace(/</g,'&lt;')}<small>${x.publisher||x.published||''}</small></a>`).join('')}
function renderBT(m){q('#bt').innerHTML=[3,4,5].map(h=>{const z=m.horizons?.[h],a=z?.sealed||{};return `<tr><td>T+${h}</td><td>${Number.isFinite(+a.r2)?(+a.r2).toFixed(3):'—'}</td><td>${pct(a.balancedDirection)}</td><td>${Number.isFinite(+a.csIC)?(+a.csIC).toFixed(3):'—'}</td><td>${pct(a.csSpread)}</td><td class="${z?.status==='PASS'?'positive':'neutral'}">${z?.status==='PASS'?'ĐẠT':'CHƯA ĐẠT'}</td></tr>`}).join('')}
function fcCard(h,z,last){const pr=last*Math.exp(z.value),lo=last*Math.exp(z.low),hi=last*Math.exp(z.high),cls=z.value>=0?'positive':'negative';q(`#h${h}`).innerHTML=`<span>T+${h}</span><b class="${cls}">${z.value>=0?'+':''}${pct(z.value)}</b><small>${num(pr)} · khoảng ${num(lo)}–${num(hi)}</small>`}
function fundamentals(d){const z=d?.modules?.fundamental,m=z?.metrics||d?.fundamentals||{};if(z?.available===false&&!Object.keys(m).length)return['CHƯA CÓ','Dữ liệu cơ bản hiện không khả dụng.'];const parts=[];if(Number.isFinite(+m.roe))parts.push(`ROE ${(+m.roe).toFixed(1)}`);if(Number.isFinite(+m.pe))parts.push(`P/E ${(+m.pe).toFixed(1)}`);if(Number.isFinite(+m.revenueGrowth))parts.push(`Tăng trưởng DT ${(+m.revenueGrowth).toFixed(1)}`);return[toneScore(z?.score)[0],parts.join(' · ')||'Có dữ liệu, dùng làm lớp kiểm tra bổ sung.']}
function render(d,m,built,fc,an,ns){const f=built.fs.at(-1),last=+d.history.at(-1).close,rec=VMEWSForecastV4.recommend(fc,d,an,ns),risk=Number.isFinite(+d.current?.technical)?+d.current.technical:f.technical;q('#stance').textContent=rec.label;q('#stance').className=`stance ${rec.tone}`;q('#reason').textContent=rec.text;q('#confidence').textContent=rec.confidence;q('#last').textContent=num(last);q('#risk').textContent=`${Math.round(risk)}/100`;q('#riskText').textContent=riskBand(risk);q('#asof').textContent=`Dữ liệu ${f.date} · mô hình ${m.modelDate}`;q('#chartTitle').textContent=`${d.symbol||''} · Giá thực tế và đường dự báo`;for(const h of[3,4,5])fcCard(h,fc[h],last);q('#r3').textContent=(fc[3].value>=0?'+':'')+pct(fc[3].value);q('#p3').textContent=num(last*Math.exp(fc[3].value));q('#r5').textContent=(fc[5].value>=0?'+':'')+pct(fc[5].value);q('#p5').textContent=num(last*Math.exp(fc[5].value));const market=+d?.modules?.market?.score,macro=+d?.modules?.macro?.score,st=Number.isFinite(+d?.modules?.sentiment?.score)?+d.modules.sentiment.score:ns.score,[ml,mc]=toneScore(market),[xl,xc]=toneScore(macro),[sl,sc]=toneScore(st),[fl,fs]=fundamentals(d);q('#market').textContent=ml;q('#market').className=mc;q('#marketSub').textContent=Number.isFinite(market)?`${market.toFixed(0)}/100`:'Chưa có dữ liệu';q('#macro').textContent=xl;q('#macro').className=xc;q('#macroSub').textContent=Number.isFinite(macro)?`${macro.toFixed(0)}/100`:'Dùng mức nền trong mô hình';q('#sentiment').textContent=sl;q('#sentiment').className=sc;q('#sentimentSub').textContent=`${ns.n||d.news?.length||0} tin được đối chiếu`;q('#fund').textContent=fl;q('#fundSub').textContent=fs;const a5=an[5];q('#analog').textContent=a5?`${Math.round(a5.positive*100)}% tăng`:'—';q('#analogSub').textContent=a5?`Trung vị T+5 ${(a5.median>=0?'+':'')+pct(a5.median)} · ${a5.n} trạng thái`:'Không đủ trạng thái';const vx=factor(d,'vix'),uv=factor(d,'usdVnd'),dx=factor(d,'dxy'),tn=factor(d,'us10y'),br=factor(d,'brent');q('#contextDetail').textContent=[vx&&`VIX ${(+vx.last).toFixed(1)} (${pct(vx.ret20)}/20P)`,uv&&`USD/VND ${pct(uv.ret20)}/20P`,dx&&`DXY ${pct(dx.ret20)}/20P`,tn&&`US10Y ${pct(tn.ret20)}/20P`,br&&`Brent ${pct(br.ret20)}/20P`].filter(Boolean).join(' · ')||'Bối cảnh vĩ mô đã được đưa vào mô hình theo dữ liệu tại thời điểm huấn luyện; dữ liệu live hiện chưa đầy đủ.';renderBT(m);draw(d.history,fc);lastView={d,fc}}
async function run(s){q('#app').classList.add('loading');q('#error').classList.add('hidden');try{const [d,m]=await Promise.all([detail(s),model()]);if(m.promotion?.status!=='PASS')throw Error('Mô hình hiện chưa vượt điều kiện kiểm định để phát hành.');const built=VMEWSForecastV4.features(d.history);if(!built.fs.length)throw Error('Không đủ lịch sử để tạo đặc trưng mô hình.');const news=await newsFor(String(s).toUpperCase(),d),ns=VMEWSForecastV4.sentiment(news),fc=VMEWSForecastV4.forecast(m,built.fs.at(-1),d),an=VMEWSForecastV4.analog(built.rows,built.fs);renderNews(news);render(d,m,built,fc,an,ns);history.replaceState(null,'',`?symbol=${encodeURIComponent(String(s).toUpperCase())}`)}catch(e){q('#error').textContent=e.message||String(e);q('#error').classList.remove('hidden')}finally{q('#app').classList.remove('loading')}}
q('#run').onclick=()=>run(q('#symbol').value);q('#symbol').onkeydown=e=>{if(e.key==='Enter')run(q('#symbol').value)};document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{q('#symbol').value=b.dataset.s;run(b.dataset.s)});window.onresize=()=>{if(lastView)draw(lastView.d.history,lastView.fc)};const s=new URLSearchParams(location.search).get('symbol')||'FPT';q('#symbol').value=s;run(s);
})();