(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.VMEWSForecastCore=api;})(typeof self!=='undefined'?self:this,function(){
'use strict';
const EPS=1e-12, ALPHAS=[0.1,1,10,100,1000];
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const sd=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function quantile(a,q){const z=a.filter(Number.isFinite).slice().sort((x,y)=>x-y);if(!z.length)return 0;const p=clamp(q,0,1)*(z.length-1),lo=Math.floor(p),hi=Math.ceil(p),w=p-lo;return z[lo]*(1-w)+z[hi]*w}
function solve(A,b){const n=A.length,M=A.map((r,i)=>r.slice().concat([b[i]]));for(let i=0;i<n;i++){let p=i;for(let j=i+1;j<n;j++)if(Math.abs(M[j][i])>Math.abs(M[p][i]))p=j;if(Math.abs(M[p][i])<1e-10)M[p][i]=(M[p][i]>=0?1:-1)*1e-8;[M[i],M[p]]=[M[p],M[i]];const d=M[i][i]||1e-8;for(let k=i;k<=n;k++)M[i][k]/=d;for(let j=0;j<n;j++){if(j===i)continue;const f=M[j][i];for(let k=i;k<=n;k++)M[j][k]-=f*M[i][k]}}return M.map(r=>r[n])}
function standardizer(X){const p=X[0].length,mu=[],sig=[];for(let j=0;j<p;j++){const a=X.map(r=>r[j]);mu[j]=mean(a);sig[j]=sd(a)||1}return{mu,sig}}
function zrow(x,s){return x.map((v,j)=>(v-s.mu[j])/s.sig[j])}
function ridgeFit(X,y,alpha){const s=standardizer(X),Z=X.map(x=>[1].concat(zrow(x,s))),p=Z[0].length,A=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);for(let i=0;i<Z.length;i++)for(let j=0;j<p;j++){b[j]+=Z[i][j]*y[i];for(let k=0;k<p;k++)A[j][k]+=Z[i][j]*Z[i][k]}for(let j=1;j<p;j++)A[j][j]+=alpha;return{s,beta:solve(A,b)}}
function ridgePredict(m,X){return X.map(x=>{const z=[1].concat(zrow(x,m.s));return z.reduce((s,v,j)=>s+v*m.beta[j],0)})}
function nwT(d,lag){const n=d.length;if(n<20)return 0;const m=mean(d),e=d.map(x=>x-m);let v=mean(e.map(x=>x*x));for(let k=1;k<=Math.min(lag,n-1);k++){let g=0;for(let i=k;i<n;i++)g+=e[i]*e[i-k];g/=n;v+=2*(1-k/(lag+1))*g}const se=Math.sqrt(Math.max(v,EPS)/n);return se?m/se:0}
function metrics(y,p,h){const n=y.length;if(!n)return{};let sse=0,mae=0,hit=0,pos=0;const d=[];for(let i=0;i<n;i++){const e=y[i]-p[i];sse+=e*e;mae+=Math.abs(e);if(Math.sign(y[i])===Math.sign(p[i]))hit++;if(y[i]>0)pos++;d.push(y[i]*y[i]-e*e)}const denom=y.reduce((s,x)=>s+x*x,0)||EPS,mid=Math.floor(n/2);const hr=(a,b)=>{let se=0,de=0;for(let i=a;i<b;i++){se+=(y[i]-p[i])**2;de+=y[i]**2}return 1-se/(de||EPS)};return{n,mae:mae/n,rmse:Math.sqrt(sse/n),r2:1-sse/denom,da:hit/n,majority:Math.max(pos/n,1-pos/n),dm:nwT(d,Math.max(1,h-1)),half1:hr(0,mid),half2:hr(mid,n)}}
function buildFeatures(rows){const c=rows.map(r=>+r.close),v=rows.map(r=>+(r.volume||0)),hi=rows.map(r=>+(r.high||r.close)),lo=rows.map(r=>+(r.low||r.close)),lr=Array(c.length).fill(0);for(let i=1;i<c.length;i++)lr[i]=Math.log(c[i]/c[i-1]);const out=[];for(let i=60;i<c.length;i++){const ret=k=>Math.log(c[i]/c[i-k]),rw=lr.slice(i-13,i+1),g=mean(rw.map(x=>Math.max(0,x))),loss=mean(rw.map(x=>Math.max(0,-x))),rsi=loss<EPS?100:100-100/(1+g/loss),vw=v.slice(i-19,i),vz=(v[i]-mean(vw))/(sd(vw)||1),vol5=sd(lr.slice(i-4,i+1))*Math.sqrt(252),vol20=sd(lr.slice(i-19,i+1))*Math.sqrt(252),sma=k=>mean(c.slice(i-k+1,i+1)),peak=k=>Math.max(...c.slice(i-k+1,i+1));const full=[lr[i],lr[i-1],lr[i-2],lr[i-3],lr[i-4],ret(3),ret(5),ret(10),ret(20),vol5,vol20,c[i]/sma(5)-1,c[i]/sma(10)-1,c[i]/sma(20)-1,c[i]/sma(50)-1,c[i]/peak(20)-1,c[i]/peak(60)-1,(rsi-50)/50,vz,(hi[i]-lo[i])/c[i]];out.push({i,full,ar:full.slice(0,9)})}return out}
function tuneRidge(X,y,dev,val,h){let best=null;for(const alpha of ALPHAS){const m=ridgeFit(X.slice(dev[0],dev[1]),y.slice(dev[0],dev[1]),alpha),p=ridgePredict(m,X.slice(val[0],val[1])),mt=metrics(y.slice(val[0],val[1]),p,h),score=mt.r2+.30*(mt.da-mt.majority)-.01*Math.log10(alpha+1);if(!best||score>best.score)best={alpha,score,metrics:mt,pred:p}}return best}
function fitOne(rows,F,h){const eligible=F.filter(f=>f.i+h<rows.length);if(eligible.length<420)return{available:false,reason:'Insufficient history'};const X=eligible.map(f=>f.full),A=eligible.map(f=>f.ar),y=eligible.map(f=>Math.log(rows[f.i+h].close/rows[f.i].close)),n=y.length,a=Math.floor(n*.60),b=Math.floor(n*.80),dev=[0,Math.max(0,a-h)],val=[a,Math.max(a,b-h)],test=[b,n];if(dev[1]<220||val[1]-val[0]<70||test[1]-test[0]<70)return{available:false,reason:'Insufficient split size'};
const full=tuneRidge(X,y,dev,val,h),ar=tuneRidge(A,y,dev,val,h),blendPred=full.pred.map((x,i)=>(x+ar.pred[i])/2),blendMt=metrics(y.slice(val[0],val[1]),blendPred,h),blendScore=blendMt.r2+.30*(blendMt.da-blendMt.majority);const candidates=[{name:'V',score:full.score},{name:'A',score:ar.score},{name:'E',score:blendScore}].sort((u,v)=>v.score-u.score),champ=candidates[0].name,train=[0,Math.max(0,b-h)],yt=y.slice(test[0],test[1]);let pred;
if(champ==='V'){const m=ridgeFit(X.slice(train[0],train[1]),y.slice(train[0],train[1]),full.alpha);pred=ridgePredict(m,X.slice(test[0],test[1]))}else if(champ==='A'){const m=ridgeFit(A.slice(train[0],train[1]),y.slice(train[0],train[1]),ar.alpha);pred=ridgePredict(m,A.slice(test[0],test[1]))}else{const mv=ridgeFit(X.slice(train[0],train[1]),y.slice(train[0],train[1]),full.alpha),ma=ridgeFit(A.slice(train[0],train[1]),y.slice(train[0],train[1]),ar.alpha),pv=ridgePredict(mv,X.slice(test[0],test[1])),pa=ridgePredict(ma,A.slice(test[0],test[1]));pred=pv.map((x,i)=>(x+pa[i])/2)}
const mt=metrics(yt,pred,h),pass=mt.r2>.01&&mt.da>=Math.max(.52,mt.majority-.02)&&mt.dm>1.64&&Math.min(mt.half1,mt.half2)>-.05,resid=yt.map((x,i)=>x-pred[i]),q10=quantile(resid,.10),q90=quantile(resid,.90),cur=F[F.length-1];let forecast=0;
if(champ==='V'){const m=ridgeFit(X,y,full.alpha);forecast=ridgePredict(m,[cur.full])[0]}else if(champ==='A'){const m=ridgeFit(A,y,ar.alpha);forecast=ridgePredict(m,[cur.ar])[0]}else{const mv=ridgeFit(X,y,full.alpha),ma=ridgeFit(A,y,ar.alpha);forecast=(ridgePredict(mv,[cur.full])[0]+ridgePredict(ma,[cur.ar])[0])/2}
return{available:true,horizon:h,forecast,low:forecast+q10,high:forecast+q90,pass,metrics:mt,champion:champ,validationScore:candidates[0].score}}
function run(rows){rows=(rows||[]).filter(r=>Number.isFinite(+r.close)&&+r.close>0).slice().sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(rows.length<500)return{ok:false,reason:'At least 500 completed sessions are required.'};const F=buildFeatures(rows),horizons={};for(let h=1;h<=5;h++)horizons[h]=fitOne(rows,F,h);return{ok:true,rows:rows.length,last:rows[rows.length-1],horizons}}
function recommendation(result,risk){const hs=[3,4,5].map(h=>result.horizons[h]).filter(x=>x&&x.available),passed=hs.filter(x=>x.pass),riskScore=Number.isFinite(+risk)?+risk:50;if(!passed.length)return{label:'HOLD / NO ACTION',tone:'neutral',confidence:'LOW',text:'Short-horizon evidence did not clear the sealed out-of-sample gate. The AI does not promote a directional trade.',edge:false};const w=passed.map(x=>Math.max(.02,x.metrics.r2+.02)),avg=passed.reduce((s,x,i)=>s+w[i]*x.forecast,0)/w.reduce((a,b)=>a+b,0),da=mean(passed.map(x=>x.metrics.da)),grade=passed.length===3&&da>=.54?'HIGH':passed.length>=2?'MODERATE':'LIMITED';if(riskScore>=78)return{label:'REDUCE / AVOID NEW RISK',tone:'negative',confidence:grade,text:'Structural risk is very high, so the risk gate overrides a short-horizon upside forecast.',edge:true,forecast:avg};if(avg>=.012&&riskScore<65)return{label:'ACCUMULATE',tone:'positive',confidence:grade,text:'Validated 3–5 session evidence is positive and structural risk is not elevated.',edge:true,forecast:avg};if(avg>=.004)return{label:'HOLD / POSITIVE BIAS',tone:'positive',confidence:grade,text:'Validated short-horizon evidence is mildly positive, but the expected edge is not large enough for a stronger stance.',edge:true,forecast:avg};if(avg<=-.012)return{label:'REDUCE',tone:'negative',confidence:grade,text:'Validated 3–5 session evidence is negative with a material expected downside path.',edge:true,forecast:avg};if(avg<=-.004)return{label:'CAUTION / REDUCE RISK',tone:'negative',confidence:grade,text:'Validated short-horizon evidence is mildly negative; new risk should be limited.',edge:true,forecast:avg};return{label:'HOLD',tone:'neutral',confidence:grade,text:'The model cleared validation, but the expected 3–5 session move is too small for a directional stance.',edge:true,forecast:avg}}
return{run,recommendation,metrics,buildFeatures};
});
