(()=>{
'use strict';
const MARKET='https://cdn.githubraw.com/NCKHtop1/vmews-risk-analytics/main/data/market-scan.json';
const priorFetch=window.fetch.bind(window);
let lastDetail=null, range='1Y', marketPromise=null, ro=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number.isFinite(+x)?new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(+x):'—';
const pct=x=>Number.isFinite(+x)?`${(+x*100).toFixed(1)}%`:'—';
function isDetail(input){try{const raw=typeof input==='string'?input:(input?.url||String(input));const u=new URL(raw,location.href);return u.pathname==='/api/stocks2'&&u.searchParams.get('mode')==='detail'}catch{return false}}
function injectStyle(){if(document.getElementById('vmewsChartStyle'))return;const s=document.createElement('style');s.id='vmewsChartStyle';s.textContent=`
.investorChart{margin-top:14px;border:1px solid var(--line);border-radius:10px;background:#08141e;overflow:hidden}.chartHead{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;padding:15px 16px 10px;border-bottom:1px solid var(--line)}.chartHead h3{margin:3px 0 2px;font-size:18px}.chartHead p{margin:0;color:var(--muted);font-size:12px}.chartTools{display:flex;gap:6px;flex-wrap:wrap}.chartTools button{border:1px solid var(--line);background:#102130;color:var(--text);border-radius:6px;padding:6px 9px;cursor:pointer;font-size:11px}.chartTools button.active{background:#23435d}.chartStats{display:grid;grid-template-columns:repeat(6,1fr);gap:1px;background:var(--line);border-bottom:1px solid var(--line)}.chartStats>div{background:#091722;padding:10px 12px;min-width:0}.chartStats span,.chartStats b{display:block}.chartStats span{font-size:10px;color:var(--muted);text-transform:uppercase;letter-spacing:.04em}.chartStats b{margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chartStage{position:relative;padding:8px 8px 2px}.chartStage svg{display:block;width:100%;height:auto;min-height:360px}.chartTooltip{position:absolute;pointer-events:none;display:none;z-index:3;background:#061019;border:1px solid #31495b;border-radius:7px;padding:8px 10px;box-shadow:0 8px 26px rgba(0,0,0,.35);font-size:11px;line-height:1.45;min-width:160px}.chartTooltip b,.chartTooltip span{display:block}.chartTooltip span{color:var(--muted)}.chartLegend{display:flex;gap:16px;flex-wrap:wrap;padding:8px 16px 13px;color:var(--muted);font-size:11px}.chartLegend i{display:inline-block;width:16px;height:2px;vertical-align:middle;margin-right:5px;background:#c7d5df}.chartLegend .s50{background:#8db5d3}.chartLegend .s200{background:#8fc9a6}.chartLegend .warnY,.chartLegend .warnR{width:8px;height:8px;border-radius:50%}.chartLegend .warnY{background:#d7b06c}.chartLegend .warnR{background:#dc8f8f}.chartNote{padding:0 16px 13px;color:var(--muted);font-size:11px}.chartEmpty{padding:20px;color:var(--muted)}@media(max-width:900px){.chartStats{grid-template-columns:repeat(3,1fr)}.chartHead{flex-direction:column}}@media(max-width:600px){.chartStats{grid-template-columns:repeat(2,1fr)}}`;
document.head.appendChild(s)}
function ensure(){injectStyle();let root=document.getElementById('investorChart');if(root)return root;const panel=document.getElementById('analysisPanel');if(!panel)return null;root=document.createElement('section');root.id='investorChart';root.className='investorChart';const anchor=document.getElementById('moduleGrid');if(anchor)panel.insertBefore(root,anchor);else panel.appendChild(root);return root}
function ma(rows,n){let sum=0;return rows.map((r,i)=>{sum+=+r.close||0;if(i>=n)sum-=+rows[i-n].close||0;return i>=n-1?sum/n:null})}
function rangeRows(rows){const n=range==='6M'?126:range==='1Y'?252:range==='3Y'?756:99999;return rows.slice(-Math.min(n,rows.length))}
function loadMarket(){return marketPromise||(marketPromise=priorFetch(`${MARKET}?t=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null))}
function marketItem(p,symbol){const all=[...(p?.redList||[]),...(p?.yellowList||[]),...(p?.ranking||[])];return all.find(x=>x.symbol===symbol)||null}
function makeSignals(rows,scoreHistory){const sm=new Map((scoreHistory||[]).map(x=>[x.date,+x.technical]));let prev=0,lastIdx=-999;const out=[];rows.forEach((r,i)=>{const v=sm.get(r.date);if(!Number.isFinite(v))return;const band=v>=70?2:v>=55?1:0;if(band>prev&&band>0&&i-lastIdx>=10){out.push({i,date:r.date,score:v,level:band===2?'RED':'YELLOW'});lastIdx=i}prev=band});return out}
function linePath(vals,x,y){let d='',started=false;vals.forEach((v,i)=>{if(!Number.isFinite(v)){started=false;return}d+=`${started?'L':'M'}${x(i).toFixed(2)},${y(v).toFixed(2)}`;started=true});return d}
function render(detail){lastDetail=detail;const root=ensure();if(!root)return;const all=(detail.history||[]).filter(x=>Number.isFinite(+x.close)&&+x.close>0);if(all.length<2){root.innerHTML='<div class="chartEmpty">Price history is not sufficient to draw a chart.</div>';return}const rows=rangeRows(all),offset=all.length-rows.length;const sma50All=ma(all,50),sma200All=ma(all,200),s50=sma50All.slice(offset),s200=sma200All.slice(offset);const closes=rows.map(x=>+x.close),vols=rows.map(x=>+x.volume||0),signals=makeSignals(all,detail.scoreHistory).filter(s=>s.i>=offset).map(s=>({...s,i:s.i-offset}));
const W=1060,H=430,L=70,R=22,T=20,PRICE_B=328,VTOP=345,VB=398,PW=W-L-R,PH=PRICE_B-T;const valid=[...closes,...s50.filter(Number.isFinite),...s200.filter(Number.isFinite)];let ymin=Math.min(...valid),ymax=Math.max(...valid);const pad=(ymax-ymin||ymax*.08||1)*.08;ymin-=pad;ymax+=pad;const vmax=Math.max(...vols,1);const x=i=>L+(rows.length<=1?0:i/(rows.length-1))*PW;const y=v=>T+(ymax-v)/(ymax-ymin)*PH;const vy=v=>VB-(v/vmax)*(VB-VTOP);let grid='',labels='';for(let k=0;k<5;k++){const yy=T+k*PH/4,val=ymax-k*(ymax-ymin)/4;grid+=`<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" stroke="#173041" stroke-width="1"/>`;labels+=`<text x="${L-8}" y="${yy+4}" text-anchor="end" fill="#7890a1" font-size="10">${esc(fmt(val))}</text>`}const ticks=[0,.25,.5,.75,1].map(q=>Math.round(q*(rows.length-1)));for(const i of ticks){const xx=x(i);labels+=`<text x="${xx}" y="${H-8}" text-anchor="middle" fill="#7890a1" font-size="10">${esc(rows[i].date.slice(5))}</text>`}
const bars=vols.map((v,i)=>`<rect x="${(x(i)-Math.max(1,PW/rows.length*.32)).toFixed(1)}" y="${vy(v).toFixed(1)}" width="${Math.max(1,PW/rows.length*.64).toFixed(1)}" height="${Math.max(0,VB-vy(v)).toFixed(1)}" fill="#274258" opacity=".55"/>`).join('');const sigs=signals.map(s=>{const xx=x(s.i),yy=y(+rows[s.i].close),fill=s.level==='RED'?'#dc8f8f':'#d7b06c';return `<g><line x1="${xx}" y1="${T}" x2="${xx}" y2="${PRICE_B}" stroke="${fill}" opacity=".22" stroke-dasharray="3 5"/><circle cx="${xx}" cy="${yy}" r="5" fill="${fill}" stroke="#08141e" stroke-width="2"/><text x="${xx}" y="${Math.max(T+10,yy-9)}" text-anchor="middle" fill="${fill}" font-size="9" font-weight="700">${s.level==='RED'?'R':'Y'}</text></g>`}).join('');
const last=rows.at(-1),cur=detail.current||{},source=detail.source?.price||detail.audit?.[0]?.source||'Price history';root.innerHTML=`<div class="chartHead"><div><span class="eyebrow">INVESTOR OBSERVATION CHART</span><h3>${esc(detail.symbol)} · Price & warning history</h3><p>Completed EOD prices. Warning markers show entry into structural EWS YELLOW/RED bands; they are risk-review flags, not buy/sell signals.</p></div><div class="chartTools">${['6M','1Y','3Y','ALL'].map(r=>`<button data-range="${r}" class="${range===r?'active':''}">${r}</button>`).join('')}</div></div><div class="chartStats"><div><span>Last close</span><b>${fmt(last.close)}</b></div><div><span>20D return</span><b>${pct(cur.mom20)}</b></div><div><span>60D drawdown</span><b>${pct(cur.dd60)}</b></div><div><span>Technical risk</span><b>${Number.isFinite(+cur.technical)?Math.round(+cur.technical)+'/100':'—'}</b></div><div><span>T-Day alert</span><b id="chartTDay">Checking…</b></div><div><span>Price source</span><b title="${esc(source)}">${esc(source)}</b></div></div><div class="chartStage"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(detail.symbol)} price chart with moving averages and warning markers">${grid}<line x1="${L}" y1="${PRICE_B}" x2="${W-R}" y2="${PRICE_B}" stroke="#294152"/><line x1="${L}" y1="${VTOP}" x2="${W-R}" y2="${VTOP}" stroke="#173041"/>${bars}<path d="${linePath(s200,x,y)}" fill="none" stroke="#8fc9a6" stroke-width="1.4" opacity=".85"/><path d="${linePath(s50,x,y)}" fill="none" stroke="#8db5d3" stroke-width="1.5" opacity=".9"/><path d="${linePath(closes,x,y)}" fill="none" stroke="#e1e8ed" stroke-width="2"/>${sigs}${labels}<text x="${L}" y="${VTOP-5}" fill="#7890a1" font-size="9">VOLUME</text><rect id="chartHover" x="${L}" y="${T}" width="${PW}" height="${VB-T}" fill="transparent"/></svg><div id="chartTooltip" class="chartTooltip"></div></div><div class="chartLegend"><span><i></i>Close</span><span><i class="s50"></i>SMA50</span><span><i class="s200"></i>SMA200</span><span><i class="warnY"></i>YELLOW entry ≥55 technical</span><span><i class="warnR"></i>RED entry ≥70 technical</span></div><div id="chartDrivers" class="chartNote">T-Day market-wide status is loaded independently from the latest completed market snapshot.</div>`;
root.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=b.dataset.range;render(lastDetail)});const hover=root.querySelector('#chartHover'),tip=root.querySelector('#chartTooltip'),stage=root.querySelector('.chartStage');hover.addEventListener('pointermove',ev=>{const box=hover.getBoundingClientRect(),q=Math.max(0,Math.min(1,(ev.clientX-box.left)/box.width)),i=Math.round(q*(rows.length-1)),r=rows[i],tv=new Map((detail.scoreHistory||[]).map(z=>[z.date,+z.technical])).get(r.date);tip.innerHTML=`<b>${esc(r.date)} · ${fmt(r.close)}</b><span>SMA50 ${fmt(s50[i])} · SMA200 ${fmt(s200[i])}</span><span>Volume ${fmt(r.volume)}</span><span>Structural risk ${Number.isFinite(tv)?Math.round(tv)+'/100':'N/A'}</span>`;const sb=stage.getBoundingClientRect();tip.style.display='block';tip.style.left=`${Math.min(sb.width-175,Math.max(8,ev.clientX-sb.left+12))}px`;tip.style.top=`${Math.max(8,ev.clientY-sb.top-72)}px`});hover.addEventListener('pointerleave',()=>tip.style.display='none');
loadMarket().then(p=>{if(detail!==lastDetail)return;const m=marketItem(p,detail.symbol),b=root.querySelector('#chartTDay'),d=root.querySelector('#chartDrivers');if(!b)return;if(m){b.textContent=`${m.status} · ${Math.round(+m.score||0)}/100`;b.className=m.status==='RED'?'red':m.status==='YELLOW'?'amber':'';d.textContent=`T-Day ${m.status}: ${(m.drivers||[]).slice(0,4).join(' · ')||'No driver text available'} · ${m.exchange||'VN market'} · model date ${p.modelDate||m.date||'—'}.`}else{b.textContent='Not in alert shortlist';d.textContent='The security is not in the current RED/YELLOW market-wide shortlist. Single-name structural and model evidence remain available independently.'}});
if(ro)ro.disconnect();if(window.ResizeObserver){ro=new ResizeObserver(()=>{});ro.observe(root)}}
async function capture(r){try{const p=await r.clone().json();if(p?.mode==='detail'&&p?.symbol){window.__VMEWS_LAST_DETAIL__=p;setTimeout(()=>render(p),0)}}catch{}}
window.fetch=async(input,init)=>{const r=await priorFetch(input,init);if(isDetail(input)&&r.ok)capture(r);return r};
window.VMEWSInvestorChart={render,latest:()=>lastDetail};
})();
