(()=>{
'use strict';
const EPS=1e-9;
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const sd=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)*(x-m),0)/(a.length-1))};
const quantile=(a,p)=>{if(!a.length)return 0;const x=[...a].sort((u,v)=>u-v),q=clamp(p)*(x.length-1),i=Math.floor(q),j=Math.min(x.length-1,i+1),w=q-i;return x[i]*(1-w)+x[j]*w};
const sigmoid=x=>1/(1+Math.exp(-Math.max(-30,Math.min(30,x))));
const pctRank=(v,a)=>a.length?a.filter(x=>x<=v).length/a.length:.5;
function ema(a,n){const k=2/(n+1);let e=null;return a.map(v=>e=e==null?v:k*v+(1-k)*e)}
function rsi(a,i,n=14){if(i<n)return 50;let g=0,l=0;for(let j=i-n+1;j<=i;j++){const d=a[j]-a[j-1];g+=Math.max(0,d);l+=Math.max(0,-d)}g/=n;l/=n;return l<EPS?100:100-100/(1+g/l)}
function safeRows(rows){
  const x=(rows||[]).filter(r=>Number.isFinite(+r.close)&&+r.close>0).map(r=>({...r,close:+r.close,volume:Number.isFinite(+r.volume)?+r.volume:0})).sort((a,b)=>String(a.date).localeCompare(String(b.date)));
  const suspect=[];for(let i=1;i<x.length;i++){const lr=Math.log(x[i].close/x[i-1].close);if(Math.abs(lr)>.22)suspect.push({date:x[i].date,logReturn:lr})}
  return {rows:x,suspect};
}
function buildFeatures(raw){
  const {rows,suspect}=safeRows(raw),c=rows.map(r=>r.close),v=rows.map(r=>r.volume),ret=[0];
  for(let i=1;i<c.length;i++){let z=Math.log(c[i]/c[i-1]);if(Math.abs(z)>.22)z=0;ret.push(z)}
  const e12=ema(c,12),e26=ema(c,26),macd=e12.map((x,i)=>x-e26[i]),sig=ema(macd,9),out=[];
  for(let i=200;i<rows.length;i++){
    const vol20=sd(ret.slice(i-19,i+1))*Math.sqrt(252),histVol=[];for(let j=Math.max(200,i-252);j<i;j++)histVol.push(sd(ret.slice(j-19,j+1))*Math.sqrt(252));
    const peak=Math.max(...c.slice(i-59,i+1)),ma50=mean(c.slice(i-49,i+1)),ma200=mean(c.slice(i-199,i+1));
    const vh=v.slice(i-20,i).filter(x=>x>0),vz=vh.length?(v[i]-mean(vh))/(sd(vh)||1):0;
    const f={i,date:rows[i].date,close:c[i],ret1:ret[i],ret5:c[i]/c[i-5]-1,mom20:c[i]/c[i-20]-1,dd60:c[i]/peak-1,trend50:c[i]/ma50-1,trend200:c[i]/ma200-1,vol20,volPct:pctRank(vol20,histVol),rsi14:rsi(c,i),macdNorm:c[i]?(macd[i]-sig[i])/c[i]:0,volumeZ:vz};
    const p=[clamp(Math.abs(Math.min(f.dd60,0))/.22),clamp(Math.abs(Math.min(f.mom20,0))/.14),clamp(Math.abs(Math.min(f.trend50,0))/.12),clamp(Math.abs(Math.min(f.trend200,0))/.18),clamp((f.volPct-.45)/.55),clamp((45-f.rsi14)/20),clamp(Math.max(0,-f.macdNorm)/.025),clamp(Math.max(0,vz)/3)*clamp(Math.max(0,-ret[i])/.05)];
    f.technical=100*(.18*p[0]+.16*p[1]+.14*p[2]+.10*p[3]+.16*p[4]+.10*p[5]+.08*p[6]+.08*p[7]);
    f.vector=[f.vol20,f.dd60,f.mom20,f.trend50,f.trend200,f.rsi14/100,f.macdNorm,f.volumeZ/5];out.push(f);
  }
  return {rows,features:out,suspect};
}
function futurePath(rows,i,h=20){if(i+h>=rows.length)return null;const b=rows[i].close;let mn=0,mx=0;for(let j=i+1;j<=i+h;j++){const r=rows[j].close/b-1;mn=Math.min(mn,r);mx=Math.max(mx,r)}return {drawdown:mn,rebound:mx}}
function makeSamples(raw,step=5){const b=buildFeatures(raw),fs=b.features,rows=b.rows,s=[];for(let k=0;k<fs.length;k+=step){const f=fs[k],p=futurePath(rows,f.i,20);if(!p)continue;s.push({...f,crash:p.drawdown<=-.12,rebound:p.rebound>=.12,forwardDrawdown:p.drawdown,forwardRebound:p.rebound})}return {...b,samples:s}}
function standardizer(X){const d=X[0]?.length||0,mu=[],sg=[];for(let j=0;j<d;j++){const a=X.map(x=>x[j]);mu[j]=mean(a);sg[j]=sd(a)||1}return {transform:x=>x.map((v,j)=>(v-mu[j])/sg[j]),mu,sg}}
function kmeans(X,k=4,iters=30){if(X.length<k)return null;const st=standardizer(X),Z=X.map(st.transform),cent=[];for(let j=0;j<k;j++)cent.push([...Z[Math.floor(j*(Z.length-1)/(k-1))]]);let lab=new Array(Z.length).fill(0);for(let it=0;it<iters;it++){let ch=0;for(let i=0;i<Z.length;i++){let bi=0,bd=Infinity;for(let q=0;q<k;q++){const d=Z[i].reduce((s,v,j)=>s+(v-cent[q][j])**2,0);if(d<bd){bd=d;bi=q}}if(lab[i]!==bi){lab[i]=bi;ch++}}for(let q=0;q<k;q++){const pts=Z.filter((_,i)=>lab[i]===q);if(pts.length)cent[q]=cent[q].map((_,j)=>mean(pts.map(x=>x[j])))}if(!ch)break}return {labels:lab,centroids:cent,standardizer:st,predict:x=>{const z=st.transform(x);let bi=0,bd=Infinity;for(let q=0;q<k;q++){const d=z.reduce((s,v,j)=>s+(v-cent[q][j])**2,0);if(d<bd){bd=d;bi=q}}return bi}}}
function regimeModel(samples){const X=samples.map(s=>s.vector),km=kmeans(X,4);if(!km)return null;const meta=[];for(let q=0;q<4;q++){const pts=samples.filter((_,i)=>km.labels[i]===q);meta[q]={n:pts.length,crashRate:pts.length?mean(pts.map(x=>x.crash?1:0)):0,vol:pts.length?mean(pts.map(x=>x.vol20)):0,mom:pts.length?mean(pts.map(x=>x.mom20)):0,dd:pts.length?mean(pts.map(x=>x.dd60)):0}}return {predict:x=>km.predict(x),meta,raw:km}}
function gini(y){if(!y.length)return 0;const p=mean(y);return 2*p*(1-p)}
function bestSplit(X,y,idxs,features){let best=null;for(const j of features){const vals=idxs.map(i=>X[i][j]).sort((a,b)=>a-b);const qs=[.2,.4,.6,.8].map(p=>quantile(vals,p));for(const t of qs){const L=idxs.filter(i=>X[i][j]<=t),R=idxs.filter(i=>X[i][j]>t);if(L.length<5||R.length<5)continue;const loss=(L.length*gini(L.map(i=>y[i]))+R.length*gini(R.map(i=>y[i])))/idxs.length;if(!best||loss<best.loss)best={j,t,L,R,loss}}}return best}
function treeTrain(X,y,idxs,depth,maxDepth,mtry,rng){const p=mean(idxs.map(i=>y[i]));if(depth>=maxDepth||idxs.length<18||p<.03||p>.97)return {p};const d=X[0].length,features=[];while(features.length<Math.min(mtry,d)){const j=Math.floor(rng()*d);if(!features.includes(j))features.push(j)}const b=bestSplit(X,y,idxs,features);if(!b)return {p};return {j:b.j,t:b.t,p,left:treeTrain(X,y,b.L,depth+1,maxDepth,mtry,rng),right:treeTrain(X,y,b.R,depth+1,maxDepth,mtry,rng)}}
function mulberry(seed=1234567){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function rfTrain(X,y,nTrees=60,maxDepth=4){const rng=mulberry(137),trees=[],n=X.length,mtry=Math.max(2,Math.round(Math.sqrt(X[0].length)));for(let t=0;t<nTrees;t++){const idx=[];for(let i=0;i<n;i++)idx.push(Math.floor(rng()*n));trees.push(treeTrain(X,y,idx,0,maxDepth,mtry,rng))}const predTree=(tr,x)=>tr.j==null?tr.p:predTree(x[tr.j]<=tr.t?tr.left:tr.right,x);return {predict:x=>mean(trees.map(t=>predTree(t,x))),trees}}
function anfisTrain(samples,iters=350,lr=.08){const X=samples.map(s=>[s.dd60,s.mom20,s.trend50,s.volPct,s.rsi14/100]),y=samples.map(s=>s.crash?1:0),d=X[0].length;const qs=[];for(let j=0;j<d;j++){const a=X.map(x=>x[j]);qs[j]=[quantile(a,.2),quantile(a,.5),quantile(a,.8),sd(a)||1]}const rules=[];for(let j=0;j<d;j++)for(let m=0;m<3;m++)rules.push([j,m]);rules.push(['joint',0]);rules.push(['joint',1]);const fire=x=>rules.map(r=>{if(r[0]==='joint'){const risk=r[1]===0?[(1-x[1]),(1-x[2]),x[3]]:[(1-x[0]),x[3],(1-x[4])];return clamp(risk.map(v=>sigmoid(v)).reduce((a,b)=>a*b,1),1e-5,1)}const [j,m]=r,[q1,q2,q3,s]=qs[j],c=[q1,q2,q3][m],w=Math.max(s*.55,1e-3);return Math.exp(-.5*((x[j]-c)/w)**2)});const W=new Array(rules.length+1).fill(0);for(let it=0;it<iters;it++){const g=new Array(W.length).fill(0);for(let i=0;i<X.length;i++){const f=fire(X[i]),sum=f.reduce((a,b)=>a+b,0)||1,z=W[0]+f.reduce((a,b,j)=>a+b/sum*W[j+1],0),p=sigmoid(z),e=p-y[i];g[0]+=e;for(let j=0;j<f.length;j++)g[j+1]+=e*f[j]/sum}for(let j=0;j<W.length;j++)W[j]-=lr*g[j]/X.length}return {predict:x=>{const f=fire([x.dd60,x.mom20,x.trend50,x.volPct,x.rsi14/100]),s=f.reduce((a,b)=>a+b,0)||1;return sigmoid(W[0]+f.reduce((a,b,j)=>a+b/s*W[j+1],0))},weights:W}}
function auc(y,p){const pos=[],neg=[];for(let i=0;i<y.length;i++)(y[i]?pos:neg).push(p[i]);if(!pos.length||!neg.length)return null;let w=0,t=0;for(const a of pos)for(const b of neg){if(a>b)w++;else if(a===b)t++}return(w+.5*t)/(pos.length*neg.length)}
function metrics(y,p,thr=.5){let tp=0,fp=0,tn=0,fn=0;for(let i=0;i<y.length;i++){const h=p[i]>=thr;if(h&&y[i])tp++;else if(h)fp++;else if(y[i])fn++;else tn++}const precision=tp+fp?tp/(tp+fp):null,recall=tp+fn?tp/(tp+fn):null,fpr=fp+tn?fp/(fp+tn):null,f1=precision!=null&&recall!=null&&precision+recall?2*precision*recall/(precision+recall):null;return {tp,fp,tn,fn,precision,recall,fpr,f1,auc:auc(y,p)}}
async function vaeTrain(X,epochs=10,latent=3){if(!window.tf||X.length<80)return null;const tf=window.tf,st=standardizer(X),Z=X.map(st.transform),d=Z[0].length,h=10;const vars={We:tf.variable(tf.randomNormal([d,h],0,.12)),be:tf.variable(tf.zeros([h])),Wm:tf.variable(tf.randomNormal([h,latent],0,.12)),bm:tf.variable(tf.zeros([latent])),Wv:tf.variable(tf.randomNormal([h,latent],0,.05)),bv:tf.variable(tf.fill([latent],-1)),Wd:tf.variable(tf.randomNormal([latent,d],0,.12)),bd:tf.variable(tf.zeros([d]))};const opt=tf.train.adam(.015),xt=tf.tensor2d(Z);for(let ep=0;ep<epochs;ep++){opt.minimize(()=>tf.tidy(()=>{const hh=xt.matMul(vars.We).add(vars.be).tanh(),mu=hh.matMul(vars.Wm).add(vars.bm),lv=hh.matMul(vars.Wv).add(vars.bv).clipByValue(-4,3),eps=tf.randomNormal(mu.shape),z=mu.add(lv.mul(.5).exp().mul(eps)),rec=z.matMul(vars.Wd).add(vars.bd),mse=rec.sub(xt).square().mean(),kl=tf.scalar(-.5).mul(tf.scalar(1).add(lv).sub(mu.square()).sub(lv.exp())).mean();return mse.add(kl.mul(.03))}),true,Object.values(vars));await tf.nextFrame()}const score=x=>tf.tidy(()=>{const q=tf.tensor2d([st.transform(x)]),hh=q.matMul(vars.We).add(vars.be).tanh(),mu=hh.matMul(vars.Wm).add(vars.bm),rec=mu.matMul(vars.Wd).add(vars.bd),e=rec.sub(q).square().mean();return e.dataSync()[0]});const trainErr=Z.map((_,i)=>score(X[i])),m=mean(trainErr),s=sd(trainErr)||1;return {score:x=>clamp((score(x)-m)/(3*s)+.33),raw:score,dispose:()=>{xt.dispose();Object.values(vars).forEach(v=>v.dispose())}}}
async function lstmTrain(samples,epochs=7,seq=12){if(!window.tf||samples.length<100)return null;const tf=window.tf,X=[],Y=[];for(let i=seq;i<samples.length;i++){X.push(samples.slice(i-seq,i).map(s=>s.vector));Y.push([samples[i].crash?1:0,samples[i].rebound?1:0])}if(X.length<80)return null;const flat=X.flat(),st=standardizer(flat),XZ=X.map(q=>q.map(st.transform));const xs=tf.tensor3d(XZ),ys=tf.tensor2d(Y);const model=tf.sequential();model.add(tf.layers.lstm({units:10,inputShape:[seq,XZ[0][0].length],dropout:.05,recurrentDropout:0}));model.add(tf.layers.dense({units:2,activation:'sigmoid'}));model.compile({optimizer:tf.train.adam(.01),loss:'binaryCrossentropy'});await model.fit(xs,ys,{epochs,batchSize:24,shuffle:false,verbose:0});xs.dispose();ys.dispose();return {predict:seqRows=>tf.tidy(()=>{const z=seqRows.map(s=>st.transform(s.vector)),t=tf.tensor3d([z]),o=model.predict(t).dataSync();return {crash:o[0],rebound:o[1]}}),dispose:()=>model.dispose()}}
function structuralProb(s){return clamp(sigmoid((s.technical-48)/11 + Math.max(0,-s.mom20)*4 + Math.max(0,-s.trend50)*3))}
async function trainBundle(train){const X=train.map(s=>s.vector),y=train.map(s=>s.crash?1:0),rf=rfTrain(X,y),anf=anfisTrain(train),reg=regimeModel(train),vae=await vaeTrain(X,8),lstm=await lstmTrain(train,5);return {rf,anf,reg,vae,lstm}}
function predictBundle(bundle,history,currentIdx){const s=history[currentIdx],regime=bundle.reg?bundle.reg.predict(s.vector):null,regRisk=regime==null?.5:(bundle.reg.meta[regime]?.crashRate||0),rf=bundle.rf.predict(s.vector),anf=bundle.anf.predict(s),vae=bundle.vae?bundle.vae.score(s.vector):null;let dl=null;if(bundle.lstm&&currentIdx>=12)dl=bundle.lstm.predict(history.slice(currentIdx-12,currentIdx));const lstmCrash=dl?dl.crash:null,lstmRebound=dl?dl.rebound:null;const parts=[[structuralProb(s),.25],[rf,.20],[anf,.15],[regRisk,.10]];if(vae!=null)parts.push([vae,.10]);if(lstmCrash!=null)parts.push([lstmCrash,.20]);const w=parts.reduce((a,b)=>a+b[1],0),ensemble=parts.reduce((a,b)=>a+b[0]*b[1],0)/(w||1);return {structural:structuralProb(s),randomForest:rf,anfis:anf,regime:regRisk,regimeId:regime,vae,lstmCrash,lstmRebound,ensemble}}
function disposeBundle(b){try{b.vae?.dispose()}catch{}try{b.lstm?.dispose()}catch{}}
async function walkForward(samples){if(samples.length<180)return {status:'INSUFFICIENT',folds:[]};const n=samples.length,purge=4,cuts=[[.50,.66],[.66,.82],[.82,1]],folds=[],all={ensemble:[],rf:[],anfis:[],lstm:[],vae:[],structural:[],y:[]};for(let f=0;f<cuts.length;f++){const [a,b]=cuts[f],testStart=Math.floor(n*a),testEnd=Math.floor(n*b),train=samples.slice(0,Math.max(80,testStart-purge)),test=samples.slice(testStart,testEnd);if(train.length<80||test.length<20)continue;const bundle=await trainBundle(train),pred={ensemble:[],rf:[],anfis:[],lstm:[],vae:[],structural:[]},y=[];const seqBase=train.concat(test);for(let j=0;j<test.length;j++){const idx=train.length+j,r=predictBundle(bundle,seqBase,idx);y.push(test[j].crash?1:0);for(const k of Object.keys(pred))pred[k].push(k==='rf'?r.randomForest:k==='anfis'?r.anfis:k==='lstm'?(r.lstmCrash??.5):k==='vae'?(r.vae??.5):r[k])}const fm={from:test[0].date,to:test.at(-1).date,n:test.length,events:y.reduce((a,b)=>a+b,0)};for(const k of Object.keys(pred)){fm[k]=metrics(y,pred[k]);all[k].push(...pred[k])}all.y.push(...y);folds.push(fm);disposeBundle(bundle)}const aggregate={};for(const k of ['ensemble','rf','anfis','lstm','vae','structural'])aggregate[k]=metrics(all.y,all[k]);return {status:folds.length?'OK':'INSUFFICIENT',folds,aggregate}}
function newsModel(news,symbol,name){const neg=['fraud','investigation','lawsuit','penalty','fine','loss','decline','slump','warning','risk','default','violation','probe','downgrade','thua lỗ','giảm mạnh','điều tra','vi phạm','xử phạt','nợ xấu','cảnh báo','rủi ro'];const pos=['growth','profit','record','upgrade','beat','outperform','expansion','tăng trưởng','lợi nhuận','kỷ lục','vượt kế hoạch','mở rộng'];const legal=['investigation','fraud','lawsuit','penalty','violation','probe','điều tra','khởi tố','vi phạm','xử phạt'];const earnings=['profit','revenue','earnings','margin','lợi nhuận','doanh thu','biên lợi nhuận'];const capital=['dividend','bond','share issue','buyback','cổ tức','trái phiếu','phát hành','mua lại'];const seen=new Set(),items=[];for(const h of news||[]){const title=String(h.title||'').replace(/\s+/g,' ').trim(),key=title.toLowerCase().replace(/[^a-z0-9à-ỹ]+/gi,' ');if(!title||seen.has(key))continue;seen.add(key);const low=title.toLowerCase();let s=0;for(const w of neg)if(low.includes(w))s-=1;for(const w of pos)if(low.includes(w))s+=1;if(/not\s+(a\s+)?(loss|decline|risk)|không\s+(bị\s+)?(lỗ|giảm|vi phạm)/i.test(low))s+=1.5;const rel=(low.includes(symbol.toLowerCase())||name&&low.includes(String(name).toLowerCase().split(' ')[0]))?1:.65;let age=10;try{age=Math.max(0,(Date.now()-Date.parse(h.published))/864e5)}catch{}const decay=Math.exp(-age/21),risk=clamp(.5-.22*s)*rel*decay;let event='General';if(legal.some(w=>low.includes(w)))event='Legal / compliance';else if(earnings.some(w=>low.includes(w)))event='Earnings';else if(capital.some(w=>low.includes(w)))event='Capital / corporate action';items.push({...h,event,risk,relevance:rel,ageDays:age})}const score=items.length?100*clamp(items.reduce((a,b)=>a+b.risk,0)/(items.reduce((a,b)=>a+Math.exp(-b.ageDays/21),0)||1)):null;const sources=new Set(items.map(x=>{const m=String(x.title).match(/\s-\s([^\-]+)$/);return m?m[1].trim():'Unknown'}));return {score,items:items.sort((a,b)=>b.risk-a.risk),articleCount:items.length,sourceCount:sources.size}}
async function run(detail,onProgress=()=>{}){const built=makeSamples(detail.history||[],5),samples=built.samples;if(samples.length<150)throw Error(`Research models need at least 150 point-in-time samples; received ${samples.length}.`);onProgress('Training point-in-time research models…');const currentTrain=samples.slice(0,-1),bundle=await trainBundle(currentTrain),current=predictBundle(bundle,samples,samples.length-1);onProgress('Running purged walk-forward validation…');const validation=await walkForward(samples);disposeBundle(bundle);const news=newsModel(detail.news||[],detail.symbol,detail.name),m=detail.modules||{},ctx=[];if(m.market?.available!==false&&Number.isFinite(+m.market?.score))ctx.push([+m.market.score/100,.30]);if(m.macro?.available!==false&&Number.isFinite(+m.macro?.score))ctx.push([+m.macro.score/100,.20]);if(news.score!=null)ctx.push([news.score/100,.25]);if(m.fundamental?.available!==false&&Number.isFinite(+m.fundamental?.score))ctx.push([+m.fundamental.score/100,.25]);const cw=ctx.reduce((a,b)=>a+b[1],0),context=ctx.length?ctx.reduce((a,b)=>a+b[0]*b[1],0)/cw:null;const currentRisk=context==null?current.ensemble:.8*current.ensemble+.2*context;return {current,context,currentRisk,validation,news,data:{sessions:built.rows.length,samples:samples.length,corporateActionSuspects:built.suspect},latest:samples.at(-1)}}
window.VMEWSResearch={run,makeSamples,newsModel};
})();
