(()=>{
'use strict';
const API='/api/stocks2',VALIDATE='/api/validate',NEWS_URL='https://cdn.githubraw.com/NCKHtop1/vmews-risk-analytics/main/data/research-news.json';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=(x,d=1)=>Number.isFinite(+x)?`${(+x*100).toFixed(d)}%`:'—';
const score=x=>Number.isFinite(+x)?Math.round(+x):'—';
const fmt=x=>Number.isFinite(+x)?new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(+x):'—';
let scan=null,detail=null,research=null,baselineValidation=null;
async function api(url,timeout=70000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal}),txt=await r.text();let p;try{p=JSON.parse(txt)}catch{throw Error(`Invalid API response (${r.status})`)}if(!r.ok)throw Error(p.message||p.error||`HTTP ${r.status}`);return p}finally{clearTimeout(t)}}
function setStatus(id,text,kind=''){const e=$(id);if(e){e.textContent=text;e.className=`status ${kind}`}}
function band(s){s=+s||0;return s>=70?['HIGH','red']:s>=55?['ELEVATED','amber']:s>=40?['WATCH','amber']:['NORMAL','green']}
function moduleCard(label,m,note=''){if(!m||m.available===false)return `<article class="metric"><span>${esc(label)}</span><b>UNAVAILABLE</b><small>${esc(m?.reason||m?.note||note||'Excluded from score')}</small></article>`;return `<article class="metric"><span>${esc(label)}</span><b>${score(m.score)}/100</b><small>${esc(note||'Available')}</small></article>`}
function renderMarket(){const m=scan?.market||{},root=$('marketCard');if(!root)return;if(m.available===false){root.innerHTML='<span>VNINDEX regime</span><b>UNAVAILABLE</b><p>VNINDEX data are unavailable. The market module is excluded rather than treated as normal risk.</p>';return}const [b,c]=band(m.score);root.innerHTML=`<span>VNINDEX regime</span><b class="${c}">${b} · ${score(m.score)}/100</b><p>Technical ${score(m.technical)}/100 · 20-session analog event rate ${m.analog20?.rate==null?'N/A':pct(m.analog20.rate)} · model date ${esc(m.date||'—')}</p>`}
function renderScan(){renderMarket();const body=$('radarRows');body.innerHTML='';for(const x of scan?.ranking||[]){const [b,c]=x.color==='GRAY'?['ACTIVE DRAWDOWN','gray']:x.color==='RED'?['HIGH','red']:x.color==='YELLOW'?['ELEVATED','amber']:['NORMAL','green'];const tr=document.createElement('tr');tr.innerHTML=`<td><button class="symbolLink" data-symbol="${esc(x.symbol)}"><b>${esc(x.symbol)}</b><small>${esc(x.name)}</small></button></td><td><span class="pill ${c}">${b}</span></td><td><b>${score(x.score)}</b></td><td>${fmt(x.close)}</td><td>${pct(x.ret5)}</td><td>${x.modules?.technical?.available===false?'N/A':score(x.modules?.technical?.score)}</td><td>${x.modules?.analog?.available===false?'N/A':score(x.modules?.analog?.score)}</td><td>${x.modules?.market?.available===false?'N/A':score(x.modules?.market?.score)}</td><td>${Math.round((x.confidence||0)*100)}%</td><td>${esc((x.reasons||[]).join(' · ')||'Structural screen')}</td>`;body.appendChild(tr)}if(!body.children.length)body.innerHTML='<tr><td colspan="10">No usable securities returned.</td></tr>';$('scanMeta').textContent=`${scan.scanned||0}/${scan.requestedSymbols?.length||0} names · ${new Date(scan.asOf).toLocaleString()}`;document.querySelectorAll('.symbolLink').forEach(b=>b.onclick=()=>{$('symbolInput').value=b.dataset.symbol;runAnalysis()})}
async function loadRadar(){const syms=($('watchlist').value||'FPT,PNJ,VCB,HPG').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean).slice(0,8).join(',');setStatus('radarStatus','Loading current structural screen…','loading');try{scan=await api(`${API}?mode=scan&symbols=${encodeURIComponent(syms)}&t=${Date.now()}`);renderScan();setStatus('radarStatus',`Ready · ${scan.version}`,'ok')}catch(e){setStatus('radarStatus',e.message,'error');$('radarRows').innerHTML=`<tr><td colspan="10">${esc(e.message)}</td></tr>`}}
function renderDetailHeader(){const [b,c]=band(detail.score),root=$('detailHeader');root.innerHTML=`<div><span>CURRENT STRUCTURAL ASSESSMENT</span><h2>${esc(detail.symbol)} · ${esc(detail.name)}</h2><p>Model date ${esc(detail.modelAsOf||'—')} · ${detail.dataQuality?.rows||0} completed sessions · coverage ${Math.round((detail.confidence||0)*100)}%</p></div><div class="scoreBox ${c}"><b>${score(detail.score)}</b><span>${b}</span></div>`}
function renderModules(){const m=detail.modules||{};$('moduleGrid').innerHTML=[moduleCard('Technical',m.technical,'Deterministic price/volume deterioration'),moduleCard('Historical analog',m.analog,m.analog?.rate==null?'No stable analog rate':`20-session event rate ${pct(m.analog.rate)}`),moduleCard('VNINDEX',m.market,m.market?.available===false?'Excluded':'Current market context'),moduleCard('Macro',m.macro,'Current cross-asset context only'),moduleCard('News',m.sentiment,`${m.sentiment?.articleCount||detail.news?.length||0} aggregated headlines`),moduleCard('Fundamentals',m.fundamental,'Current snapshot; excluded from historical ML validation')].join('')}
function renderNews(){const n=research?.news||{items:detail.news||[],articleCount:detail.news?.length||0,sourceCount:0,score:null};$('newsMeta').textContent=`${n.articleCount||0} unique headlines · ${n.sourceCount||0} publishers · headline-level event/NLP risk ${n.score==null?'N/A':score(n.score)+'/100'}`;const root=$('newsList');root.innerHTML='';for(const x of (n.items||[]).slice(0,20)){root.insertAdjacentHTML('beforeend',`<article><div><b>${esc(x.event||'News')}</b><span>risk ${Number.isFinite(+x.risk)?score(+x.risk*100):'—'}</span></div><a href="${esc(x.link||'#')}" target="_blank" rel="noopener noreferrer">${esc(x.title)}</a><small>${esc(x.published||'')}</small></article>`)}if(!root.children.length)root.innerHTML='<div class="empty">No usable news headlines were returned by the current feed.</div>'}
function modelMetric(name,val,sub=''){return `<article class="metric model"><span>${esc(name)}</span><b>${val==null?'UNAVAILABLE':score(val*100)+'/100'}</b><small>${esc(sub)}</small></article>`}
function renderResearch(){const r=research,c=r.current,reg=c.regimeId==null?'N/A':`cluster ${c.regimeId+1}`;$('researchScore').innerHTML=`<div><span>POINT-IN-TIME MODEL ENSEMBLE</span><b>${score(c.ensemble*100)}/100</b><small>Validated historical engine</small></div><div><span>CURRENT CONTEXT OVERLAY</span><b>${r.context==null?'N/A':score(r.context*100)+'/100'}</b><small>VNINDEX + macro + news + fundamentals, available modules only</small></div><div><span>CURRENT RESEARCH RISK</span><b>${score(r.currentRisk*100)}/100</b><small>80% historical model ensemble + 20% current context</small></div>`;$('modelGrid').innerHTML=[modelMetric('Structural EWS',c.structural,'Deterministic benchmark'),modelMetric('Random Forest',c.randomForest,'Bagged nonlinear benchmark'),modelMetric('ANFIS',c.anfis,'Adaptive neuro-fuzzy rules'),modelMetric('Regime model',c.regime,reg),modelMetric('VAE anomaly',c.vae,'Latent reconstruction anomaly'),modelMetric('LSTM crash',c.lstmCrash,'20-session crash classifier'),modelMetric('LSTM rebound',c.lstmRebound,'20-session rebound classifier')].join('');$('dataAudit').innerHTML=`<span>Price sessions <b>${r.data.sessions}</b></span><span>Point-in-time samples <b>${r.data.samples}</b></span><span>Corporate-action suspects <b>${r.data.corporateActionSuspects.length}</b></span><span>News headlines <b>${r.news.articleCount||0}</b></span><span>Publishers <b>${r.news.sourceCount||0}</b></span>`;renderNews();renderWalkForward()}
function mcell(k,m){if(!m)return '<td>N/A</td>';return `<td>${m.auc==null?'—':m.auc.toFixed(2)}</td><td>${m.precision==null?'—':pct(m.precision)}</td><td>${m.recall==null?'—':pct(m.recall)}</td><td>${m.fpr==null?'—':pct(m.fpr)}</td>`}
function renderWalkForward(){const v=research.validation,body=$('validationRows');body.innerHTML='';if(v.status!=='OK'){body.innerHTML='<tr><td colspan="6">Insufficient point-in-time samples for walk-forward validation.</td></tr>';return}const names={ensemble:'Ensemble',structural:'Structural EWS',rf:'Random Forest',anfis:'ANFIS',vae:'VAE anomaly',lstm:'LSTM crash'};for(const k of Object.keys(names)){const m=v.aggregate[k];const tr=document.createElement('tr');tr.innerHTML=`<td>${names[k]}</td>${mcell(k,m)}<td>${v.folds.length}</td>`;body.appendChild(tr)}$('foldMeta').textContent=v.folds.map((f,i)=>`Fold ${i+1}: ${f.from} → ${f.to}, n=${f.n}, events=${f.events}`).join(' · ')}
function renderBaselineValidation(){const v=baselineValidation,root=$('baselineValidation');if(!v){root.innerHTML='';return}if(v.status!=='OK'){root.innerHTML=`<b>Structural holdout: ${esc(v.status)}</b><span>${esc(v.reason||'')}</span>`;return}const m=v.holdout?.metrics||{};root.innerHTML=`<b>Server structural holdout · ${esc(v.verdict)}</b><span>Precision ${m.precision==null?'—':pct(m.precision)} · Recall ${m.recall==null?'—':pct(m.recall)} · F1 ${m.f1==null?'—':pct(m.f1)} · FPR ${m.falsePositiveRate==null?'—':pct(m.falsePositiveRate)} · AUC ${m.auc==null?'—':(+m.auc).toFixed(2)}</span>`}
async function runAnalysis(){const symbol=($('symbolInput').value||'FPT').trim().toUpperCase();setStatus('analysisStatus','Loading point-in-time history…','loading');$('analysisPanel').hidden=false;$('researchBlock').hidden=true;try{let newsSnapshot=null;[detail,baselineValidation,newsSnapshot]=await Promise.all([api(`${API}?mode=detail&symbol=${encodeURIComponent(symbol)}&t=${Date.now()}`,80000),api(`${VALIDATE}?symbol=${encodeURIComponent(symbol)}&t=${Date.now()}`,80000).catch(()=>null),fetch(`${NEWS_URL}?t=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)]);const extra=newsSnapshot?.symbols?.[symbol]||[];if(extra.length){const all=[...(detail.news||[]),...extra],seen=new Set();detail.news=all.filter(x=>{const k=String(x.title||'').toLowerCase().replace(/[^a-z0-9à-ỹ]+/gi,' ').trim();if(!k||seen.has(k))return false;seen.add(k);return true}).slice(0,100);detail.newsSnapshotGeneratedAt=newsSnapshot.generatedAt||null}renderDetailHeader();renderModules();renderBaselineValidation();setStatus('analysisStatus','Training research models in the browser…','loading');research=await window.VMEWSResearch.run(detail,msg=>setStatus('analysisStatus',msg,'loading'));renderResearch();$('researchBlock').hidden=false;setStatus('analysisStatus','Research analysis complete','ok')}catch(e){setStatus('analysisStatus',e.message,'error')}}
function bind(){$('refreshBtn').onclick=loadRadar;$('analyzeBtn').onclick=runAnalysis;$('fptBtn').onclick=()=>{$('symbolInput').value='FPT';runAnalysis()};$('pnjBtn').onclick=()=>{$('symbolInput').value='PNJ';runAnalysis()}}
async function init(){bind();setStatus('radarStatus','Warming data source…','loading');try{await api(`${API}?mode=scan&symbols=FPT,PNJ,VCB,HPG&t=${Date.now()}`,45000)}catch{}await loadRadar()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
