(()=>{
const API='/api/stocks2';
const $=id=>document.getElementById(id), F=new Intl.NumberFormat('en-US',{maximumFractionDigits:2});
const pct=(x,d=1)=>Number.isFinite(Number(x))?`${(Number(x)*100).toFixed(d)}%`:'—';
const n=(x,d=0)=>Number.isFinite(Number(x))?Number(x).toFixed(d):'—';
let scan=null,detail=null;
const modLabels={technical:'Technical',analog:'Historical analog',market:'VNINDEX regime',macro:'Macro / cross-asset',sentiment:'News sentiment',fundamental:'Fundamentals'};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(url){const r=await fetch(url,{cache:'no-store'}),t=await r.text();let p;try{p=JSON.parse(t)}catch{throw Error(`Invalid API response (${r.status})`)}if(!r.ok)throw Error(p.message||p.error||`HTTP ${r.status}`);return p}
function setStatus(msg,kind=''){const e=$('radarStatus');if(e){e.textContent=msg;e.className=`radar-status ${kind}`}}
function colorChip(x){const c=String(x.color||'GREEN').toLowerCase();return `<span class="radar-state ${c}">${esc(x.color||'GREEN')} ${Math.round(x.effectiveScore??x.score??0)}</span>`}
function listChips(id,items){const e=$(id);if(!e)return;e.innerHTML=items?.length?items.map(x=>`<button class="watch-chip ${String(x.color||'').toLowerCase()}" data-symbol="${x.symbol}"><b>${x.symbol}</b><span>${Math.round(x.effectiveScore??x.score??0)}</span></button>`).join(''):'<span class="radar-empty">None</span>'}
function moduleScore(item,k){const m=item.modules?.[k];return m?.available===false?'N/A':Math.round(m?.score??0)}
function renderScan(){
 if(!scan)return;
 $('radarAsOf').textContent=`${scan.scanned}/${scan.requestedSymbols?.length||0} requested · ${new Date(scan.asOf).toLocaleString()}`;
 listChips('redList',scan.redList||[]);listChips('yellowList',scan.yellowList||[]);listChips('greenList',scan.greenList||[]);listChips('activeDrawdown',scan.activeDrawdown||[]);
 const body=$('radarRows');body.innerHTML='';
 for(const x of scan.ranking||[]){
   const live=x.quote?.last, display=Number.isFinite(Number(live))?`${F.format(x.close)} → ${F.format(live)}`:F.format(x.close);
   const tr=document.createElement('tr');tr.innerHTML=`<td><button class="symbol-btn" data-symbol="${x.symbol}"><b>${x.symbol}</b><small>${esc(x.name)}</small></button></td><td>${colorChip(x)}<small>${esc(x.phase)}</small></td><td>${Math.round(x.effectiveScore??x.score)}</td><td>${display}</td><td class="${x.ret5<0?'neg':'pos'}">${pct(x.ret5)}</td><td>${moduleScore(x,'technical')}</td><td>${moduleScore(x,'analog')}</td><td>${moduleScore(x,'sentiment')}</td><td>${moduleScore(x,'fundamental')}</td><td>${Math.round((x.confidence||0)*100)}%</td><td class="radar-reason">${esc((x.reasons||[]).join(' · '))}</td>`;body.appendChild(tr)
 }
 const m=scan.macro?.factors||{};$('macroTape').innerHTML=Object.entries(m).map(([k,v])=>`<div><span>${esc(k)}</span><b>${F.format(v.last)}</b><small>20D ${pct(v.ret20)}</small></div>`).join('');
}
async function loadScan(){
 const symbols=($('scanSymbols')?.value||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean).slice(0,8).join(',');
 setStatus('Requesting current watchlist data from Vnstock…','loading');$('radarRefresh').disabled=true;
 try{scan=await api(`${API}?mode=scan&symbols=${encodeURIComponent(symbols)}&t=${Date.now()}`);renderScan();setStatus(`Watchlist ready · ${scan.version}`,'ok')}catch(e){setStatus(e.message,'error')}finally{$('radarRefresh').disabled=false}
}
function renderModules(){const root=$('detailModules');root.innerHTML='';for(const k of ['technical','analog','market','macro','sentiment','fundamental']){const m=detail.modules?.[k]||{};const score=m.available===false?null:Number(m.score);root.insertAdjacentHTML('beforeend',`<article class="module-card ${score!=null&&score>=70?'hot':score!=null&&score>=55?'warm':''}"><div><span>${modLabels[k]}</span><button class="radar-info" data-radar-info="${k}">i</button></div><strong>${score==null?'N/A':Math.round(score)}</strong><small>${m.available===false?esc(m.reason||m.note||'Unavailable / excluded'): 'Risk evidence module'}</small></article>`)} }
function renderDetailChart(){const c=$('stockDetailChart');if(!c||!detail)return;const rows=detail.history||[],scores=new Map((detail.scoreHistory||[]).map(x=>[x.date,x.technical]));const r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(500,Math.floor(r.width||760)),h=330;c.width=w*d;c.height=h*d;const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);if(rows.length<2)return;const p={l:12,r:52,t:15,b:28},vals=rows.map(x=>x.close),mi=Math.min(...vals),ma=Math.max(...vals),rg=ma-mi||1,X=i=>p.l+(w-p.l-p.r)*i/(rows.length-1),Y=v=>p.t+(h-p.t-p.b)*(1-(v-mi)/rg),YS=s=>p.t+(h-p.t-p.b)*(1-s/100);ctx.strokeStyle='#163149';ctx.fillStyle='#70869b';ctx.font='10px monospace';for(let j=0;j<=4;j++){let y=p.t+(h-p.t-p.b)*j/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillText(Math.round(ma-rg*j/4),w-p.r+5,y+3)}ctx.beginPath();rows.forEach((x,i)=>i?ctx.lineTo(X(i),Y(x.close)):ctx.moveTo(X(i),Y(x.close)));ctx.strokeStyle='#48d9ff';ctx.lineWidth=1.7;ctx.stroke();ctx.beginPath();let st=false;rows.forEach((x,i)=>{const s=scores.get(x.date);if(!Number.isFinite(s))return;st?ctx.lineTo(X(i),YS(s)):ctx.moveTo(X(i),YS(s));st=true});ctx.strokeStyle='#ffc95d';ctx.lineWidth=1.4;ctx.stroke();}
function renderReplay(){const root=$('crashReplay');root.innerHTML='';const ev=detail.crashReplay||[];if(!ev.length){root.innerHTML='<div class="radar-empty">No qualifying historical drawdown episode in the available point-in-time replay window.</div>';return}for(const e of ev.slice(0,5)){root.insertAdjacentHTML('beforeend',`<article class="replay-card"><header><div><b>${e.signalDate}</b><span>20D realized drawdown ${pct(e.forwardDrawdown20)}</span></div><button class="replay-use" data-asof="${e.signalDate}">Run as-of this date</button></header><div class="replay-steps">${(e.preSignals||[]).map(s=>`<div><small>T-${s.lead}</small><b>${s.date}</b><span>Technical ${Math.round(s.technical)}</span><em>${F.format(s.close)}</em></div>`).join('')}</div></article>`)} }
function renderNews(){const root=$('stockNews');root.innerHTML='';const news=detail.news||[];if(!news.length){root.innerHTML='<div class="radar-empty">No usable headlines returned in the selected sentiment window.</div>';return}for(const x of news){root.insertAdjacentHTML('beforeend',`<a class="news-row" href="${esc(x.link)}" target="_blank" rel="noopener"><span class="sent-dot ${x.sentiment<0?'neg-bg':x.sentiment>0?'pos-bg':''}"></span><div><b>${esc(x.title)}</b><small>${esc(x.published)}</small></div></a>`)} }
function renderFund(){const v=detail.fundamentals||{},root=$('fundMetrics');root.innerHTML=Object.entries(v).map(([k,x])=>`<div><span>${esc(k)}</span><b>${x==null?'—':n(x,2)}</b></div>`).join('')||'<div class="radar-empty">Point-in-time fundamental fields unavailable.</div>'}
function renderAudit(){const root=$('detailAudit'),q=detail.dataQuality||{},req=detail.request||{},src=detail.source||{};root.innerHTML=`<div><b>Request</b><span>${req.from} → ${req.to}${req.asOf?' · as-of '+req.asOf:''}</span></div><div><b>Vnstock rows</b><span>${q.rows||0} · coverage ${(Number(q.coverageRatio||0)*100).toFixed(1)}% · ${q.status}</span></div><div><b>Price</b><span>${esc(src.price||'—')}</span></div><div><b>Fundamental</b><span>${esc(src.fundamental||'—')}</span></div><div><b>News</b><span>${esc(src.sentiment||'—')}</span></div><div><b>Macro</b><span>${esc(src.macro||'—')}</span></div>`}
function renderDetail(){
 $('detailPanel').hidden=false;$('detailTitle').textContent=`${detail.symbol} · ${detail.name}`;$('detailMeta').textContent=`Request ${detail.request.from} → ${detail.request.to}${detail.request.asOf?' · as-of '+detail.request.asOf:''} · model ${detail.modelAsOf} · confidence ${Math.round(detail.confidence*100)}%`;$('detailState').innerHTML=colorChip(detail);$('detailReasons').textContent=(detail.reasons||[]).join(' · ');
 const c=detail.current||{},o=detail.liveOverlay||{};$('detailSnapshot').innerHTML=`<div><span>EOD close</span><b>${F.format(c.close)}</b></div><div><span>Live quote</span><b>${o.available?F.format(o.last):'—'}</b></div><div><span>Intraday</span><b class="${o.intradayReturn<0?'neg':'pos'}">${o.available?pct(o.intradayReturn):'—'}</b></div><div><span>20D momentum</span><b class="${c.mom20<0?'neg':'pos'}">${pct(c.mom20)}</b></div><div><span>60D drawdown</span><b class="neg">${pct(c.dd60)}</b></div><div><span>RSI 14</span><b>${n(c.rsi14,1)}</b></div>`;
 const hz=$('stockHorizons');hz.innerHTML='';for(const [k,x] of Object.entries(detail.horizons||{})){hz.insertAdjacentHTML('beforeend',`<div><span>${k}D analog tail stress</span><b>${x.rate==null?'N/A':pct(x.rate)}</b><small>threshold ${pct(x.threshold)} · ${x.matches} matches</small></div>`)}
 renderModules();renderReplay();renderNews();renderFund();renderAudit();requestAnimationFrame(renderDetailChart);$('detailPanel').scrollIntoView({behavior:'smooth',block:'start'})
}
async function loadDetail(symbol,asof=null){
 symbol=(symbol||$('symbolInput').value||'FPT').toUpperCase().trim();$('symbolInput').value=symbol;const start=$('fromDate').value,end=$('toDate').value,a=asof||$('asOfDate').value;
 setStatus(`Requesting ${symbol} data and running EWS…`,'loading');let u=`${API}?mode=detail&symbol=${encodeURIComponent(symbol)}`;if(a)u+=`&asof=${a}`;if(start)u+=`&from=${start}`;if(end)u+=`&to=${end}`;u+=`&t=${Date.now()}`;
 try{detail=await api(u);renderDetail();setStatus(`${symbol} ready · ${detail.color} ${Math.round(detail.effectiveScore)}`,'ok')}catch(e){setStatus(e.message,'error')}
}
const info={request:'The backend fetches Vnstock data only for the user-selected stock and date window, plus a warm-up period needed for MA200 and historical analogs. Every refresh is a new request; the response includes source audit and data-quality coverage.',technical:'Price/volume layer from Vnstock OHLCV: drawdown, momentum, MA50/MA200, volatility regime, RSI, MACD and volume-confirmed selling.',analog:'Point-in-time nearest-neighbor states. Candidate analogs and their forward outcomes must be fully observable before the requested model as-of date.',market:'VNINDEX regime requested from Vnstock for the same point-in-time model context.',macro:'Cross-asset context (VIX, USD/VND, DXY, US10Y, Brent). These are background stress variables and do not prove causality.',sentiment:'Headline-based financial-news sentiment inside the requested time window. This is not analyst consensus and is excluded when no usable headlines are returned.',fundamental:'Vnstock financial ratios. For historical requests, fundamentals are excluded unless reliable dated point-in-time data are available, preventing look-ahead bias.'};
function showInfo(k){$('radarInfoTitle').textContent=modLabels[k]||'Request-driven EWS';$('radarInfoBody').textContent=info[k]||info.request;$('radarInfoDialog').showModal()}
function setDefaultDates(){const today=new Date(),to=today.toISOString().slice(0,10),from=new Date(today);from.setFullYear(from.getFullYear()-3);if(!$('toDate').value)$('toDate').value=to;if(!$('fromDate').value)$('fromDate').value=from.toISOString().slice(0,10)}
document.addEventListener('DOMContentLoaded',()=>{setDefaultDates();$('radarRefresh')?.addEventListener('click',loadScan);$('runStockBtn')?.addEventListener('click',()=>loadDetail());$('fptReplay')?.addEventListener('click',()=>loadDetail('FPT'));$('pnjReplay')?.addEventListener('click',()=>loadDetail('PNJ'));document.addEventListener('click',e=>{const s=e.target.closest('[data-symbol]');if(s)loadDetail(s.dataset.symbol);const r=e.target.closest('[data-asof]');if(r)loadDetail(detail?.symbol,r.dataset.asof);const i=e.target.closest('[data-radar-info]');if(i)showInfo(i.dataset.radarInfo)});window.addEventListener('resize',()=>detail&&renderDetailChart());loadScan();});
})();
