(()=>{
const $=id=>document.getElementById(id), F=new Intl.NumberFormat('en-US',{maximumFractionDigits:2});
const pct=(x,d=1)=>Number.isFinite(Number(x))?`${(Number(x)*100).toFixed(d)}%`:'—';
const n=(x,d=0)=>Number.isFinite(Number(x))?Number(x).toFixed(d):'—';
let scan=null,detail=null;
const modLabels={technical:'Technical',analog:'Historical analog',market:'Market regime',macro:'Macro / cross-asset',sentiment:'News sentiment',fundamental:'Fundamentals'};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(url){const r=await fetch(url,{cache:'no-store'}),t=await r.text();let p;try{p=JSON.parse(t)}catch{throw Error(`Invalid API response (${r.status})`)}if(!r.ok)throw Error(p.message||p.error||`HTTP ${r.status}`);return p}
function stateChip(s,score){return `<span class="radar-state ${String(s).toLowerCase()}">${esc(s)} ${Math.round(score||0)}</span>`}
function setStatus(msg,kind=''){const e=$('radarStatus');if(e){e.textContent=msg;e.className=`radar-status ${kind}`}}
function listChips(id,items){const e=$(id);if(!e)return;e.innerHTML=items.length?items.map(x=>`<button class="watch-chip ${x.state.toLowerCase()}" data-symbol="${x.symbol}"><b>${x.symbol}</b><span>${Math.round(x.score)}</span></button>`).join(''):'<span class="radar-empty">None in the enriched coverage set.</span>'}
function moduleScore(item,k){const m=item.modules?.[k];return m?.available===false?'N/A':Math.round(m?.score??0)}
function renderScan(){
  if(!scan)return; $('radarAsOf').textContent=`Scan ${new Date(scan.asOf).toLocaleString()} · ${scan.scanned}/${scan.universeSize} symbols`;
  listChips('redList',scan.redList||[]);listChips('goldList',scan.goldList||[]);
  const body=$('radarRows');body.innerHTML='';
  for(const x of scan.ranking||[]){
    const tr=document.createElement('tr');tr.dataset.symbol=x.symbol;tr.innerHTML=`<td><button class="symbol-btn" data-symbol="${x.symbol}"><b>${x.symbol}</b><small>${esc(x.name)}</small></button></td><td>${stateChip(x.state,x.score)}</td><td>${F.format(x.close)}</td><td class="${x.ret5<0?'neg':'pos'}">${pct(x.ret5)}</td><td>${moduleScore(x,'technical')}</td><td>${moduleScore(x,'analog')}</td><td>${moduleScore(x,'sentiment')}</td><td>${moduleScore(x,'fundamental')}</td><td>${Math.round((x.confidence||0)*100)}%</td><td class="radar-reason">${esc((x.reasons||[]).join(' · ')||'Price/market pre-screen')}</td>`;body.appendChild(tr)
  }
  const m=scan.macro?.factors||{};$('macroTape').innerHTML=Object.entries(m).map(([k,v])=>`<div><span>${esc(k)}</span><b>${F.format(v.last)}</b><small>20D ${pct(v.ret20)}</small></div>`).join('');
}
async function loadScan(){setStatus('Running stock-level EWS across the coverage universe…','loading');$('radarRefresh').disabled=true;try{scan=await api(`/api/stocks?mode=scan&limit=22&t=${Date.now()}`);renderScan();setStatus(`Ready · ${scan.version}`,'ok')}catch(e){setStatus(e.message,'error')}finally{$('radarRefresh').disabled=false}}
function renderModules(){const root=$('detailModules');root.innerHTML='';for(const k of ['technical','analog','market','macro','sentiment','fundamental']){const m=detail.modules?.[k]||{};const score=m.available===false?null:Number(m.score);root.insertAdjacentHTML('beforeend',`<article class="module-card ${score!=null&&score>=70?'hot':score!=null&&score>=55?'warm':''}"><div><span>${modLabels[k]}</span><button class="radar-info" data-radar-info="${k}">i</button></div><strong>${score==null?'N/A':Math.round(score)}</strong><small>${m.available===false?'Source unavailable / excluded from weighted score':'Risk contribution module'}</small></article>`)} }
function renderDetailChart(){const c=$('stockDetailChart');if(!c||!detail)return;const rows=detail.history||[],scores=new Map((detail.scoreHistory||[]).map(x=>[x.date,x.technical]));const r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(500,Math.floor(r.width)),h=330;c.width=w*d;c.height=h*d;const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);if(rows.length<2)return;const p={l:12,r:52,t:15,b:28},vals=rows.map(x=>x.close),mi=Math.min(...vals),ma=Math.max(...vals),rg=ma-mi||1,X=i=>p.l+(w-p.l-p.r)*i/(rows.length-1),Y=v=>p.t+(h-p.t-p.b)*(1-(v-mi)/rg),YS=s=>p.t+(h-p.t-p.b)*(1-s/100);ctx.strokeStyle='#163149';ctx.fillStyle='#70869b';ctx.font='10px monospace';for(let j=0;j<=4;j++){let y=p.t+(h-p.t-p.b)*j/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillText(Math.round(ma-rg*j/4),w-p.r+5,y+3)}ctx.beginPath();rows.forEach((x,i)=>i?ctx.lineTo(X(i),Y(x.close)):ctx.moveTo(X(i),Y(x.close)));ctx.strokeStyle='#48d9ff';ctx.lineWidth=1.7;ctx.stroke();ctx.beginPath();let st=false;rows.forEach((x,i)=>{const s=scores.get(x.date);if(!Number.isFinite(s))return;st?ctx.lineTo(X(i),YS(s)):ctx.moveTo(X(i),YS(s));st=true});ctx.strokeStyle='#ffc95d';ctx.lineWidth=1.4;ctx.stroke();}
function renderReplay(){const root=$('crashReplay');root.innerHTML='';const ev=detail.crashReplay||[];if(!ev.length){root.innerHTML='<div class="radar-empty">No ≥12% 20-session historical drawdown episode in the available replay window.</div>';return}for(const e of ev.slice(0,5)){root.insertAdjacentHTML('beforeend',`<article class="replay-card"><header><div><b>${e.signalDate}</b><span>20D realized drawdown ${pct(e.forwardDrawdown20)}</span></div><button class="replay-use" data-asof="${e.signalDate}">Replay this date</button></header><div class="replay-steps">${(e.preSignals||[]).map(s=>`<div><small>T-${s.lead}</small><b>${s.date}</b><span>Technical ${Math.round(s.technical)}</span><em>${F.format(s.close)}</em></div>`).join('')}</div></article>`)} }
function renderNews(){const root=$('stockNews');root.innerHTML='';const news=detail.news||[];if(!news.length){root.innerHTML='<div class="radar-empty">No usable headlines returned for this request window.</div>';return}for(const x of news){root.insertAdjacentHTML('beforeend',`<a class="news-row" href="${esc(x.link)}" target="_blank" rel="noopener"><span class="sent-dot ${x.sentiment<0?'neg-bg':x.sentiment>0?'pos-bg':''}"></span><div><b>${esc(x.title)}</b><small>${esc(x.published)}</small></div></a>`)} }
function renderFund(){const m=detail.modules?.fundamental||{},root=$('fundMetrics');const v=m.metrics||{};root.innerHTML=Object.entries(v).map(([k,x])=>`<div><span>${esc(k)}</span><b>${x==null?'—':n(x,2)}</b></div>`).join('')||'<div class="radar-empty">Fundamental fields unavailable.</div>'}
function renderDetail(){
  $('detailPanel').hidden=false;$('detailTitle').textContent=`${detail.symbol} · ${detail.name}`;$('detailMeta').textContent=`Model as-of ${detail.modelAsOf} · confidence ${Math.round(detail.confidence*100)}% · ${detail.version}`;$('detailState').innerHTML=stateChip(detail.state,detail.score);$('detailReasons').textContent=(detail.reasons||[]).join(' · ');
  const c=detail.current||{};$('detailSnapshot').innerHTML=`<div><span>Close</span><b>${F.format(c.close)}</b></div><div><span>20D momentum</span><b class="${c.mom20<0?'neg':'pos'}">${pct(c.mom20)}</b></div><div><span>60D drawdown</span><b class="neg">${pct(c.dd60)}</b></div><div><span>20D vol</span><b>${pct(c.vol20)}</b></div><div><span>RSI 14</span><b>${n(c.rsi14,1)}</b></div><div><span>vs MA50</span><b class="${c.trend50<0?'neg':'pos'}">${pct(c.trend50)}</b></div>`;
  const hz=$('stockHorizons');hz.innerHTML='';for(const [k,x] of Object.entries(detail.horizons||{})){hz.insertAdjacentHTML('beforeend',`<div><span>${k}D analog stress</span><b>${x.rate==null?'N/A':pct(x.rate)}</b><small>tail ${pct(x.threshold)} · ${x.matches} matches</small></div>`)}
  renderModules();renderReplay();renderNews();renderFund();requestAnimationFrame(renderDetailChart);$('detailPanel').scrollIntoView({behavior:'smooth',block:'start'})
}
async function loadDetail(symbol,asof=null){symbol=(symbol||$('symbolInput').value||'FPT').toUpperCase().trim();$('symbolInput').value=symbol;const start=$('fromDate').value,end=$('toDate').value;const a=asof||$('asOfDate').value;setStatus(`Running ${symbol} model${a?' as of '+a:''}…`,'loading');let u=`/api/stocks?mode=detail&symbol=${encodeURIComponent(symbol)}`;if(a)u+=`&asof=${a}`;if(start)u+=`&from=${start}`;if(end)u+=`&to=${end}`;u+=`&t=${Date.now()}`;try{detail=await api(u);renderDetail();setStatus(`${symbol} ready · model as-of ${detail.modelAsOf}`,'ok')}catch(e){setStatus(e.message,'error')}}
const info={technical:'Price/volume warning layer: drawdown, 20D momentum, MA50/MA200 breaks, volatility regime, RSI weakness, MACD weakness and volume-confirmed selloff.',analog:'Stock-specific historical analog layer. It searches older states with similar technical structure and measures how often the next 5/20/60 sessions entered the stock’s severe drawdown tail.',market:'Broad VNINDEX regime. A stock warning is more credible when market-level stress is also elevated.',macro:'Fast cross-asset context: VIX, USD/VND, DXY, US 10Y yield and Brent. These variables do not prove causality; they increase or reduce background stress.',sentiment:'Recent finance-news headlines are scored with a transparent Vietnamese/English risk lexicon. The module is excluded if no usable headlines are returned.',fundamental:'Vnstock financial ratios/statements when available. Weak profitability, high leverage, expensive valuation or negative growth can raise structural fragility. Missing fields are excluded rather than invented.'};
function showInfo(k){$('radarInfoTitle').textContent=modLabels[k]||k;$('radarInfoBody').textContent=info[k]||'';$('radarInfoDialog').showModal()}
document.addEventListener('DOMContentLoaded',()=>{
  $('radarRefresh')?.addEventListener('click',loadScan);$('runStockBtn')?.addEventListener('click',()=>loadDetail());$('fptReplay')?.addEventListener('click',()=>loadDetail('FPT'));$('pnjReplay')?.addEventListener('click',()=>loadDetail('PNJ'));
  document.addEventListener('click',e=>{const s=e.target.closest('[data-symbol]');if(s)loadDetail(s.dataset.symbol);const r=e.target.closest('[data-asof]');if(r)loadDetail(detail?.symbol,r.dataset.asof);const i=e.target.closest('[data-radar-info]');if(i)showInfo(i.dataset.radarInfo)});
  window.addEventListener('resize',()=>detail&&renderDetailChart());loadScan();
});
})();
