(function(){'use strict';
const $=id=>document.getElementById(id);
const DATA_BASE=new URL(document.currentScript.dataset.base||'../data/',document.currentScript.src||location.href).href;
const BOOT=JSON.parse(document.getElementById('financial-bootstrap')?.textContent||'{}');
const LIVE_BASE='https://raw.githubusercontent.com/NCKHtop1/vmews-risk-analytics/financial-report-data/data/';
const state={data:null,companies:[],catalog:[],years:[],reports:[],active:'balance_sheet',loading:false,controller:null,base:DATA_BASE};
const names={balance_sheet:'Cân đối kế toán',income_statement:'Kết quả kinh doanh',cash_flow:'Lưu chuyển tiền tệ',ratios:'Chỉ số tài chính',notes:'Thuyết minh',off_balance:'Ngoại bảng'};
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const nf=new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2});
const fmt=v=>v==null?'':v===0?'–':v<0?`(${nf.format(-v)})`:nf.format(v);
async function json(url,signal,timeout=20000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);const abort=()=>ctl.abort();signal?.addEventListener('abort',abort,{once:true});try{const r=await fetch(url,{signal:ctl.signal,cache:'no-cache'});if(!r.ok)throw Error('Dữ liệu tạm thời chưa tải được. Vui lòng thử lại.');return await r.json();}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}}
function error(message){$('error').hidden=!message;$('error').textContent=message||'';}
function reportYears(s){return Array.from(new Set(s.rows.flatMap(r=>Object.keys(r.values).filter(y=>Number.isFinite(r.values[y])).map(Number)))).sort((a,b)=>a-b);}
function eligible(){if(!state.data||!state.reports.length)return[];const ss=state.data.sections.filter(s=>state.reports.includes(s.id));return ss.length?ss.map(s=>s.years).reduce((a,b)=>a.filter(y=>b.includes(y))):[];}
function checkData(d,symbol){if(d.symbol!==symbol||!Array.isArray(d.sections)||!d.sections.length)throw Error('Không tìm thấy báo cáo phù hợp.');for(const s of d.sections){if(!Array.isArray(s.rows)||!s.rows.length)throw Error('Báo cáo chưa có chỉ tiêu.');for(const r of s.rows){if(s.id!=='ratios'&&r.unit==='triệu đồng'&&['outstanding_shares_volume','treasury_stocks_volume','foreign_currencies'].includes(r.id)){r.unit=r.id==='foreign_currencies'?'nguyên tệ':'cổ phiếu';r.values=Object.fromEntries(Object.entries(r.values).map(([y,v])=>[y,v==null?null:Math.round(v*1000000)]));}if(!r.label||!r.values||Object.entries(r.values).some(([y,v])=>!/^\d{4}$/.test(y)||(v!==null&&!Number.isFinite(v))))throw Error('Dữ liệu chưa qua kiểm tra định dạng.');}s.years=reportYears(s);}return d;}
function renderYears(){const available=eligible(),all=Array.from(new Set(state.data?.sections.flatMap(s=>s.years)||[])).sort((a,b)=>a-b);state.years=state.years.filter(y=>available.includes(y));$('year-options').innerHTML=all.map(y=>`<label class="year-option"><input type="checkbox" value="${y}" ${state.years.includes(y)?'checked':''} ${!available.includes(y)?'disabled':''} aria-label="Năm ${y}"><span>${y}</span></label>`).join('');const consecutive=available.every((y,i)=>i===0||y===available[i-1]+1);$('availability').textContent=available.length?`${state.data.symbol}: chọn ${consecutive&&available.length>1?`từ ${available[0]} đến ${available.at(-1)}`:available.join(', ')} cho nội dung đã chọn.`:'Chưa có năm phù hợp với nội dung đã chọn.';}
function renderReports(){if(!state.data)return;$('report-options').innerHTML=state.data.sections.map(s=>`<div class="report-option"><input type="checkbox" id="report-${esc(s.id)}" value="${esc(s.id)}" ${state.reports.includes(s.id)?'checked':''}><label for="report-${esc(s.id)}">${esc(names[s.id]||s.name)}</label><small>${s.rows.filter(r=>Object.values(r.values).some(v=>v!==null)).length}</small></div>`).join('');}
function renderPreview(){const data=state.data;const reports=data?.sections.filter(s=>state.reports.includes(s.id))||[];if(!reports.some(s=>s.id===state.active))state.active=reports[0]?.id||'';$('report-tabs').innerHTML=reports.map(s=>`<button type="button" role="tab" id="tab-${esc(s.id)}" aria-selected="${state.active===s.id}" data-report="${esc(s.id)}">${esc(names[s.id]||s.name)}</button>`).join('');const section=reports.find(s=>s.id===state.active);$('unit-caption').textContent=section?.id==='ratios'?'Đơn vị theo chỉ tiêu':'Triệu đồng';
if(!section||!state.years.length){$('table-container').innerHTML='<div class="empty-state"><h3>Chọn năm và nội dung báo cáo</h3><p>Bảng số liệu sẽ hiển thị theo lựa chọn của bạn.</p></div>';}else{$('table-container').innerHTML=`<table aria-label="${esc(section.name)}"><thead><tr><th scope="col">CHỈ TIÊU</th>${state.years.map(y=>`<th scope="col">${y}</th>`).join('')}</tr></thead><tbody>${section.rows.map(r=>`<tr class="${r.bold?'bold':''}"><td>${esc(r.label)}${r.unit&&r.unit!=='triệu đồng'&&!r.label.toLowerCase().includes(r.unit.toLowerCase())?` <span class="muted">(${esc(r.unit)})</span>`:''}</td>${state.years.map(y=>`<td>${fmt(r.values[String(y)])}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
const count=section?.rows.filter(r=>state.years.some(y=>r.values[String(y)]!==null&&r.values[String(y)]!==undefined)).length||0;$('row-count').textContent=`${count} chỉ tiêu · ${state.years.length} năm`;$('summary').textContent=`${reports.length} báo cáo · ${state.years.length} năm`;$('download').disabled=state.loading||!reports.length||!state.years.length;}
function update(){renderYears();renderPreview();$('download-status').textContent='Chỉ tiêu theo hàng · Năm theo cột';}
async function loadCompany(raw){const match=state.companies.find(c=>c.symbol===raw.trim().toUpperCase()||c.name.toLowerCase()===raw.trim().toLowerCase());const symbol=match?.symbol||raw.trim().split(/[\s—–]/)[0].toUpperCase();if(!/^[A-Z][A-Z0-9]{1,7}$/.test(symbol)){error('Nhập mã chứng khoán hợp lệ, ví dụ MBB, FPT hoặc VCB.');return;}
state.controller?.abort();const ctl=new AbortController();state.controller=ctl;state.loading=true;state.data=null;state.years=[];state.reports=[];$('ticker').value=symbol;error('');$('download').disabled=true;$('data-state').className='status-badge';$('data-state').textContent='Đang tải';$('availability').textContent='Đang kiểm tra năm có dữ liệu…';$('report-options').replaceChildren();$('year-options').replaceChildren();$('report-tabs').replaceChildren();$('preview-title').innerHTML=`${esc(symbol)} <span>/ Báo cáo tài chính</span>`;$('company-name').textContent=match?.name||symbol;$('table-container').innerHTML='<div class="empty-state"><span class="loading-ring"></span><h3>Đang chuẩn bị báo cáo</h3><p>Đang tải và kiểm tra dữ liệu…</p></div>';
try{let d;try{d=await json(state.base+symbol+'.json',ctl.signal,BOOT.datasets?.[symbol]?4000:15000);}catch(e){if(ctl.signal.aborted)throw e;if(BOOT.datasets?.[symbol])d=structuredClone(BOOT.datasets[symbol]);else if(state.base!==DATA_BASE)d=await json(DATA_BASE+symbol+'.json',ctl.signal);else throw e;}if(ctl.signal.aborted)return;state.data=checkData(d,symbol);state.reports=d.sections.filter(s=>s.id!=='ratios'&&s.id!=='notes').map(s=>s.id);state.years=eligible().slice(-6);state.active='balance_sheet';$('company-name').textContent=d.name||match?.name||symbol;$('company-description').textContent=[d.exchange||match?.exchange,d.name||match?.name].filter(Boolean).join(' · ');$('data-state').textContent='Có dữ liệu';$('data-state').className='status-badge ready';$('updated-at').textContent='Cập nhật '+new Date(d.updatedAt).toLocaleDateString('vi-VN');document.querySelectorAll('[data-symbol]').forEach(b=>b.classList.toggle('active',b.dataset.symbol===symbol));renderReports();const url=new URL(location.href);url.searchParams.set('symbol',symbol);history.replaceState(null,'',url);}
catch(e){if(ctl.signal.aborted)return;const known=!!match;error(known?`${symbol} chưa có báo cáo đủ dữ liệu trong lần cập nhật hiện tại. Vui lòng chọn mã khác hoặc thử lại sau.`:'Không tìm thấy mã doanh nghiệp này. Vui lòng kiểm tra lại mã.');$('data-state').textContent='Chưa có dữ liệu';$('availability').textContent='Chưa mở lựa chọn năm cho mã này.';$('table-container').innerHTML='<div class="empty-state"><h3>Chưa có báo cáo để tải</h3><p>Chọn doanh nghiệp khác ở ô tra cứu.</p></div>';$('row-count').textContent='0 chỉ tiêu';$('updated-at').textContent='—';$('summary').textContent='Chưa có báo cáo';}
finally{if(!ctl.signal.aborted){state.loading=false;if(state.data)update();}}
}
function download(){if(!state.data||!state.years.length||!state.reports.length)return;try{const bytes=FinancialXlsx.workbook(state.data,state.years,state.reports);const blob=new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download=`${state.data.symbol}_Bao_cao_tai_chinh_${state.years.join('_')}.xlsx`;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$('download-status').textContent='Đã tạo Excel. File đang được tải về.';}catch(e){error(e.message);}}
$('company-form').addEventListener('submit',e=>{e.preventDefault();loadCompany($('ticker').value);});$('ticker').addEventListener('change',()=>loadCompany($('ticker').value));document.querySelectorAll('[data-symbol]').forEach(b=>b.addEventListener('click',()=>loadCompany(b.dataset.symbol)));
$('year-options').addEventListener('change',e=>{const y=Number(e.target.value);state.years=e.target.checked?[...new Set([...state.years,y])].sort((a,b)=>a-b):state.years.filter(v=>v!==y);renderPreview();});
$('report-options').addEventListener('change',e=>{const r=e.target.value;state.reports=e.target.checked?[...state.reports,r]:state.reports.filter(v=>v!==r);update();});
$('all-years').addEventListener('click',()=>{state.years=eligible();update();});$('recent-years').addEventListener('click',()=>{state.years=eligible().slice(-3);update();});$('clear-years').addEventListener('click',()=>{state.years=[];update();});
$('report-tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-report]');if(b){state.active=b.dataset.report;renderPreview();}});$('report-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const ids=state.data.sections.filter(s=>state.reports.includes(s.id)).map(s=>s.id);const i=ids.indexOf(state.active);state.active=ids[(i+(e.key==='ArrowRight'?1:ids.length-1))%ids.length];renderPreview();$('tab-'+state.active)?.focus();});$('download').addEventListener('click',download);
async function init(){try{state.companies=BOOT.companies||await json(DATA_BASE+'companies.json',null);$('company-options').innerHTML=state.companies.map(c=>`<option value="${esc(c.symbol)}">${esc(c.name)}</option>`).join('');$('company-description').textContent='Tìm trong '+nf.format(state.companies.length)+' doanh nghiệp.';}catch{$('company-description').textContent='Nhập mã doanh nghiệp để tra cứu.';}try{const live=await json(LIVE_BASE+'manifest.json',null,4000);if(live.schemaVersion===1&&live.companies?.length){state.base=LIVE_BASE;state.catalog=live.companies;}}catch{/* Bundled verified dataset is a complete offline fallback. */}await loadCompany(new URLSearchParams(location.search).get('symbol')||'MBB');registerTools();}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const life=new AbortController();context.registerTool({name:'select_financial_report',title:'Chọn báo cáo tài chính',description:'Chọn doanh nghiệp và các năm có dữ liệu, cập nhật bảng xem trước. Không tải file.',inputSchema:{type:'object',properties:{symbol:{type:'string'},years:{type:'array',items:{type:'integer'},minItems:1}},required:['symbol'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input){if(!input||typeof input.symbol!=='string'||!/^[A-Z][A-Z0-9]{1,7}$/.test(input.symbol.toUpperCase()))throw Error('Mã không hợp lệ');await loadCompany(input.symbol);if(!state.data)throw Error('Chưa có báo cáo');if(input.years){if(!Array.isArray(input.years)||!input.years.length||input.years.some(y=>!Number.isInteger(y)||!eligible().includes(y)))throw Error('Năm không có dữ liệu');state.years=[...new Set(input.years)].sort((a,b)=>a-b);update();}return{symbol:state.data.symbol,years:state.years,reports:state.reports};}},{signal:life.signal});window.addEventListener('pagehide',()=>life.abort(),{once:true});}
init();
})();
