(function(){'use strict';
const configURL=new URL(document.currentScript?.dataset.config||'chart-config.json',document.currentScript?.src||location.href).href;
const M=window.FinChartMath,L=window.LightweightCharts,$=id=>document.getElementById(id);
const raf=globalThis.requestAnimationFrame||((fn)=>fn());
const fmt=n=>Number.isFinite(n)?n.toLocaleString('vi-VN',{maximumFractionDigits:2}):'—';
const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=t=>new Date(t).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'});
const timeLabel=t=>typeof t==='number'?new Date(t*1000).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):typeof t==='string'?t:`${t.year}-${String(t.month).padStart(2,'0')}-${String(t.day).padStart(2,'0')}`;
const defaults={sma:20,ema:20,wma:20,vwma:20,rsi:14,fast:12,slow:26,signal:9,bb:20,deviation:2,vma:20,atr:14,adx:14,stoch:14,stochSignal:3,cci:20,roc:10,willr:14,mfi:14,cmf:20,supertrend:10,supertrendFactor:3};
function liquidityText(volumeRatio){
 const q=M.liquiditySignal?.(volumeRatio);if(!q)return'Khối lượng chưa có đủ 20 nến để đánh giá mức xác nhận';
 const pct=Math.abs(q.deltaPct),delta=q.deltaPct>=0?'cao hơn':'thấp hơn';
 if(q.level==='surge')return'Khối lượng '+fmt(q.ratio)+'x TB20, '+delta+' nền 20 phiên '+fmt(pct)+'%; thanh khoản mở rộng mạnh và đang xác nhận rõ tín hiệu';
 if(q.level==='elevated')return'Khối lượng '+fmt(q.ratio)+'x TB20, '+delta+' nền 20 phiên '+fmt(pct)+'%; thanh khoản cải thiện rõ và tạo mức xác nhận khá';
 if(q.level==='mildly_elevated')return'Khối lượng '+fmt(q.ratio)+'x TB20, '+delta+' nền 20 phiên '+fmt(pct)+'%; thanh khoản cải thiện nhẹ, mới bổ sung xác nhận vừa phải chứ chưa phải bùng nổ';
 if(q.level==='near_average')return'Khối lượng '+fmt(q.ratio)+'x TB20, chỉ lệch '+fmt(pct)+'% so với nền 20 phiên; mức tham gia gần trung bình và chưa bổ sung nhiều xác nhận';
 if(q.level==='thin')return'Khối lượng '+fmt(q.ratio)+'x TB20, thấp hơn nền 20 phiên '+fmt(pct)+'%; thanh khoản mỏng hơn bình thường nên tín hiệu giá còn thiếu xác nhận';
 return'Khối lượng '+fmt(q.ratio)+'x TB20, thấp hơn nền 20 phiên '+fmt(pct)+'%; thanh khoản co hẹp mạnh và độ tin cậy của tín hiệu giảm';
}
function moneyFlowText(current,previous){
 const f=M.moneyFlowSignal?.(current,previous);if(!f)return'Chưa đủ CMF, MFI hoặc OBV để kết luận hướng dòng tiền';
 const detail=f.parts.map(x=>x.name==='CMF'?'CMF '+fmt(x.value):x.name==='MFI'?'MFI '+fmt(x.value):'OBV '+(x.delta>0?'tăng':x.delta<0?'giảm':'đi ngang')).join(', ');
 const extreme=f.parts.find(x=>x.name==='MFI'&&x.extreme);
 const tail=extreme?.extreme==='high'?'; MFI đã cao nên cần lưu ý trạng thái mua mạnh có thể đi kèm rung lắc':extreme?.extreme==='low'?'; MFI rất thấp, áp lực bán vẫn cần được theo dõi':'';
 if(f.direction==='accumulation')return detail+'; các chỉ báo dòng tiền đang nghiêng về tích lũy'+tail;
 if(f.direction==='distribution')return detail+'; các chỉ báo dòng tiền đang nghiêng về phân phối'+tail;
 return detail+'; các chỉ báo dòng tiền chưa đồng thuận, chưa nên kết luận dòng tiền vào hoặc ra rõ'+tail;
}
class ChartController{
 constructor(base,onQuote){this.base=base;this.onQuote=onQuote;this.cache=new Map();this.params={...defaults};this.symbol='';this.tf=$('chart-interval')?.value||'1d';this.type='candles';this.bars=[];this.baseBars=[];this.values=[];this.series={};this.watch=[];this.generation=0;this.retries=0;this.stopped=false;this.buffer=[];this.signalEvents=[];this.signalSnapshot=null;this.signalCooldown=new Map();this.lastQuote=null;this.lastMarketQuote=null;this.lastSnapshotSource='';this.dataConsistent=true;this.insightItems=[];this.insightOpen=null;this.insightsVisible=false;
 this.chart=L.createChart($('price-chart'),{autoSize:true,height:540,layout:{background:{type:'solid',color:'#ffffff'},textColor:'#65728b',fontFamily:'Arial',attributionLogo:false},grid:{vertLines:{color:'#f2f4f8'},horzLines:{color:'#edf0f6'}},rightPriceScale:{borderColor:'#e5eaf3'},timeScale:{borderColor:'#e5eaf3',timeVisible:false,rightOffset:5,lockVisibleTimeRangeOnResize:true},crosshair:{mode:L.CrosshairMode.Normal},localization:{locale:'vi-VN',timeFormatter:timeLabel}});
 this.chart.subscribeCrosshairMove(e=>{const b=e.seriesData.get(this.series.price);if(b)this.readout({...b,volume:e.seriesData.get(this.series.volume)?.value});else this.readout(this.bars.at(-1));});
 this.chart.timeScale().subscribeVisibleLogicalRangeChange?.(()=>raf(()=>this.renderInsights()));
 $('chart-insight-markers')?.addEventListener('click',e=>{const b=e.target.closest('[data-insight-id]');if(b)this.insightOpen?.(b.dataset.insightId);});
 this.controls();this.configPromise=this.config();window.addEventListener('pagehide',()=>this.close());window.addEventListener('pageshow',e=>{if(e.persisted){this.stopped=false;this.connect();}});
 window.addEventListener('online',()=>this.connect());
 }
 async config(){try{const r=await fetch(configURL,{cache:'no-cache',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error();this.options=await r.json();}catch{this.options={};}this.connect();}
 status(text){const node=$('chart-stream-status');node.textContent=text;node.hidden=!text;}
 controls(){
 $('chart-interval').addEventListener('change',e=>{this.tf=e.target.value;const period=$('chart-period');if(M.intraday(this.tf)&&Number(period.value)!==0&&Number(period.value)>=12)period.value='3';if(M.intraday(this.tf)&&period.value==='0')period.value='3';this.load();});
 $('chart-type').addEventListener('change',e=>{this.type=e.target.value;this.rebuild(true);});
 $('chart-period').addEventListener('change',e=>{const months=Number(e.target.value);if(M.intraday(this.tf)&&(!months||months>=12)){this.tf='1d';$('chart-interval').value='1d';this.load();return;}this.range();});
 $('chart-zoom-in').addEventListener('click',()=>this.zoom(.75));$('chart-zoom-out').addEventListener('click',()=>this.zoom(1.3));
 $('chart-fit').addEventListener('click',()=>this.chart.timeScale().fitContent());
 const markerToggle=$('chart-marker-toggle');markerToggle?.addEventListener('click',()=>{this.insightsVisible=!this.insightsVisible;markerToggle.setAttribute('aria-pressed',String(this.insightsVisible));markerToggle.textContent=this.insightsVisible?'Mốc: bật':'Mốc: tắt';this.renderInsights();});
 $('chart-fullscreen').addEventListener('click',async()=>{const terminal=$('chart-terminal');if(terminal.classList.contains('chart-expanded')){terminal.classList.remove('chart-expanded');$('chart-fullscreen').textContent='Toàn màn hình';return;}try{if(document.fullscreenElement)await document.exitFullscreen();else await terminal.requestFullscreen();}catch{terminal.classList.add('chart-expanded');$('chart-fullscreen').textContent='Thoát toàn màn hình';}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('chart-terminal').classList.contains('chart-expanded')){$('chart-terminal').classList.remove('chart-expanded');$('chart-fullscreen').textContent='Toàn màn hình';}});
 document.addEventListener('fullscreenchange',()=>{$('chart-fullscreen').textContent=document.fullscreenElement?'Thoát toàn màn hình':'Toàn màn hình';});
 const dialog=$('chart-indicators');$('indicator-open')?.addEventListener('click',()=>{this.syncIndicatorSettings();dialog.showModal();$('indicator-search')?.focus();});$('indicator-close')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});$('indicator-search')?.addEventListener('input',e=>{const q=String(e.target.value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();(document.querySelectorAll?.('.indicator-list-item')||[]).forEach(row=>row.hidden=q&&!String(row.dataset.indicatorName||'').includes(q));});
 dialog.addEventListener('change',e=>{if(e.target.type==='number'){const key=e.target.dataset.param,n=Number(e.target.value),min=Number(e.target.min||0),max=Number(e.target.max||1e9),step=Number(e.target.step||1);const integer=step>=1;if(!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n))){e.target.value=this.params[key];return;}const next={...this.params,[key]:n};if(next.fast>=next.slow){e.target.value=this.params[key];$('chart-indicator-error').textContent='MACD: chu kỳ nhanh phải nhỏ hơn chu kỳ chậm.';return;}this.params=next;}$('chart-indicator-error').textContent='';this.syncIndicatorSettings();this.values=M.indicators(this.bars,this.params);this.rebuild(true);});
 this.syncIndicatorSettings();
 }
 select(symbol,watch=[]){this.watch=[...new Set([symbol,...watch])].filter(s=>/^[A-Z]{3}$/.test(s));if(this.symbol!==symbol){this.symbol=symbol;this.insightItems=[];this.renderInsights();this.signalEvents=[];this.signalSnapshot=null;this.signalCooldown.clear();this.lastQuote=null;this.lastMarketQuote=null;this.lastSnapshotSource='';this.dataConsistent=true;this.renderSignals();this.load();}else this.subscribe();}
 async load(force=false){const generation=++this.generation;this.abort?.abort();this.abort=new AbortController();const controller=this.abort;this.loading=true;this.buffer=[];const symbol=this.symbol,baseTF=M.intraday(this.tf)?'1m':'1d',key=symbol+':'+baseTF,previousBars=this.baseBars.map(b=>({...b})),previousValues=this.values.map(v=>({...v}));
 $('chart-status').textContent='Đang tải lịch sử '+symbol+'…';if(!previousBars.length){this.bars=[];this.baseBars=[];this.values=[];this.rebuild(false);}this.subscribe();await this.configPromise;if(generation!==this.generation)return;
 try{let data=this.cache.get(key);if(force||!data||Date.now()-data.cachedAt>300000){const url=this.options?.historyBase?new URL(`history?symbol=${symbol}&interval=${baseTF}`,this.options.historyBase).href:this.base+(baseTF==='1m'?'intraday/':'history/')+symbol+'.json';let raw;if(window.FinMarketData&&!this.options?.historyBase){raw=await window.FinMarketData.get((baseTF==='1m'?'intraday/':'history/')+symbol+'.json',{signal:controller.signal});}else{const r=await fetch(url,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)]),cache:'no-cache'});if(!r.ok)throw Error('HTTP '+r.status);raw=await r.json();}if(raw.symbol!==symbol||raw.unit!=='VND'||!Array.isArray(raw.bars))throw Error('Invalid history');data={...raw,bars:M.cleanBars(raw.bars,baseTF==='1m'),cachedAt:Date.now()};if(!data.bars.length)throw Error('Empty');this.cache.set(key,data);if(this.cache.size>24)this.cache.delete(this.cache.keys().next().value);}
 if(generation!==this.generation)return;this.baseBars=data.bars.map(b=>({...b}));if(!M.intraday(this.tf))this.mergeDailyQuote(this.lastMarketQuote,true);this.bars=M.aggregate(this.baseBars,this.tf);this.values=M.indicators(this.bars,this.params);this.loading=false;this.rebuild(false);this.range();this.consistency(this.lastMarketQuote);this.evaluateSignals(false);$('chart-status').textContent=`${data.source||'Vietcap'} · ${baseTF==='1m'?'Lịch sử nến phút':'Lịch sử nến ngày'} · Lấy lúc ${stamp(data.collectedAt)}${data.status==='retained'?' · Bản đã lưu':''}. ${this.lastMarketQuote&&this.lastSnapshotSource===this.lastMarketQuote.sourceTime?'Đã ghép snapshot phiên hiện tại.':'Nến cuối có thể chưa hoàn tất.'}`;this.consistency(this.lastMarketQuote);
 for(const message of this.buffer)this.candle(message);this.buffer=[];
 }catch(e){if(generation!==this.generation)return;this.loading=false;if(e.name==='AbortError')return;
  const cached=this.cache.get(key);
  if(cached?.bars?.length){this.baseBars=cached.bars.map(b=>({...b}));this.bars=M.aggregate(this.baseBars,this.tf);this.values=M.indicators(this.bars,this.params);this.rebuild(false);this.range();this.consistency(this.lastMarketQuote);this.evaluateSignals(false);$('chart-status').textContent='Nguồn cập nhật đang gián đoạn · đang giữ '+this.bars.length+' nến gần nhất đã lưu cho '+symbol+'.';return;}
  if(previousBars.length){this.baseBars=previousBars;this.bars=M.aggregate(this.baseBars,this.tf);this.values=previousValues.length===this.bars.length?previousValues:M.indicators(this.bars,this.params);this.rebuild(false);this.range();this.consistency(this.lastMarketQuote);this.evaluateSignals(false);$('chart-status').textContent='Nguồn cập nhật đang gián đoạn · biểu đồ vẫn dùng lịch sử đã tải trước đó.';return;}
  if(baseTF==='1m'){this.tf='1d';$('chart-interval').value='1d';$('chart-status').textContent='Nến phút chưa sẵn sàng cho '+symbol+' · chuyển sang toàn bộ lịch sử ngày.';return this.load(force);}
  $('chart-status').textContent='Chưa nhận được tệp lịch sử '+symbol+' từ nguồn dữ liệu.';
 }
 }
 enabled(name){return !!$('ind-'+name)?.checked;}
 rebuild(keep){const range=keep?this.chart.timeScale().getVisibleLogicalRange():null;for(const s of Object.values(this.series))this.chart.removeSeries(s);this.series={};
 const kind=this.type==='line'?L.LineSeries:this.type==='area'?L.AreaSeries:L.CandlestickSeries;
 this.series.price=this.chart.addSeries(kind,{upColor:'#089981',downColor:'#f23645',wickUpColor:'#089981',wickDownColor:'#f23645',borderVisible:false,color:'#4564cc',lineColor:'#4564cc',topColor:'#4564cc50',bottomColor:'#4564cc05',priceFormat:{type:'price',precision:0,minMove:1}},0);
 let pane=0;const line=(key,color,index=0)=>this.series[key]=this.chart.addSeries(L.LineSeries,{color,lineWidth:1,priceLineVisible:false,lastValueVisible:false,crosshairMarkerVisible:false},index);const guides=(series,levels)=>levels.forEach(price=>series.createPriceLine({price,color:'#abb3c3',lineWidth:1,lineStyle:2,axisLabelVisible:true,title:''}));
 if(this.enabled('volume')||this.enabled('vma')){pane++;this.series.volume=this.chart.addSeries(L.HistogramSeries,{priceFormat:{type:'volume'},priceLineVisible:false,lastValueVisible:false,visible:this.enabled('volume')},pane);if(this.enabled('vma'))line('vma','#d59637',pane);}
 if(this.enabled('sma'))line('sma','#da962b');if(this.enabled('ema'))line('ema','#725cce');if(this.enabled('wma'))line('wma','#227c9d');if(this.enabled('vwma'))line('vwma','#00897b');if(this.enabled('supertrend'))line('supertrend','#d04b64');
 if(this.enabled('bb')){line('upper','#7597ba');line('middle','#adb5c5');line('lower','#7597ba');}
 if(this.enabled('rsi')){pane++;line('rsi','#9764c7',pane);guides(this.series.rsi,[30,70]);}
 if(this.enabled('macd')){pane++;line('macd','#3777bc',pane);line('signal','#e69239',pane);this.series.hist=this.chart.addSeries(L.HistogramSeries,{priceLineVisible:false,lastValueVisible:false},pane);guides(this.series.macd,[0]);}
 if(this.enabled('atr')){pane++;line('atr','#8b6f47',pane);}
 if(this.enabled('adx')){pane++;line('adx','#6d5aa7',pane);guides(this.series.adx,[20,25]);}
 if(this.enabled('stoch')){pane++;line('stoch','#3478b8',pane);line('stochSignal','#e08a35',pane);guides(this.series.stoch,[20,80]);}
 if(this.enabled('cci')){pane++;line('cci','#7a5f9e',pane);guides(this.series.cci,[-100,100]);}
 if(this.enabled('roc')){pane++;line('roc','#2b8a7e',pane);guides(this.series.roc,[0]);}
 if(this.enabled('willr')){pane++;line('willr','#a56b35',pane);guides(this.series.willr,[-80,-20]);}
 if(this.enabled('obv')){pane++;line('obv','#4e6bb3',pane);}
 if(this.enabled('mfi')){pane++;line('mfi','#7b5cab',pane);guides(this.series.mfi,[20,80]);}
 if(this.enabled('cmf')){pane++;line('cmf','#318b6c',pane);guides(this.series.cmf,[0]);}
 this.series.price.setData(this.bars.map(b=>this.priceData(b)));if(this.series.volume)this.series.volume.setData(this.bars.map(b=>this.volumeData(b)));
 for(const [key,s]of Object.entries(this.series)){if(['price','volume'].includes(key))continue;s.setData(this.values.filter(v=>Number.isFinite(v[key])).map(v=>({time:v.time,value:v[key],...(key==='hist'?{color:v.hist>=0?'#08998188':'#f2364588'}:{})})));}
 this.chart.panes().forEach((p,i)=>p.setHeight(i?95:350));this.chart.applyOptions({timeScale:{timeVisible:M.intraday(this.tf),tickMarkFormatter:t=>M.intraday(this.tf)?new Date(t*1000).toLocaleTimeString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',hour:'2-digit',minute:'2-digit'}):null}});
 if(range)this.chart.timeScale().setVisibleLogicalRange(range);this.readout(this.bars.at(-1));this.renderInsights();
 }
 priceData(b){return this.type==='candles'?{time:b.time,open:b.open,high:b.high,low:b.low,close:b.close}:{time:b.time,value:b.close};}
 volumeData(b){return {time:b.time,value:b.volume,color:b.close>=b.open?'#08998177':'#f2364577'};}
 readout(b){if(!b){$('price-readout').textContent='Chưa có dữ liệu ở khung thời gian này.';return;}const original=this.bars.findLast(x=>x.time===b.time)||b;$('price-readout').textContent=`${this.symbol} · ${timeLabel(b.time)} · O ${fmt(original.open)}  H ${fmt(original.high)}  L ${fmt(original.low)}  C ${fmt(original.close)}  Vol ${fmt(original.volume)}`;}
 syncIndicatorSettings(){const selected=[];(document.querySelectorAll?.('#indicator-list input[type=checkbox]')||[]).forEach(x=>{if(x.checked)selected.push(x.id.replace('ind-',''));});(document.querySelectorAll?.('[data-settings-for]')||[]).forEach(card=>card.classList.toggle('active',selected.includes(card.dataset.settingsFor)));const empty=$('indicator-selected-empty');if(empty)empty.hidden=selected.length>0;}
 pushSignal(id,title,detail,tone='neutral',toast=true){const key=this.symbol+':'+this.tf+':'+id,now=Date.now(),last=this.signalCooldown.get(key)||0;if(toast&&now-last<12*60*1000)return;this.signalCooldown.set(key,now);const event={id,title,detail,tone,time:now};this.signalEvents=[event,...this.signalEvents.filter(x=>x.id!==id)].slice(0,6);this.renderSignals();if(toast){const stack=$('signal-toast-stack');if(stack){const node=document.createElement('div');node.className='signal-toast '+tone;node.innerHTML='<strong>'+title.replace(/[<>]/g,'')+'</strong><p>'+detail.replace(/[<>]/g,'')+'</p>';stack.prepend(node);setTimeout(()=>node.remove(),9000);}}}
 consistency(q=this.lastMarketQuote){
  const b=this.bars.at(-1),chartNode=$('price-chart');
  if(!q||!b||!Number.isFinite(Number(q.price))||!Number.isFinite(Number(b.close))){this.dataConsistent=true;chartNode?.classList.remove('chart-data-mismatch');return{ok:true,comparable:false};}
  const barDate=typeof b.time==='string'?b.time:(typeof b.time==='number'?new Date(b.time*1000).toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}):'');
  const quoteDate=q.sourceTime?new Date(q.sourceTime).toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}):'';
  if(barDate&&quoteDate&&barDate!==quoteDate){const staleIntraday=M.intraday(this.tf);this.dataConsistent=!staleIntraday;chartNode?.classList.toggle('chart-data-mismatch',staleIntraday);if(staleIntraday){this.signalSnapshot=null;this.signalEvents=[];this.renderSignals();this.status('Nến phút chưa cập nhật phiên hôm nay; FinQuery tạm ẩn tín hiệu kỹ thuật.');const signalStatus=$('signal-status');if(signalStatus)signalStatus.textContent='Nến phút chưa cập nhật phiên hôm nay';}return{ok:!staleIntraday,comparable:false,barDate,quoteDate,reason:staleIntraday?'stale_intraday_session':'different_session'};}
  const delta=Math.abs(Number(b.close)-Number(q.price))/Number(q.price),ok=delta<=.15;
  this.dataConsistent=ok;chartNode?.classList.toggle('chart-data-mismatch',!ok);
  if(!ok)this.status('Dữ liệu giá và biểu đồ đang lệch nhau; FinQuery tạm ẩn tín hiệu kỹ thuật cho đến khi đồng bộ.');
  return{ok,comparable:true,delta,barClose:Number(b.close),quotePrice:Number(q.price),barDate,quoteDate};
 }
 technicalContext(){const v=this.values.at(-1),p=this.values.at(-2),b=this.bars.at(-1),pb=this.bars.at(-2);if(!v||!b||!this.dataConsistent)return null;if(M.intraday(this.tf)){const q=this.lastMarketQuote,barDate=this.barDate(b.time),quoteDate=q?.sourceTime?new Date(q.sourceTime).toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}):'';if(!q||!barDate||!quoteDate||barDate!==quoteDate)return null;}const prior=this.bars.length>=21?this.bars.slice(-21,-1):[],avgVol=prior.length?prior.reduce((s,z)=>s+z.volume,0)/prior.length:null,volumeRatio=avgVol?b.volume/avgVol:null,smaDistance=Number.isFinite(v.sma)&&v.sma?100*(b.close/v.sma-1):null,bbPos=Number.isFinite(v.upper)&&Number.isFinite(v.lower)&&v.upper!==v.lower?100*(b.close-v.lower)/(v.upper-v.lower):null;return{symbol:this.symbol,timeframe:this.tf,bar:b,previousBar:pb,indicators:{sma:v.sma,ema:v.ema,wma:v.wma,vwma:v.vwma,rsi:v.rsi,macd:v.macd,signal:v.signal,hist:v.hist,upper:v.upper,middle:v.middle,lower:v.lower,atr:v.atr,adx:v.adx,stoch:v.stoch,stochSignal:v.stochSignal,cci:v.cci,roc:v.roc,willr:v.willr,obv:v.obv,mfi:v.mfi,cmf:v.cmf,supertrend:v.supertrend,supertrendDir:v.supertrendDir},previousIndicators:p||null,volumeRatio20:volumeRatio,smaDistancePct:smaDistance,bollingerPositionPct:bbPos,snapshot:this.signalSnapshot};}
 signalText(ctx){if(!ctx)return null;const v=ctx.indicators,p=ctx.previousIndicators||{},b=ctx.bar,parts=[],votes=[];if(Number.isFinite(v.rsi)){if(v.rsi<30){parts.push('RSI '+fmt(v.rsi)+' đang ở vùng quá bán');votes.push(-1);}else if(v.rsi<45){parts.push('RSI '+fmt(v.rsi)+' còn dưới vùng cân bằng 50');votes.push(-.5);}else if(v.rsi<=55){parts.push('RSI '+fmt(v.rsi)+' đã quay về vùng cân bằng quanh 50');votes.push(0);}else if(v.rsi<=70){parts.push('RSI '+fmt(v.rsi)+' duy trì động lượng tích cực');votes.push(.7);}else{parts.push('RSI '+fmt(v.rsi)+' ở vùng quá mua');votes.push(.25);}}
 if(Number.isFinite(v.macd)&&Number.isFinite(v.signal)){const spread=v.macd-v.signal;parts.push('MACD '+(spread>=0?'đứng trên':'đứng dưới')+' Signal '+fmt(Math.abs(spread)));votes.push(spread>=0?.8:-.8);}
 if(Number.isFinite(v.supertrendDir)){parts.push('Supertrend '+(v.supertrendDir>0?'đang tăng':'đang giảm'));votes.push(v.supertrendDir>0?1:-1);}
 if(Number.isFinite(v.adx)){parts.push('ADX '+fmt(v.adx)+(v.adx>=25?' cho thấy xu hướng có lực':' cho thấy xu hướng còn yếu'));votes.push(v.adx>=25?.25:0);}
 if(Number.isFinite(ctx.smaDistancePct)){parts.push('giá '+(ctx.smaDistancePct>=0?'cao hơn':'thấp hơn')+' SMA'+this.params.sma+' '+fmt(Math.abs(ctx.smaDistancePct))+'%');votes.push(ctx.smaDistancePct>=0?.6:-.6);}
 if(Number.isFinite(ctx.volumeRatio20)){parts.push(liquidityText(ctx.volumeRatio20));votes.push(ctx.volumeRatio20>=1.5?.35:ctx.volumeRatio20>=1.2?.25:ctx.volumeRatio20>=1.05?.1:ctx.volumeRatio20<.7?-.15:ctx.volumeRatio20<.9?-.05:0);}const flow=moneyFlowText(v,p);if(flow)parts.push(flow);
 const score=votes.length?votes.reduce((a,b)=>a+b,0)/votes.length:0,tone=score>.22?'positive':score<-.22?'negative':'neutral',title=score>.22?'Thiết lập kỹ thuật nghiêng tăng':score<-.22?'Thiết lập kỹ thuật nghiêng giảm':'Thiết lập kỹ thuật cân bằng';return{score,tone,title,detail:parts.join(' · ')+'.'};}
 renderSignals(){const title=$('signal-title'),status=$('signal-status'),feed=$('signal-feed');if(title)title.textContent=(this.symbol||'Mã đang xem')+' · '+this.tf;if(status)status.textContent='Tổng hợp xu hướng, động lượng, mean-reversion, thanh khoản và dòng tiền theo nến mới nhất';if(!feed)return;const all=[this.signalSnapshot,...this.signalEvents].filter(Boolean);if(!all.length){feed.innerHTML='<p>Đang tính trạng thái kỹ thuật…</p>';return;}feed.innerHTML=all.map(x=>'<div class="signal-chip '+x.tone+'"><strong>'+x.title.replace(/[<>]/g,'')+'</strong><span>'+x.detail.replace(/[<>]/g,'')+'</span></div>').join('');}
 evaluateSignals(toast=true){if(this.values.length<3||this.bars.length<3){this.signalSnapshot=null;this.renderSignals();return;}const p=this.values.at(-2),v=this.values.at(-1),pb=this.bars.at(-2),b=this.bars.at(-1);if(!p||!v)return;const ctx=this.technicalContext(),summary=this.signalText(ctx);if(summary)this.signalSnapshot={id:'snapshot',...summary,time:Date.now()};
 const cross=(a0,b0,a1,b1)=>Number.isFinite(a0)&&Number.isFinite(b0)&&Number.isFinite(a1)&&Number.isFinite(b1)&&((a0<=b0&&a1>b1)?1:(a0>=b0&&a1<b1)?-1:0);
 if(!ctx){this.signalSnapshot=null;this.signalEvents=[];this.renderSignals();return;}
 const rsiState=Number.isFinite(v.rsi)?(v.rsi<30?'đang ở vùng quá bán':v.rsi<45?'còn yếu và dưới vùng cân bằng 50':v.rsi<=55?'đang trung tính quanh vùng cân bằng 50':v.rsi<=70?'đang có động lượng tích cực, trên vùng cân bằng nhưng chưa quá mua':'động lượng rất mạnh nhưng đã vào vùng quá mua'):'chưa có RSI',vol=Number.isFinite(ctx?.volumeRatio20)?ctx.volumeRatio20:null,volText=liquidityText(vol),flowText=moneyFlowText(v,p),participationText=[volText,flowText].filter(Boolean).join('. '),trendText=Number.isFinite(v.supertrendDir)?('Supertrend '+(v.supertrendDir>0?'đang tăng':'đang giảm')):'Supertrend chưa sẵn sàng',meanText=Number.isFinite(ctx?.smaDistancePct)?('Giá hiện '+(ctx.smaDistancePct>=0?'cao hơn':'thấp hơn')+' SMA'+this.params.sma+' '+fmt(Math.abs(ctx.smaDistancePct))+'%'+(Math.abs(ctx.smaDistancePct)<=2?', tức vẫn khá gần đường trung bình':', cho thấy giá đã tách khỏi đường trung bình ở mức đáng chú ý')):'';
 let x=cross(p.macd,p.signal,v.macd,v.signal);if(x>0)this.pushSignal('macd-up','MACD cắt lên Signal','MACD vừa chuyển sang phía trên Signal trên khung '+this.tf+'. RSI '+fmt(v.rsi)+' ('+rsiState+'). '+participationText+'. '+trendText+'. '+meanText+'.','positive',toast);if(x<0)this.pushSignal('macd-down','MACD cắt xuống Signal','MACD vừa rơi xuống dưới Signal trên khung '+this.tf+'. RSI '+fmt(v.rsi)+' ('+rsiState+'). '+participationText+'. '+trendText+'. '+meanText+'.','negative',toast);
 if(Number.isFinite(p.rsi)&&Number.isFinite(v.rsi)){if(p.rsi<30&&v.rsi>=30)this.pushSignal('rsi-exit-low','RSI thoát vùng quá bán','RSI đã đi từ dưới 30 lên '+fmt(v.rsi)+', tức nhịp mean reversion đã bắt đầu. '+participationText+'. '+trendText+'. '+meanText+'.','positive',toast);if(p.rsi<=70&&v.rsi>70)this.pushSignal('rsi-high','RSI vào vùng quá mua','RSI lên '+fmt(v.rsi)+', động lượng tăng đang mạnh nhưng giá đã đi xa khỏi vùng cân bằng hơn. '+participationText+'. '+trendText+'.','neutral',toast);if(p.rsi>=30&&v.rsi<30)this.pushSignal('rsi-low','RSI vào vùng quá bán','RSI giảm xuống '+fmt(v.rsi)+', áp lực giảm đang ở trạng thái cực đoan. '+participationText+'. '+trendText+'. '+meanText+'.','negative',toast);}
 x=cross(pb.close,p.sma,b.close,v.sma);if(x>0)this.pushSignal('price-sma-up','Giá cắt lên SMA'+this.params.sma,'Giá đã vượt SMA'+this.params.sma+' và hiện '+(Number.isFinite(ctx?.smaDistancePct)?fmt(Math.abs(ctx.smaDistancePct))+'% phía trên đường trung bình. ':'')+'RSI '+fmt(v.rsi)+' ('+rsiState+'). '+participationText+'. '+trendText+'.','positive',toast);if(x<0)this.pushSignal('price-sma-down','Giá cắt xuống SMA'+this.params.sma,'Giá đã rơi xuống dưới SMA'+this.params.sma+'. RSI '+fmt(v.rsi)+' ('+rsiState+'). '+participationText+'. '+trendText+'.','negative',toast);
 if(Number.isFinite(p.supertrendDir)&&Number.isFinite(v.supertrendDir)&&p.supertrendDir!==v.supertrendDir){this.pushSignal('supertrend-flip','Supertrend đổi hướng',(v.supertrendDir>0?'Supertrend vừa chuyển sang tăng. ':'Supertrend vừa chuyển sang giảm. ')+'MACD '+(v.macd>=v.signal?'trên':'dưới')+' Signal, RSI '+fmt(v.rsi)+', '+participationText.toLowerCase()+'.',v.supertrendDir>0?'positive':'negative',toast);}
 if(Number.isFinite(p.adx)&&Number.isFinite(v.adx)&&p.adx<25&&v.adx>=25)this.pushSignal('adx-25','ADX vượt 25','ADX tăng lên '+fmt(v.adx)+', xác nhận xu hướng đang mạnh lên. Hướng hiện tại: '+(v.supertrendDir>0?'tăng':'giảm')+' theo Supertrend; MACD '+(v.macd>=v.signal?'trên':'dưới')+' Signal; '+participationText.toLowerCase()+'.',v.supertrendDir>0?'positive':'negative',toast);
 if(Number.isFinite(vol)&&vol>=1.5)this.pushSignal('volume-spike','Khối lượng tăng mạnh','Khối lượng đạt '+fmt(vol)+'x trung bình 20 nến. Giá '+(b.close>=pb.close?'tăng':'giảm')+' so với nến trước, RSI '+fmt(v.rsi)+', MACD '+(v.macd>=v.signal?'trên':'dưới')+' Signal và Supertrend '+(v.supertrendDir>0?'tăng':'giảm')+'.',b.close>=pb.close?'positive':'negative',toast);
 this.renderSignals();
 }
 mergeDailyQuote(q,force=false){
  if(!q||q.symbol!==this.symbol||M.intraday(this.tf)||!this.baseBars.length||!Number.isFinite(Number(q.price))||!Number.isFinite(Date.parse(q.sourceTime||'')))return false;
  if(!force&&q.sourceTime===this.lastSnapshotSource)return false;
  const day=new Date(q.sourceTime).toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}),last=this.baseBars.at(-1),lastDay=this.barDate(last?.time);
  if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!lastDay||day<lastDay)return false;
  const price=Number(q.price),openLive=Number(q.open),highLive=Number(q.high),lowLive=Number(q.low),volumeLive=Number(q.volume);
  if(day===lastDay){
   this.baseBars[this.baseBars.length-1]={...last,close:price,high:Math.max(Number(last.high)||price,Number.isFinite(highLive)?highLive:price,price),low:Math.min(Number(last.low)||price,Number.isFinite(lowLive)?lowLive:price,price),volume:Number.isFinite(volumeLive)?Math.max(Number(last.volume)||0,volumeLive):Number(last.volume)||0,live:true};
  }else{
   const open=Number.isFinite(openLive)&&openLive>0?openLive:price,high=Math.max(open,price,Number.isFinite(highLive)?highLive:price),low=Math.min(open,price,Number.isFinite(lowLive)?lowLive:price);
   this.baseBars.push({time:day,open,high,low,close:price,volume:Number.isFinite(volumeLive)&&volumeLive>=0?volumeLive:0,live:true,openEstimated:!(Number.isFinite(openLive)&&openLive>0)});
  }
  this.lastQuote={price,volume:q.volume,sourceTime:q.sourceTime};this.lastSnapshotSource=q.sourceTime;return true;
 }
 snapshot(q){if(!q||q.symbol!==this.symbol)return;this.lastMarketQuote=q;if(!Number.isFinite(Number(q.price))||!Number.isFinite(Date.parse(q.sourceTime||''))||!this.bars.length){this.consistency(q);return;}
  if(!M.intraday(this.tf)){
   if(!this.mergeDailyQuote(q)){this.consistency(q);return;}this.bars=M.aggregate(this.baseBars,this.tf);this.values=M.indicators(this.bars,this.params);this.rebuild(true);this.evaluateSignals(true);this.renderInsights();this.consistency(q);this.status('Snapshot live · '+this.barDate(this.baseBars.at(-1)?.time)+' · C '+fmt(Number(q.price))+' · cập nhật chỉ báo');return;
  }
  if(q.sourceTime===this.lastSnapshotSource)return;const ts=Date.parse(q.sourceTime)/1000,bucket=M.bucket(ts,this.tf),last=this.bars.at(-1);if(typeof last.time!=='number'||bucket<last.time)return;const prevQ=this.lastQuote,deltaVol=prevQ&&Number.isFinite(q.volume)&&Number.isFinite(prevQ.volume)&&q.volume>=prevQ.volume?Math.max(0,q.volume-prevQ.volume):0;let bar;if(bucket===last.time){bar={...last,high:Math.max(last.high,q.price),low:Math.min(last.low,q.price),close:q.price,volume:last.volume+deltaVol};this.bars[this.bars.length-1]=bar;}else{const open=prevQ?.price||last.close||q.price;bar={time:bucket,open,high:Math.max(open,q.price),low:Math.min(open,q.price),close:q.price,volume:deltaVol};this.bars.push(bar);}this.lastQuote={price:q.price,volume:q.volume,sourceTime:q.sourceTime};this.lastSnapshotSource=q.sourceTime;this.values=M.indicators(this.bars,this.params);this.rebuild(true);this.evaluateSignals(true);this.status('Snapshot '+this.tf+' · '+timeLabel(bucket)+' · tự cập nhật chỉ báo');}
 noteNews(item){if(!item?.title)return;const topics=item.topics||[],direct=(item.symbols||[]).includes(this.symbol);let read='Tin thị trường mới';if(direct)read='Tin gắn trực tiếp với '+this.symbol+'; ưu tiên theo dõi phản ứng giá, khối lượng và sức mạnh tương đối ở các snapshot tiếp theo.';else if(topics.includes('rates')||topics.includes('banking'))read='Tin lãi suất/ngân hàng; nhóm tài chính và các doanh nghiệp nhạy với chi phí vốn có thể phản ứng trước.';else if(topics.includes('stocks')||topics.includes('market'))read='Tin thị trường; tác động rộng nên đọc cùng VN100 và sức mạnh tương đối của '+this.symbol+'.';this.pushSignal('news:'+String(item.url||item.title).slice(-48),'Tin mới · '+(item.source||'Thị trường'),item.title+' — '+read,'news',true);}

 setInsights(items,onOpen){this.insightItems=Array.isArray(items)?items.filter(x=>x&&x.id&&x.date):[];this.insightOpen=typeof onOpen==='function'?onOpen:null;this.renderInsights();}
 barDate(time){if(typeof time==='string')return time.slice(0,10);if(typeof time==='number')return new Date(time*1000).toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'});if(time&&typeof time==='object')return String(time.year)+'-'+String(time.month).padStart(2,'0')+'-'+String(time.day).padStart(2,'0');return'';}
 snapInsightTime(day){if(!day||!this.bars.length)return null;const target=String(day).slice(0,10),first=this.barDate(this.bars[0].time),last=this.barDate(this.bars.at(-1).time);if(!first||!last||target<first||target>last)return null;let prior=null;for(const b of this.bars){const d=this.barDate(b.time);if(d===target)return b.time;if(d>target)return prior?.time||null;prior=b;}return null;}
 renderInsights(){const layer=$('chart-insight-markers');if(!layer)return;if(!this.insightsVisible){layer.innerHTML='';return;}if(!this.bars.length||!this.insightItems.length||!this.series.price){layer.innerHTML='';return;}const grouped=new Map(),buttons=[],height=layer.clientHeight||420;for(const item of this.insightItems){const time=this.snapInsightTime(item.date);if(time==null)continue;const x=this.chart.timeScale().timeToCoordinate(time);if(!Number.isFinite(x)||x<-20||x>(layer.clientWidth||9999)+20)continue;const bar=this.bars.find(b=>String(b.time)===String(time))||this.bars.find(b=>this.barDate(b.time)===this.barDate(time));if(!bar)continue;const key=String(time)+':'+String(item.kind||'event'),stack=grouped.get(key)||0;grouped.set(key,stack+1);const isResearch=item.kind==='research',anchorPrice=isResearch?Number(bar.high):Number(bar.low),anchorY=this.series.price.priceToCoordinate?.(anchorPrice);if(!Number.isFinite(anchorY))continue;const rawTop=isResearch?anchorY-34-stack*30:anchorY+10+stack*30,top=Math.max(8,Math.min(height-32,rawTop));const stemTop=isResearch?top+26:anchorY,stemBottom=isResearch?anchorY:top;buttons.push('<span class="chart-insight-stem '+(isResearch?'research':'event')+'" style="left:'+x.toFixed(1)+'px;top:'+Math.min(stemTop,stemBottom).toFixed(1)+'px;height:'+Math.max(6,Math.abs(stemBottom-stemTop)).toFixed(1)+'px"></span><button type="button" class="chart-insight-marker '+html(item.kind||'event')+' '+html(item.tone||'')+'" data-insight-id="'+html(item.id)+'" style="left:'+x.toFixed(1)+'px;top:'+top.toFixed(1)+'px" title="'+html(item.title||'')+'" aria-label="'+html(item.title||item.label||'Sự kiện')+'"><span>'+html(item.label||'•')+'</span></button>');}layer.innerHTML=buttons.join('');}
 range(){if(!this.bars.length)return;const months=Number($('chart-period').value),first=this.bars[0],last=this.bars.at(-1),labelTime=t=>typeof t==='number'?new Date(t*1000).toLocaleDateString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):String(t);if(!months){this.chart.timeScale().fitContent();$('chart-range-label').textContent=`${this.bars.length} nến · ${labelTime(first.time)} → ${labelTime(last.time)} · toàn bộ lịch sử có sẵn`;raf(()=>this.renderInsights());return;}const end=typeof last.time==='number'?new Date(last.time*1000):new Date(last.time+'T12:00:00Z'),start=new Date(end);start.setUTCMonth(start.getUTCMonth()-months);let index=this.bars.findIndex(b=>(typeof b.time==='number'?b.time*1000:Date.parse(b.time+'T12:00:00Z'))>=+start);if(index<0)index=0;this.chart.timeScale().setVisibleLogicalRange({from:Math.max(0,index),to:this.bars.length+3});$('chart-range-label').textContent=`${this.bars.length-index} nến trong khoảng xem · ${labelTime(this.bars[index]?.time)} → ${labelTime(last.time)}`;raf(()=>this.renderInsights());}
 zoom(f){const r=this.chart.timeScale().getVisibleLogicalRange();if(r){const mid=(r.from+r.to)/2,half=(r.to-r.from)*f/2;this.chart.timeScale().setVisibleLogicalRange({from:mid-half,to:mid+half});}}
 subscribe(){if(this.socket?.readyState===WebSocket.OPEN){this.socket.send(JSON.stringify({type:'subscribe',symbols:this.watch,intervals:['1m','1d']}));}}
 connect(){clearTimeout(this.retry);if(this.stopped||!this.options)return;if(!this.options.websocketUrl){this.status('');return;}if(!/^wss:\/\//.test(this.options.websocketUrl)){this.status('Cấu hình WebSocket cần địa chỉ wss:// hợp lệ.');return;}if(this.socket&&this.socket.readyState<2)return;
 this.status('Đang kết nối luồng giá…');const socket=this.socket=new WebSocket(this.options.websocketUrl);
 socket.onopen=()=>{this.retries=0;this.status('Đã kết nối · Đang chờ dữ liệu thị trường');this.subscribe();if(this.hasConnected)this.load(true);this.hasConnected=true;};
 socket.onmessage=e=>{if(socket!==this.socket)return;clearTimeout(this.staleTimer);this.staleTimer=setTimeout(()=>this.status('Chưa nhận thông điệp mới trong 90 giây · Kiểm tra trạng thái nguồn/phiên'),90000);try{const m=JSON.parse(e.data);if(m.type==='ping'){socket.send(JSON.stringify({type:'pong'}));return;}if(m.type==='status'){this.status(String(m.message||'Đang chờ dữ liệu').slice(0,160));return;}if(m.type==='quote'&&this.watch.includes(m.symbol)&&Number.isFinite(m.price)&&m.price>0&&Number.isFinite(Date.parse(m.sourceTime))){this.onQuote(m);return;}if(m.type==='candle'){if(this.loading){if(this.buffer.length<2000)this.buffer.push(m);}else this.candle(m);}}catch{this.status('Bỏ qua thông điệp thị trường không hợp lệ.');}};
 socket.onclose=()=>{if(this.stopped)return;this.status('Mất kết nối · Giữ dữ liệu cuối, đang kết nối lại');this.retry=setTimeout(()=>this.connect(),Math.min(30000,1000*2**Math.min(this.retries++,5))+Math.random()*500);};socket.onerror=()=>socket.close();
 }
 candle(m){const baseTF=M.intraday(this.tf)?'1m':'1d';if(m.symbol!==this.symbol||m.interval!==baseTF||m.unit!=='VND')return;const next=M.cleanBars([m.bar],baseTF==='1m')[0];if(!next||(typeof next.time==='number'&&next.time>Date.now()/1000+60))return;const last=this.baseBars.at(-1);if(last&&next.time<last.time)return;if(last&&next.time===last.time)this.baseBars[this.baseBars.length-1]=next;else this.baseBars.push(next);
 // Reaggregate only the current bucket, preserving every earlier rendered candle.
 const t=M.bucket(next.time,this.tf),tail=[];for(let i=this.baseBars.length-1;i>=0&&M.bucket(this.baseBars[i].time,this.tf)===t;i--)tail.unshift(this.baseBars[i]);const b=M.aggregate(tail,this.tf)[0];if(this.bars.at(-1)?.time===b.time)this.bars[this.bars.length-1]=b;else this.bars.push(b);
 const i=this.bars.length-1,v=M.point(this.bars,i,this.params,this.values[i-1]);this.values[i]=v;this.series.price.update(this.priceData(b));this.series.volume?.update(this.volumeData(b));for(const [key,s]of Object.entries(this.series))if(!['price','volume'].includes(key)&&Number.isFinite(v[key]))s.update({time:b.time,value:v[key],...(key==='hist'?{color:v.hist>=0?'#08998188':'#f2364588'}:{})});
 this.readout(b);this.evaluateSignals(true);this.renderInsights();this.cache.delete(this.symbol+':'+baseTF);this.status(`WebSocket · Nến ${timeLabel(next.time)} · Nhận lúc ${new Date().toLocaleTimeString('vi-VN')}`);
 }
 close(){this.stopped=true;clearTimeout(this.retry);clearTimeout(this.staleTimer);this.abort?.abort();this.socket?.close();}
}
window.FinChart={create:(base,onQuote)=>{if(!L||!M){$('chart-status').textContent='Không tải được thư viện biểu đồ. Vui lòng mở lại trang.';return {select(){},load(){},snapshot(){},noteNews(){},setInsights(){},technicalContext(){return null;}};}return new ChartController(base,onQuote);}};
})();
