(function(){'use strict';
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9%]+/g,' ').trim();
const C=[
{id:'roe',title:'ROE',aliases:['roe','return on equity','ty suat loi nhuan tren von chu'],definition:'ROE cho biết 100 đồng vốn chủ sở hữu bình quân tạo ra bao nhiêu đồng lợi nhuận sau thuế trong kỳ.',formula:'Lợi nhuận sau thuế / Vốn chủ sở hữu bình quân × 100%',read:'ROE tăng cùng lợi nhuận và dòng tiền thường cho thấy hiệu quả vốn tốt lên. ROE cao nhưng nợ tăng nhanh thì cần tách phần cải thiện do kinh doanh khỏi phần do đòn bẩy.',metric:'roe'},
{id:'roa',title:'ROA',aliases:['roa','return on assets','ty suat sinh loi tren tai san'],definition:'ROA cho biết 100 đồng tài sản bình quân tạo ra bao nhiêu đồng lợi nhuận sau thuế trong kỳ.',formula:'Lợi nhuận sau thuế / Tổng tài sản bình quân × 100%',read:'ROA càng cao và ổn định thì tài sản đang tạo lợi nhuận tốt hơn. Khi ROA giảm, cần xem biên lợi nhuận, vòng quay tài sản và tài sản mới đầu tư đã tạo doanh thu hay chưa.',metric:'roa'},
{id:'roic',title:'ROIC',aliases:['roic','return on invested capital','loi nhuan tren von dau tu'],definition:'ROIC đo lợi nhuận hoạt động sau thuế tạo ra trên phần vốn dài hạn thực sự được đưa vào kinh doanh.',formula:'NOPAT / Vốn đầu tư bình quân × 100%',read:'ROIC cao hơn chi phí vốn trong thời gian dài cho thấy doanh nghiệp tạo thêm giá trị từ vốn bỏ vào hoạt động.',metric:null},
{id:'grossMargin',title:'Biên lợi nhuận gộp',aliases:['bien loi nhuan gop','gross margin','bien gop'],definition:'Biên gộp cho biết sau khi trừ giá vốn, 100 đồng doanh thu còn lại bao nhiêu đồng để trang trải chi phí vận hành, tài chính và thuế.',formula:'Lợi nhuận gộp / Doanh thu thuần × 100%',read:'Biên gộp tăng thường đến từ giá bán tốt hơn, cơ cấu sản phẩm tốt hơn hoặc chi phí đầu vào giảm. Biên giảm kéo dài cho thấy sức ép giá vốn hoặc cạnh tranh.',metric:'grossMargin'},
{id:'netMargin',title:'Biên lợi nhuận ròng',aliases:['bien loi nhuan rong','net margin','bien rong'],definition:'Biên ròng cho biết 100 đồng doanh thu cuối cùng giữ lại bao nhiêu đồng lợi nhuận sau thuế.',formula:'Lợi nhuận sau thuế / Doanh thu thuần × 100%',read:'Biên ròng tăng cho thấy doanh thu được chuyển thành lợi nhuận tốt hơn; cần xem mức tăng đến từ hoạt động chính hay khoản bất thường.',metric:'netMargin'},
{id:'ebitda',title:'EBITDA',aliases:['ebitda'],definition:'EBITDA là lợi nhuận trước lãi vay, thuế và khấu hao, dùng để nhìn khả năng tạo lợi nhuận từ hoạt động trước cấu trúc tài trợ và chính sách khấu hao.',formula:'EBIT + Khấu hao và phân bổ',read:'EBITDA tăng nhưng dòng tiền kinh doanh không tăng tương ứng thì cần xem vốn lưu động và chất lượng doanh thu.',metric:null},
{id:'eps',title:'EPS',aliases:['eps','earnings per share','lai tren moi co phieu'],definition:'EPS là phần lợi nhuận sau thuế thuộc về mỗi cổ phiếu đang lưu hành.',formula:'LNST thuộc cổ đông công ty mẹ / Số cổ phiếu bình quân',read:'EPS tăng bền vững cho thấy lợi nhuận trên mỗi cổ phần cải thiện; phát hành thêm cổ phiếu có thể làm EPS tăng chậm hơn lợi nhuận tuyệt đối.',metric:null},
{id:'pe',title:'P/E',aliases:['p e','pe','price earnings','he so pe'],definition:'P/E cho biết thị trường đang trả bao nhiêu đồng cho 1 đồng lợi nhuận một năm của doanh nghiệp.',formula:'Giá cổ phiếu / EPS',read:'P/E cao thường phản ánh kỳ vọng tăng trưởng cao hơn hoặc mức định giá đắt hơn. So sánh nên đặt cùng ngành, chu kỳ lợi nhuận và tốc độ tăng trưởng.',metric:null},
{id:'pb',title:'P/B',aliases:['p b','pb','price book','he so pb'],definition:'P/B so giá thị trường với giá trị sổ sách trên mỗi cổ phiếu.',formula:'Giá cổ phiếu / BVPS',read:'P/B đặc biệt đáng chú ý với ngân hàng và doanh nghiệp tài sản lớn. P/B thấp không tự động rẻ nếu ROE thấp hoặc chất lượng tài sản yếu.',metric:null},
{id:'ocf',title:'OCF / CFO',aliases:['ocf','cfo','dong tien hoat dong kinh doanh','dong tien hd kinh doanh'],definition:'OCF là tiền thực thu trừ tiền thực chi từ hoạt động kinh doanh trong kỳ.',formula:'Dòng tiền thuần từ hoạt động kinh doanh',read:'OCF dương và đi cùng lợi nhuận cho thấy lợi nhuận được chuyển thành tiền. Lợi nhuận tăng nhưng OCF yếu kéo dài thường liên quan phải thu, tồn kho hoặc khoản phải trả.',metric:'ocf'},
{id:'fcf',title:'FCF',aliases:['fcf','free cash flow','dong tien tu do'],definition:'FCF là phần tiền còn lại sau khi hoạt động kinh doanh tạo tiền và doanh nghiệp đã chi cho đầu tư tài sản dài hạn.',formula:'OCF - Chi đầu tư tài sản cố định',read:'FCF dương tạo dư địa trả nợ, cổ tức, mua lại cổ phiếu hoặc tái đầu tư. FCF âm có thể bình thường trong giai đoạn mở rộng nếu dự án mới tạo tăng trưởng đủ tốt.',metric:'fcf'},
{id:'capex',title:'CAPEX',aliases:['capex','chi dau tu','chi dau tu tai san'],definition:'CAPEX là tiền chi cho nhà xưởng, máy móc, hạ tầng và tài sản dài hạn phục vụ nhiều kỳ.',formula:'Tiền chi mua sắm, xây dựng tài sản dài hạn',read:'CAPEX cao cần đọc cùng tăng trưởng công suất, doanh thu tương lai và FCF; một mình CAPEX cao không nói tốt hay xấu.',metric:'capex'},
{id:'receivables',title:'Khoản phải thu',aliases:['phai thu','receivables','phai thu khach hang'],definition:'Khoản phải thu là phần doanh thu hoặc nghĩa vụ thanh toán mà doanh nghiệp đã ghi nhận nhưng chưa thu tiền.',formula:'Số dư phải thu tại ngày báo cáo',read:'Nếu phải thu tăng nhanh hơn doanh thu nhiều kỳ, tiền đang bị giữ ở khách hàng lâu hơn và chất lượng tăng trưởng doanh thu cần được xem kỹ.',metric:'receivables'},
{id:'inventory',title:'Hàng tồn kho',aliases:['ton kho','hang ton kho','inventory'],definition:'Hàng tồn kho là nguyên vật liệu, sản phẩm dở dang và hàng hóa chưa được bán tại ngày báo cáo.',formula:'Số dư hàng tồn kho',read:'Tồn kho tăng cùng doanh thu có thể phục vụ mở rộng. Tồn kho tăng nhanh hơn doanh thu kéo dài làm vốn bị giữ lại và tăng rủi ro giảm giá hoặc chậm tiêu thụ.',metric:'inventory'},
{id:'liabilitiesAssets',title:'Nợ phải trả / Tổng tài sản',aliases:['no tren tai san','liabilities assets','no phai tra tren tong tai san'],definition:'Tỷ lệ này cho biết bao nhiêu phần trăm tài sản được tài trợ bằng nợ phải trả.',formula:'Nợ phải trả / Tổng tài sản × 100%',read:'Tỷ lệ cao làm doanh nghiệp nhạy hơn với lãi suất, dòng tiền và khả năng tái cấp vốn; mức hợp lý phụ thuộc ngành.',metric:'liabilitiesAssets'},
{id:'liabilitiesEquity',title:'Nợ / Vốn chủ',aliases:['no tren von chu','debt equity','d e','liabilities equity'],definition:'Tỷ lệ nợ trên vốn chủ cho biết quy mô nghĩa vụ nợ so với phần vốn thuộc chủ sở hữu.',formula:'Nợ phải trả / Vốn chủ sở hữu',read:'Tỷ lệ tăng nhanh cho thấy doanh nghiệp đang dựa nhiều hơn vào nguồn vốn nợ.',metric:'liabilitiesEquity'},
{id:'quick',title:'Thanh toán nhanh',aliases:['quick ratio','thanh toan nhanh','ty so thanh toan nhanh'],definition:'Thanh toán nhanh đo khả năng dùng tài sản ngắn hạn có tính thanh khoản cao để trả nợ ngắn hạn, không dựa nhiều vào việc bán tồn kho.',formula:'(Tiền + Đầu tư ngắn hạn + Phải thu) / Nợ ngắn hạn',read:'Tỷ lệ dưới 1 kéo dài có thể tạo áp lực vốn lưu động; mức chuẩn khác nhau theo ngành.',metric:'quick'},
{id:'workingCapital',title:'Vốn lưu động',aliases:['von luu dong','working capital'],definition:'Vốn lưu động là phần tài sản ngắn hạn còn lại sau khi trừ nợ ngắn hạn.',formula:'Tài sản ngắn hạn - Nợ ngắn hạn',read:'Vốn lưu động tăng do phải thu hoặc tồn kho tăng chưa chắc tốt; cần xem dòng tiền kinh doanh đi cùng.',metric:null},
{id:'yoy',title:'YoY',aliases:['yoy','year over year','cung ky'],definition:'YoY so một kỳ với đúng kỳ tương ứng của năm trước.',formula:'(Kỳ hiện tại / Cùng kỳ năm trước - 1) × 100%',read:'YoY phù hợp để giảm ảnh hưởng mùa vụ khi đọc doanh thu và lợi nhuận quý.',metric:null},
{id:'qoq',title:'QoQ',aliases:['qoq','quarter over quarter','quy truoc'],definition:'QoQ so quý hiện tại với quý ngay trước đó.',formula:'(Quý hiện tại / Quý trước - 1) × 100%',read:'QoQ phản ánh tốc độ thay đổi ngắn hạn nhưng dễ bị mùa vụ tác động.',metric:null},
{id:'cagr',title:'CAGR',aliases:['cagr','tang truong kep'],definition:'CAGR là tốc độ tăng trưởng bình quân năm theo lãi kép giữa hai mốc thời gian.',formula:'(Giá trị cuối / Giá trị đầu)^(1/số năm) - 1',read:'CAGR giúp tóm tắt xu hướng nhiều năm nhưng không cho thấy biến động từng năm ở giữa.',metric:null},
{id:'sma',title:'SMA',aliases:['sma','simple moving average','duong trung binh don'],definition:'SMA là giá trung bình của một số nến gần nhất, mỗi nến có trọng số như nhau.',formula:'Tổng giá đóng cửa N nến / N',read:'Giá nằm trên SMA và SMA dốc lên thường cho thấy cấu trúc xu hướng đang tích cực hơn; cắt SMA chỉ là một tín hiệu, cần đọc cùng động lượng và khối lượng.',metric:null},
{id:'ema',title:'EMA',aliases:['ema','exponential moving average'],definition:'EMA là đường trung bình ưu tiên trọng số lớn hơn cho các nến mới.',formula:'EMA mới = EMA trước + hệ số × (giá mới - EMA trước)',read:'EMA phản ứng nhanh hơn SMA nên phù hợp để theo dõi thay đổi xu hướng ngắn hạn.',metric:null},
{id:'rsi',title:'RSI',aliases:['rsi','relative strength index','qua mua qua ban'],definition:'RSI đo tương quan giữa các nhịp tăng và giảm gần đây trên thang 0-100.',formula:'100 - 100 / (1 + RS), với RS là mức tăng bình quân / mức giảm bình quân',read:'RSI dưới 30 là trạng thái bán mạnh; đi trở lại trên 30 là mean reversion ban đầu. RSI quanh 50 là vùng cân bằng; trên 55 cho thấy động lượng tăng rõ hơn; trên 70 là tăng mạnh nhưng đã xa vùng cân bằng.',metric:null},
{id:'macd',title:'MACD',aliases:['macd','moving average convergence divergence','signal line'],definition:'MACD lấy chênh lệch giữa EMA nhanh và EMA chậm để đo hướng và xung lực của xu hướng.',formula:'MACD = EMA nhanh - EMA chậm; Signal = EMA của MACD',read:'MACD cắt lên Signal cho thấy xung lực đang chuyển tích cực; chất lượng tín hiệu mạnh hơn khi RSI cải thiện, giá đứng trên đường trung bình và khối lượng tăng.',metric:null},
{id:'bollinger',title:'Bollinger Bands',aliases:['bollinger','bollinger bands','bbands'],definition:'Bollinger Bands đặt hai biên quanh đường trung bình dựa trên độ lệch chuẩn của giá.',formula:'Middle = SMA; Upper/Lower = SMA ± k × độ lệch chuẩn',read:'Giá chạm biên không tự động là đảo chiều. Độ rộng dải phản ánh biến động, còn vị trí giá trong dải cho thấy giá đang ở đâu so với phân phối gần đây.',metric:null},
{id:'atr',title:'ATR',aliases:['atr','average true range'],definition:'ATR đo biên độ dao động thực tế trung bình, tập trung vào độ lớn biến động chứ không đo hướng.',formula:'Trung bình True Range trong N nến',read:'ATR tăng nghĩa là giá đang dao động mạnh hơn; ATR giảm nghĩa là biên dao động co lại.',metric:null},
{id:'adx',title:'ADX',aliases:['adx','average directional index'],definition:'ADX đo độ mạnh của xu hướng, không nói xu hướng tăng hay giảm.',formula:'Được tính từ +DI, -DI và DX',read:'ADX trên khoảng 25 thường cho thấy xu hướng đã có lực; hướng phải đọc cùng giá, Supertrend hoặc MACD.',metric:null},
{id:'stochastic',title:'Stochastic',aliases:['stochastic','stoch','%k','%d'],definition:'Stochastic đo vị trí giá đóng cửa so với biên cao-thấp của một khoảng nến gần nhất.',formula:'%K = (Close - Lowest Low) / (Highest High - Lowest Low) × 100',read:'Chỉ báo nhạy với mean reversion; vùng dưới 20 là yếu, trên 80 là mạnh nhưng dễ rung lắc.',metric:null},
{id:'supertrend',title:'Supertrend',aliases:['supertrend'],definition:'Supertrend kết hợp giá trung bình và ATR để tạo một ngưỡng xu hướng bám theo biến động.',formula:'Dải cơ sở ± hệ số × ATR',read:'Giá trên Supertrend là trạng thái xu hướng tăng theo mô hình; giá dưới Supertrend là trạng thái xu hướng giảm.',metric:null},
{id:'obv',title:'OBV',aliases:['obv','on balance volume'],definition:'OBV cộng khối lượng khi giá tăng và trừ khối lượng khi giá giảm để theo dõi hướng tích lũy dòng tiền.',formula:'OBV mới = OBV trước ± Volume',read:'OBV tăng cùng giá củng cố xu hướng; phân kỳ OBV và giá thường đáng chú ý.',metric:null},
{id:'mfi',title:'MFI',aliases:['mfi','money flow index'],definition:'MFI kết hợp giá và khối lượng để đo áp lực tiền vào/ra trên thang 0-100.',formula:'Dựa trên Typical Price × Volume và tỷ lệ dòng tiền dương/âm',read:'MFI thấp cho thấy áp lực bán và dòng tiền ra mạnh; MFI cao cho thấy tiền vào mạnh.',metric:null},
{id:'cmf',title:'CMF',aliases:['cmf','chaikin money flow'],definition:'CMF đo vị trí đóng cửa trong biên nến có trọng số khối lượng để ước lượng dòng tiền tích lũy hoặc phân phối.',formula:'Tổng Money Flow Volume / Tổng Volume',read:'CMF trên 0 cho thấy dòng tiền nghiêng tích lũy; dưới 0 nghiêng phân phối.',metric:null},
{id:'volume',title:'Khối lượng',aliases:['volume','khoi luong','thanh khoan giao dich'],definition:'Khối lượng là số cổ phiếu được khớp trong một khoảng thời gian.',formula:'Tổng số cổ phiếu khớp lệnh',read:'Một biến động giá đi cùng khối lượng cao hơn bình quân thường có mức xác nhận thị trường mạnh hơn biến động trên thanh khoản mỏng.',metric:null},
{id:'meanReversion',title:'Mean reversion',aliases:['mean reversion','hoi ve trung binh','quay lai trung binh'],definition:'Mean reversion là hiện tượng giá hoặc chỉ báo sau khi lệch xa mức bình quân có xu hướng quay về vùng cân bằng.',formula:'Không có một công thức duy nhất; thường đọc bằng độ lệch so với SMA/VWAP và RSI',read:'RSI rời vùng quá bán và giá tiến lại SMA là một dạng mean reversion. Mean reversion không đồng nghĩa xu hướng dài hạn đã đảo chiều.',metric:null},
{id:'volatility',title:'Biến động',aliases:['volatility','bien dong','do bien dong'],definition:'Biến động đo mức độ giá dao động quanh mức trung bình trong một khoảng thời gian.',formula:'Thường dùng độ lệch chuẩn của lợi suất hoặc ATR',read:'Biến động cao làm biên lời/lỗ tiềm năng lớn hơn và khoảng dừng kỹ thuật cũng cần rộng hơn.',metric:null},
{id:'drawdown',title:'Drawdown',aliases:['drawdown','muc sut giam'],definition:'Drawdown là mức giảm từ đỉnh gần nhất xuống đáy sau đó.',formula:'(Giá hiện tại / Đỉnh trước đó - 1) × 100%',read:'Drawdown giúp nhìn mức thiệt hại đã xảy ra trong một chu kỳ giảm, khác với biến động ngày.',metric:null},
{id:'reference',title:'Giá tham chiếu',aliases:['gia tham chieu','reference price','phien truoc','gia dong cua phien truoc'],definition:'Giá tham chiếu là mốc dùng để tính phần trăm tăng giảm của phiên hiện tại, thường là giá đóng cửa điều chỉnh của phiên trước theo quy tắc sàn.',formula:'% thay đổi = (Giá hiện tại / Giá tham chiếu - 1) × 100%',read:'Nếu cổ phiếu tăng 3,59%, cần nhìn luôn giá tham chiếu và mức tăng tuyệt đối bằng đồng để biết phiên trước thị trường đang định giá ở đâu.',metric:null},
{id:'pmi',title:'PMI',aliases:['pmi','purchasing managers index'],definition:'PMI là chỉ số khảo sát nhà quản trị mua hàng về đơn hàng, sản lượng, việc làm, tồn kho và thời gian giao hàng.',formula:'Chỉ số khuếch tán từ khảo sát doanh nghiệp',read:'PMI trên 50 thường cho thấy hoạt động sản xuất mở rộng; dưới 50 cho thấy thu hẹp.',metric:null},
{id:'gdp',title:'GDP',aliases:['gdp','tong san pham trong nuoc'],definition:'GDP là tổng giá trị hàng hóa và dịch vụ cuối cùng được tạo ra trong nền kinh tế trong một giai đoạn.',formula:'Có thể tính theo sản xuất, chi tiêu hoặc thu nhập',read:'Tăng trưởng GDP phản ánh tốc độ mở rộng của nền kinh tế, nhưng ảnh hưởng lên từng ngành khác nhau.',metric:null},
{id:'m2',title:'Cung tiền M2',aliases:['m2','cung tien','money supply'],definition:'M2 là thước đo lượng tiền rộng trong nền kinh tế, gồm tiền mặt, tiền gửi thanh toán và nhiều loại tiền gửi có tính thanh khoản cao.',formula:'Tổng các thành phần tiền theo định nghĩa thống kê tiền tệ',read:'M2 tăng nhanh thường đi cùng điều kiện thanh khoản dồi dào hơn; cần đọc cùng tín dụng, lạm phát và lãi suất.',metric:null},
{id:'credit',title:'Tăng trưởng tín dụng',aliases:['tin dung','credit growth','du no tin dung'],definition:'Tăng trưởng tín dụng cho biết dư nợ cho vay của hệ thống tăng bao nhiêu so với mốc trước.',formula:'(Dư nợ hiện tại / Dư nợ mốc so sánh - 1) × 100%',read:'Tín dụng tăng hỗ trợ cầu và hoạt động kinh tế nhưng tốc độ quá nhanh có thể làm áp lực lạm phát và chất lượng tài sản tăng.',metric:null},
{id:'omo',title:'OMO',aliases:['omo','thi truong mo','open market operation'],definition:'OMO là nghiệp vụ Ngân hàng Nhà nước bơm hoặc hút thanh khoản ngắn hạn qua giao dịch giấy tờ có giá với các tổ chức tín dụng.',formula:'Theo khối lượng phát hành/đáo hạn và giao dịch từng ngày',read:'Bơm ròng thường giảm căng thanh khoản VND; hút ròng thường rút phần tiền dư. Tác động lên lãi suất liên ngân hàng còn phụ thuộc nhu cầu vay và trạng thái thanh khoản trước đó.',metric:null},
{id:'overnight',title:'Lãi suất qua đêm liên ngân hàng',aliases:['overnight','lai suat qua dem','lai suat on','on rate'],definition:'Lãi suất qua đêm là mức lãi các ngân hàng vay mượn VND với nhau trong thời hạn một ngày.',formula:'Lãi suất giao dịch bình quân theo dữ liệu liên ngân hàng',read:'ON tăng nhanh thường phản ánh nhu cầu VND ngắn hạn căng hơn; ON giảm cho thấy thanh khoản ngắn hạn bớt căng hoặc cầu vay giảm.',metric:null},
{id:'inflation',title:'Lạm phát / CPI',aliases:['lam phat','cpi','consumer price index'],definition:'CPI đo mức thay đổi giá của một rổ hàng hóa và dịch vụ tiêu dùng; tốc độ tăng CPI thường được dùng để theo dõi lạm phát.',formula:'(CPI kỳ này / CPI kỳ gốc - 1) × 100%',read:'Lạm phát tăng có thể làm chính sách tiền tệ thận trọng hơn và ảnh hưởng chi phí vốn, sức mua và biên lợi nhuận.',metric:null},
{id:'fdi',title:'FDI',aliases:['fdi','dau tu truc tiep nuoc ngoai'],definition:'FDI là vốn đầu tư trực tiếp từ nhà đầu tư nước ngoài vào dự án hoặc doanh nghiệp trong nước.',formula:'Theo vốn đăng ký, điều chỉnh và vốn thực hiện',read:'FDI thực hiện cho thấy lượng vốn thực sự được giải ngân; FDI đăng ký phản ánh quy mô cam kết và kỳ vọng đầu tư.',metric:null}
];
const byId=Object.fromEntries(C.map(x=>[x.id,x]));
function scoreConcept(q,c){const s=norm(q);let score=0;for(const a of c.aliases||[]){const n=norm(a);if(s===n)score+=12;else if(s.includes(n))score+=8;else{const toks=n.split(' ').filter(Boolean);score+=toks.reduce((z,t)=>z+(s.includes(t)?1:0),0);}}return score;}
function find(question){const ranked=C.map(c=>({c,score:scoreConcept(question,c)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);return ranked[0]?.c||null;}
function explainLabel(label){const s=norm(label);if(/doanh thu/.test(s))return'Chỉ tiêu doanh thu ghi nhận giá trị hàng hóa hoặc dịch vụ doanh nghiệp tạo ra trong kỳ.';if(/loi nhuan/.test(s))return'Chỉ tiêu lợi nhuận cho biết phần giá trị còn lại sau các nhóm chi phí tương ứng trong kỳ.';if(/tai san/.test(s))return'Chỉ tiêu tài sản phản ánh nguồn lực kinh tế doanh nghiệp đang kiểm soát tại ngày báo cáo.';if(/no phai tra|no vay/.test(s))return'Chỉ tiêu nợ phản ánh nghĩa vụ doanh nghiệp phải thanh toán cho bên ngoài.';if(/von chu/.test(s))return'Vốn chủ sở hữu là phần giá trị còn lại thuộc cổ đông sau khi lấy tài sản trừ nợ phải trả.';if(/dong tien|luu chuyen tien/.test(s))return'Chỉ tiêu dòng tiền ghi nhận tiền thực thu và thực chi, khác với lợi nhuận kế toán.';if(/chi phi/.test(s))return'Chỉ tiêu chi phí ghi nhận nguồn lực đã sử dụng để tạo doanh thu hoặc duy trì hoạt động trong kỳ.';if(/tang truong/.test(s))return'Chỉ tiêu tăng trưởng đo tốc độ thay đổi so với mốc trước hoặc cùng kỳ.';if(/ty suat|ty so|bien/.test(s))return'Đây là tỷ lệ dùng để so quy mô của hai chỉ tiêu và theo dõi chất lượng hoạt động qua thời gian.';return'Đây là một chỉ tiêu đang có trong dữ liệu FinQuery của doanh nghiệp.';}
window.FinQueryKnowledge={concepts:C,byId,find,explainLabel,norm};
})();