(function(){'use strict';
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9%]+/g,' ').trim();
const C=[
{id:'roe',title:'ROE',aliases:['roe','return on equity','ty suat loi nhuan tren von chu'],definition:'ROE cho biết 100 đồng vốn chủ sở hữu bình quân tạo ra bao nhiêu đồng lợi nhuận sau thuế trong kỳ.',formula:'Lợi nhuận sau thuế / Vốn chủ sở hữu bình quân × 100%',read:'ROE tăng cùng lợi nhuận và dòng tiền thường cho thấy hiệu quả vốn tốt lên. ROE cao nhưng nợ tăng nhanh thì cần tách phần cải thiện do kinh doanh khỏi phần do đòn bẩy.',metric:'roe'},
{id:'roa',title:'ROA',aliases:['roa','return on assets','ty suat sinh loi tren tai san'],definition:'ROA cho biết 100 đồng tài sản bình quân tạo ra bao nhiêu đồng lợi nhuận sau thuế trong kỳ.',formula:'Lợi nhuận sau thuế / Tổng tài sản bình quân × 100%',read:'ROA càng cao và ổn định thì tài sản đang tạo lợi nhuận tốt hơn. Khi ROA giảm, cần xem biên lợi nhuận, vòng quay tài sản và tài sản mới đầu tư đã tạo doanh thu hay chưa.',metric:'roa'},
{id:'roic',title:'ROIC',aliases:['roic','return on invested capital','loi nhuan tren von dau tu'],definition:'ROIC đo lợi nhuận hoạt động sau thuế tạo ra trên phần vốn dài hạn thực sự được đưa vào kinh doanh.',formula:'NOPAT / Vốn đầu tư bình quân × 100%',read:'ROIC cao hơn chi phí vốn trong thời gian dài cho thấy doanh nghiệp tạo thêm giá trị từ vốn bỏ vào hoạt động.',metric:null},
{id:'grossMargin',title:'Biên lợi nhuận gộp',aliases:['bien loi nhuan gop','gross margin','bien gop'],definition:'Biên gộp cho biết sau khi trừ giá vốn, 100 đồng doanh thu còn lại bao nhiêu đồng để trang trải chi phí vận hành, tài chính và thuế.',formula:'Lợi nhuận gộp / Doanh thu thuần × 100%',read:'Biên gộp tăng thường đến từ giá bán tốt hơn, cơ cấu sản phẩm tốt hơn hoặc chi phí đầu vào giảm. Biên giảm kéo dài cho thấy sức ép giá vốn hoặc cạnh tranh.',metric:'grossMargin'},
{id:'netMargin',title:'Biên lợi nhuận ròng',aliases:['bien loi nhuan rong','net margin','bien rong'],definition:'Biên ròng cho biết 100 đồng doanh thu cuối cùng giữ lại bao nhiêu đồng lợi nhuận sau thuế.',formula:'Lợi nhuận sau thuế / Doanh thu thuần × 100%',read:'Biên ròng tăng cho thấy doanh thu được chuyển thành lợi nhuận tốt hơn; cần xem mức tăng đến từ hoạt động chính hay khoản bất thường.',metric:'netMargin'},
{id:'ebitda',title:'EBITDA',aliases:['ebitda'],definition:'EBITDA là lợi nhuận trước lãi vay, thuế và khấu hao, dùng để nhìn khả năng tạo lợi nhuận từ hoạt động trước cấu trúc tài trợ và chính sách khấu hao.',formula:'EBIT + Khấu hao và phân bổ',read:'EBITDA tăng nhưng dòng tiền kinh doanh không tăng tương ứng thì cần xem vốn lưu động và chất lượng doanh thu.',metric:null},
{id:'eps',title:'EPS',aliases:['eps','earnings per share','lai tren moi co phieu'],definition:'EPS là phần lợi nhuận sau thuế thuộc về mỗi cổ phiếu đang lưu hành.',formula:'LNST thuộc cổ đông công ty mẹ / Số cổ phiếu bình quân',read:'EPS tăng bền vững cho thấy lợi nhuận trên mỗi cổ phần cải thiện; phát hành thêm cổ phiếu có thể làm EPS tăng chậm hơn lợi nhuận tuyệt đối.',metric:null},
{id:'pe',title:'P/E',aliases:['p e','pe','price earnings','he so pe'],definition:'P/E cho biết thị trường đang trả bao nhiêu đồng cho 1 đồng lợi nhuận một năm của doanh nghiệp.',formula:'Giá cổ phiếu / EPS',read:'P/E cao thường phản ánh kỳ vọng tăng trưởng cao hơn hoặc mức định giá đắt hơn. So sánh nên đặt cùng ngành, chu kỳ lợi nhuận và tốc độ tăng trưởng.',metric:null},
{id:'pb',title:'P/B',aliases:['p b','pb','price book','he so pb'],definition:'P/B so giá thị trường với giá trị sổ sách trên mỗi cổ phiếu.',formula:'Giá cổ phiếu / BVPS',read:'P/B đặc biệt đáng chú ý với ngân hàng và doanh nghiệp tài sản lớn. P/B thấp không tự động rẻ nếu ROE thấp hoặc chất lượng tài sản yếu.',metric:null},
{id:'ocf',title:'OCF / CFO',aliases:['ocf','cfo','dong tien hoat dong kinh doanh','dong tien hd kinh doanh'],definition:'OCF là tiền thực thu trừ tiền thực chi từ hoạt động kinh doanh trong kỳ.',formula:'Dòng tiền thuần từ hoạt động kinh doanh',read:'OCF dương và đi cùng lợi nhuận cho thấy lợi nhuận được chuyển thành tiền. Lợi nhuận tăng nhưng OCF yếu kéo dài thường liên quan phải thu, tồn kho hoặc khoản phải trả.',metric:'ocf'},
{id:'fcf',title:'FCF',aliases:['fcf','free cash flow','dong tien tu do'],definition:'FCF là phần tiền còn lại sau khi hoạt động kinh doanh tạo tiền và doanh nghiệp đã chi cho đầu tư tài sản dài hạn.',formula:'OCF - Chi đầu tư tài sản cố định',read:'FCF dương tạo dư địa trả nợ, cổ tức, mua lại cổ phiếu hoặc tái đầu tư. FCF âm có thể bình thường trong giai đoạn mở rộng nếu dự án mới tạo tăng trưởng đủ tốt.',metric:'fcf'},
{id:'capex',title:'CAPEX',aliases:['capex','chi dau tu','chi dau tu tai san'],definition:'CAPEX là tiền chi cho nhà xưởng, máy móc, hạ tầng và tài sản dài hạn phục vụ nhiều kỳ.',formula:'Tiền chi mua sắm, xây dựng tài sản dài hạn',read:'CAPEX cao cần đọc cùng tăng trưởng công suất, doanh thu tương lai và FCF; một mình CAPEX cao không nói tốt hay xấu.',metric:'capex'},
{id:'receivables',title:'Khoản phải thu',aliases:['phai thu','receivables','phai thu khach hang'],definition:'Khoản phải thu là phần doanh thu hoặc nghĩa vụ thanh toán mà doanh nghiệp đã ghi nhận nhưng chưa thu tiền.',formula:'Số dư phải thu tại ngày báo cáo',read:'Nếu phải thu tăng nhanh hơn doanh thu nhiều kỳ, tiền đang bị giữ ở khách hàng lâu hơn và chất lượng tăng trưởng doanh thu cần được xem kỹ.',metric:'receivables'},
{id:'inventory',title:'Hàng tồn kho',aliases:['ton kho','hang ton kho','inventory'],definition:'Hàng tồn kho là nguyên vật liệu, sản phẩm dở dang và hàng hóa chưa được bán tại ngày báo cáo.',formula:'Số dư hàng tồn kho',read:'Tồn kho tăng cùng doanh thu có thể phục vụ mở rộng. Tồn kho tăng nhanh hơn doanh thu kéo dài làm vốn bị giữ lại và tăng rủi ro giảm giá hoặc chậm tiêu thụ.',metric:'inventory'},
{id:'liabilitiesAssets',title:'Nợ phải trả / Tổng tài sản',aliases:['no tren tai san','liabilities assets','no phai tra tren tong tai san'],definition:'Tỷ lệ này cho biết bao nhiêu phần trăm tài sản được tài trợ bằng nợ phải trả.',formula:'Nợ phải trả / Tổng tài sản × 100%',read:'Tỷ lệ cao làm doanh nghiệp nhạy hơn với lãi suất, dòng tiền và khả năng tái cấp vốn; mức hợp lý phụ thuộc ngành.',metric:'liabilitiesAssets'},
{id:'liabilitiesEquity',title:'Nợ / Vốn chủ',aliases:['no tren von chu','debt equity','d e','liabilities equity'],definition:'Tỷ lệ nợ trên vốn chủ cho biết quy mô nghĩa vụ nợ so với phần vốn thuộc chủ sở hữu.',formula:'Nợ phải trả / Vốn chủ sở hữu',read:'Tỷ lệ tăng nhanh cho thấy doanh nghiệp đang dựa nhiều hơn vào nguồn vốn nợ.',metric:'liabilitiesEquity'},
{id:'quick',title:'Thanh toán nhanh',aliases:['quick ratio','thanh toan nhanh','ty so thanh toan nhanh'],definition:'Thanh toán nhanh đo khả năng dùng tài sản ngắn hạn có tính thanh khoản cao để trả nợ ngắn hạn, không dựa nhiều vào việc bán tồn kho.',formula:'(Tiền + Đầu tư ngắn hạn + Phải thu) / Nợ ngắn hạn',read:'Tỷ lệ dưới 1 kéo dài có thể tạo áp lực vốn lưu động; mức chuẩn khác nhau theo ngành.',metric:'quick'},
{id:'currentAssets',title:'Tài sản ngắn hạn',aliases:['tai san ngan han','current assets','short term assets'],definition:'Tài sản ngắn hạn là tài sản dự kiến thu hồi, bán hoặc sử dụng trong chu kỳ kinh doanh thông thường hoặc trong vòng 12 tháng; gồm tiền và tương đương tiền, đầu tư tài chính ngắn hạn, phải thu ngắn hạn, hàng tồn kho và các tài sản ngắn hạn khác.',formula:'Tổng các khoản mục tài sản ngắn hạn trên bảng cân đối kế toán',read:'Đánh giá theo cơ cấu tiền, phải thu, tồn kho và khả năng chuyển đổi thành tiền; tài sản ngắn hạn tăng không tự động có nghĩa thanh khoản tốt.',metric:null},
{id:'nonCurrentAssets',title:'Tài sản dài hạn',aliases:['tai san dai han','non current assets','noncurrent assets','long term assets'],definition:'Tài sản dài hạn là tài sản không được phân loại vào nhóm ngắn hạn, thường gồm tài sản cố định, bất động sản đầu tư, xây dựng cơ bản dở dang và các khoản đầu tư dài hạn.',formula:'Tổng tài sản - Tài sản ngắn hạn',read:'Cần đối chiếu với công suất, khấu hao, hiệu quả đầu tư và dòng tiền tạo ra trong dài hạn.',metric:null},
{id:'currentLiabilities',title:'Nợ ngắn hạn',aliases:['no ngan han','current liabilities','short term liabilities'],definition:'Nợ ngắn hạn là nghĩa vụ dự kiến thanh toán trong chu kỳ kinh doanh thông thường hoặc đến hạn trong vòng 12 tháng, theo tiêu chí phân loại kế toán áp dụng.',formula:'Tổng các khoản nợ ngắn hạn trên bảng cân đối kế toán',read:'So sánh với tiền, tài sản ngắn hạn và dòng tiền kinh doanh để đánh giá áp lực thanh toán.',metric:null},
{id:'workingCapital',title:'Vốn lưu động',aliases:['von luu dong','working capital'],definition:'Vốn lưu động là phần tài sản ngắn hạn còn lại sau khi trừ nợ ngắn hạn.',formula:'Tài sản ngắn hạn - Nợ ngắn hạn',read:'Vốn lưu động tăng do phải thu hoặc tồn kho tăng chưa chắc tốt; cần xem dòng tiền kinh doanh đi cùng.',metric:null},
{id:'yoy',title:'YoY',aliases:['yoy','year over year','cung ky'],definition:'YoY so một kỳ với đúng kỳ tương ứng của năm trước.',formula:'(Kỳ hiện tại / Cùng kỳ năm trước - 1) × 100%',read:'YoY phù hợp để giảm ảnh hưởng mùa vụ khi đọc doanh thu và lợi nhuận quý.',metric:null},
{id:'qoq',title:'QoQ',aliases:['qoq','quarter over quarter','quy truoc'],definition:'QoQ so quý hiện tại với quý ngay trước đó.',formula:'(Quý hiện tại / Quý trước - 1) × 100%',read:'QoQ phản ánh tốc độ thay đổi ngắn hạn nhưng dễ bị mùa vụ tác động.',metric:null},
{id:'cagr',title:'CAGR',aliases:['cagr','tang truong kep'],definition:'CAGR là tốc độ tăng trưởng bình quân năm theo lãi kép giữa hai mốc thời gian.',formula:'(Giá trị cuối / Giá trị đầu)^(1/số năm) - 1',read:'CAGR giúp tóm tắt xu hướng nhiều năm nhưng không cho thấy biến động từng năm ở giữa.',metric:null},
{id:'sma',title:'SMA',aliases:['sma','simple moving average','duong trung binh don'],definition:'SMA là giá trung bình của một số nến gần nhất, mỗi nến có trọng số như nhau.',formula:'Tổng giá đóng cửa N nến / N',read:'Giá nằm trên SMA và SMA dốc lên thường cho thấy cấu trúc xu hướng đang tích cực hơn; cắt SMA chỉ là một tín hiệu, cần đọc cùng động lượng và khối lượng.',metric:null},
{id:'ema',title:'EMA',aliases:['ema','exponential moving average'],definition:'EMA là đường trung bình ưu tiên trọng số lớn hơn cho các nến mới.',formula:'EMA mới = EMA trước + hệ số × (giá mới - EMA trước)',read:'EMA phản ứng nhanh hơn SMA nên phù hợp để theo dõi thay đổi xu hướng ngắn hạn.',metric:null},
{id:'rsi',title:'RSI',aliases:['rsi','relative strength index','qua mua qua ban'],definition:'RSI đo tương quan giữa các nhịp tăng và giảm gần đây trên thang 0-100.',formula:'100 - 100 / (1 + RS), với RS là mức tăng bình quân / mức giảm bình quân',read:'RSI dưới 30 là trạng thái bán mạnh; đi trở lại trên 30 là mean reversion ban đầu. RSI quanh 50 là vùng cân bằng; trên 55 cho thấy động lượng tăng rõ hơn; trên 70 là tăng mạnh nhưng đã xa vùng cân bằng.',metric:null},
{id:'macd',title:'MACD',aliases:['macd','moving average convergence divergence','signal line'],definition:'MACD lấy chênh lệch giữa EMA nhanh và EMA chậm để đo hướng và xung lực của xu hướng.',formula:'MACD = EMA nhanh - EMA chậm; Signal = EMA của MACD',read:'MACD cắt lên Signal cho thấy xung lực đang chuyển tích cực; chất lượng tín hiệu mạnh hơn khi RSI cải thiện, giá đứng trên đường trung bình và khối lượng tăng.',metric:null},
{id:'bollinger',title:'Bollinger Bands',aliases:['bollinger','bollinger bands','bbands'],definition:'Bollinger Bands đặt hai biên quanh đường trung bình dựa trên độ lệch chuẩn của giá.',formula:'Middle = SMA; Upper/Lower = SMA ± k × độ lệch chuẩn',read:'Giá chạm biên không tự động là đảo chiều. Độ rộng dải phản ánh biến động, còn vị trí giá trong dải cho thấy giá đang ở đâu so với phân phối gần đây.',metric:null},
{id:'atr',title:'ATR',aliases:['atr','average true range'],definition:'ATR đo biên độ dao động thực tế trung bình, tập trung vào độ lớn biến động chứ không đo hướng.',formula:'Trung bình True Range trong N nến',read:'ATR tăng nghĩa là giá đang dao động mạnh hơn; ATR giảm nghĩa là biên dao động co lại.',metric:null},
{id:'adx',title:'ADX',aliases:['adx','average directional index'],definition:'ADX đo độ mạnh của xu hướng, không nói xu hướng tăng hay giảm.',formula:'Được tính từ +DI, -DI và DX',read:'ADX trên khoảng 25 thường cho thấy xu hướng đã có lực; hướng phải đọc cùng giá, Supertrend hoặc MACD.',metric:null},
{id:'stochastic',title:'Stochastic',aliases:['stochastic','stoch','%k','%d'],definition:'Stochastic đo vị trí giá đóng cửa so với biên cao-thấp của một khoảng nến gần nhất.',formula:'%K = (Close - Lowest Low) / (Highest High - Lowest Low) × 100',read:'Chỉ báo nhạy với mean reversion; vùng dưới 20 là yếu, trên 80 là mạnh nhưng dễ rung lắc.',metric:null},
{id:'supertrend',title:'Supertrend',aliases:['supertrend'],definition:'Supertrend kết hợp giá trung bình và ATR để tạo một ngưỡng xu hướng bám theo biến động.',formula:'Dải cơ sở ± hệ số × ATR',read:'Giá trên Supertrend là trạng thái xu hướng tăng theo mô hình; giá dưới Supertrend là trạng thái xu hướng giảm.',metric:null},
{id:'obv',title:'OBV',aliases:['obv','on balance volume'],definition:'OBV cộng khối lượng khi giá tăng và trừ khối lượng khi giá giảm để theo dõi hướng tích lũy dòng tiền.',formula:'OBV mới = OBV trước ± Volume',read:'OBV tăng cùng giá củng cố xu hướng; phân kỳ OBV và giá thường đáng chú ý.',metric:null},
{id:'mfi',title:'MFI',aliases:['mfi','money flow index'],definition:'MFI kết hợp giá và khối lượng để đo áp lực tiền vào/ra trên thang 0-100.',formula:'Dựa trên Typical Price × Volume và tỷ lệ dòng tiền dương/âm',read:'MFI thấp cho thấy áp lực bán và dòng tiền ra mạnh; MFI cao cho thấy tiền vào mạnh.',metric:null},
{id:'cmf',title:'CMF',aliases:['cmf','chaikin money flow'],definition:'CMF đo vị trí đóng cửa trong biên nến có trọng số khối lượng để ước lượng dòng tiền tích lũy hoặc phân phối.',formula:'Tổng Money Flow Volume / Tổng Volume',read:'CMF trên 0 cho thấy dòng tiền nghiêng tích lũy; dưới 0 nghiêng phân phối.',metric:null},
{id:'volume',title:'Khối lượng',aliases:['volume','khoi luong','thanh khoan giao dich'],definition:'Khối lượng là số cổ phiếu được khớp trong một khoảng thời gian.',formula:'Tổng số cổ phiếu khớp lệnh',read:'Một biến động giá đi cùng khối lượng cao hơn bình quân thường có mức xác nhận thị trường mạnh hơn biến động trên thanh khoản mỏng.',metric:null},
{id:'meanReversion',title:'Mean reversion',aliases:['mean reversion','hoi ve trung binh','quay lai trung binh'],definition:'Mean reversion là hiện tượng giá hoặc chỉ báo sau khi lệch xa mức bình quân có xu hướng quay về vùng cân bằng.',formula:'Không có một công thức duy nhất; thường đọc bằng độ lệch so với SMA/VWAP và RSI',read:'RSI rời vùng quá bán và giá tiến lại SMA là một dạng mean reversion. Mean reversion không đồng nghĩa xu hướng dài hạn đã đảo chiều.',metric:null},
{id:'volatility',title:'Biến động',aliases:['volatility','bien dong','do bien dong'],definition:'Biến động đo mức độ giá dao động quanh mức trung bình trong một khoảng thời gian.',formula:'Thường dùng độ lệch chuẩn của lợi suất hoặc ATR',read:'Biến động cao làm biên lời/lỗ tiềm năng lớn hơn và khoảng dừng kỹ thuật cũng cần rộng hơn.',metric:null},
{id:'drawdown',title:'Drawdown',aliases:['drawdown','muc sut giam'],definition:'Drawdown là mức giảm từ đỉnh gần nhất xuống đáy sau đó.',formula:'(Giá hiện tại / Đỉnh trước đó - 1) × 100%',read:'Drawdown giúp nhìn mức thiệt hại đã xảy ra trong một chu kỳ giảm, khác với biến động ngày.',metric:null},
{id:'reference',title:'Giá tham chiếu',aliases:['gia tham chieu','reference price','phien truoc','gia dong cua phien truoc'],definition:'Giá tham chiếu là mốc dùng để tính phần trăm tăng giảm của phiên hiện tại, thường là giá đóng cửa điều chỉnh của phiên trước theo quy tắc sàn.',formula:'% thay đổi = (Giá hiện tại / Giá tham chiếu - 1) × 100%',read:'Nếu cổ phiếu tăng 3,59%, cần nhìn luôn giá tham chiếu và mức tăng tuyệt đối bằng đồng để biết phiên trước thị trường đang định giá ở đâu.',metric:null},
{id:'pmi',title:'PMI',aliases:['pmi','purchasing managers index'],definition:'PMI là chỉ số khảo sát nhà quản trị mua hàng về đơn hàng, sản lượng, việc làm, tồn kho và thời gian giao hàng.',formula:'Chỉ số khuếch tán từ khảo sát doanh nghiệp',read:'PMI trên 50 thường cho thấy hoạt động sản xuất mở rộng; dưới 50 cho thấy thu hẹp.',metric:null},
{id:'gdp',title:'GDP',aliases:['gdp','tong san pham trong nuoc'],definition:'GDP là tổng giá trị hàng hóa và dịch vụ cuối cùng được tạo ra trong nền kinh tế trong một giai đoạn.',formula:'Có thể tính theo sản xuất, chi tiêu hoặc thu nhập',read:'Tăng trưởng GDP phản ánh tốc độ mở rộng của nền kinh tế, nhưng ảnh hưởng lên từng ngành khác nhau.',metric:null},
{id:'m2',title:'Cung tiền M2',aliases:['m2','cung tien','money supply'],definition:'M2 là thước đo lượng tiền rộng trong nền kinh tế, gồm tiền mặt, tiền gửi thanh toán và nhiều loại tiền gửi có tính thanh khoản cao.',formula:'Tổng các thành phần tiền theo định nghĩa thống kê tiền tệ',read:'M2 tăng nhanh thường đi cùng điều kiện thanh khoản dồi dào hơn; cần đọc cùng tín dụng, lạm phát và lãi suất.',metric:null},
{id:'credit',title:'Tăng trưởng tín dụng',aliases:['tin dung','credit growth','du no tin dung'],definition:'Tăng trưởng tín dụng cho biết dư nợ cho vay của hệ thống tăng bao nhiêu so với mốc trước.',formula:'(Dư nợ hiện tại / Dư nợ mốc so sánh - 1) × 100%',read:'Tín dụng tăng hỗ trợ cầu và hoạt động kinh tế nhưng tốc độ quá nhanh có thể làm áp lực lạm phát và chất lượng tài sản tăng.',metric:null},
{id:'omo',title:'OMO',aliases:['omo','thi truong mo','open market operation'],definition:'OMO là nghiệp vụ Ngân hàng Nhà nước bơm hoặc hút thanh khoản ngắn hạn qua giao dịch giấy tờ có giá với các tổ chức tín dụng.',formula:'Theo khối lượng phát hành/đáo hạn và giao dịch từng ngày',read:'Bơm ròng thường giảm căng thanh khoản VND; hút ròng thường rút phần tiền dư. Tác động lên lãi suất liên ngân hàng còn phụ thuộc nhu cầu vay và trạng thái thanh khoản trước đó.',metric:null},
{id:'overnight',title:'Lãi suất qua đêm liên ngân hàng',aliases:['overnight','lai suat qua dem','lai suat on','on rate'],definition:'Lãi suất qua đêm là mức lãi các ngân hàng vay mượn VND với nhau trong thời hạn một ngày.',formula:'Lãi suất giao dịch bình quân theo dữ liệu liên ngân hàng',read:'ON tăng nhanh thường phản ánh nhu cầu VND ngắn hạn căng hơn; ON giảm cho thấy thanh khoản ngắn hạn bớt căng hoặc cầu vay giảm.',metric:null},
{id:'inflation',title:'Lạm phát / CPI',aliases:['lam phat','cpi','consumer price index'],definition:'CPI đo mức thay đổi giá của một rổ hàng hóa và dịch vụ tiêu dùng; tốc độ tăng CPI thường được dùng để theo dõi lạm phát.',formula:'(CPI kỳ này / CPI kỳ gốc - 1) × 100%',read:'Lạm phát tăng có thể làm chính sách tiền tệ thận trọng hơn và ảnh hưởng chi phí vốn, sức mua và biên lợi nhuận.',metric:null},
{id:'fdi',title:'FDI',aliases:['fdi','dau tu truc tiep nuoc ngoai'],definition:'FDI là vốn đầu tư trực tiếp từ nhà đầu tư nước ngoài vào dự án hoặc doanh nghiệp trong nước.',formula:'Theo vốn đăng ký, điều chỉnh và vốn thực hiện',read:'FDI thực hiện cho thấy lượng vốn thực sự được giải ngân; FDI đăng ký phản ánh quy mô cam kết và kỳ vọng đầu tư.',metric:null},
{id:'currentRatio',title:'Hệ số thanh toán hiện hành',aliases:['current ratio','thanh toan hien hanh','he so thanh toan hien hanh'],definition:'Hệ số thanh toán hiện hành cho biết quy mô tài sản ngắn hạn so với nợ ngắn hạn tại ngày báo cáo.',formula:'Tài sản ngắn hạn / Nợ ngắn hạn',read:'Trên 1 nghĩa là tài sản ngắn hạn lớn hơn nợ ngắn hạn; vẫn cần xem tài sản đó nằm ở tiền, phải thu hay tồn kho để đánh giá chất lượng thanh khoản.',metric:null},
{id:'assetTurnover',title:'Vòng quay tổng tài sản',aliases:['asset turnover','vong quay tai san','vong quay tong tai san'],definition:'Vòng quay tổng tài sản cho biết 1 đồng tài sản bình quân tạo ra bao nhiêu đồng doanh thu trong kỳ.',formula:'Doanh thu thuần / Tổng tài sản bình quân',read:'Vòng quay tăng cho thấy cùng một quy mô tài sản đang tạo ra nhiều doanh thu hơn. Khi chỉ số giảm, cần xem doanh nghiệp vừa đầu tư tài sản mới hay hiệu suất khai thác đang yếu đi.',metric:null},
{id:'inventoryTurnover',title:'Vòng quay hàng tồn kho',aliases:['inventory turnover','vong quay ton kho','vong quay hang ton kho'],definition:'Vòng quay tồn kho cho biết tồn kho được bán và thay thế bao nhiêu lần trong kỳ.',formula:'Giá vốn hàng bán / Tồn kho bình quân',read:'Vòng quay giảm kéo dài thường đi cùng tồn kho chậm luân chuyển; vòng quay tăng có thể phản ánh tiêu thụ tốt hơn hoặc mức tồn kho được tối ưu.',metric:null},
{id:'receivableTurnover',title:'Vòng quay khoản phải thu',aliases:['receivable turnover','vong quay phai thu','vong quay khoan phai thu'],definition:'Vòng quay phải thu cho biết doanh nghiệp thu hồi các khoản bán chịu nhanh đến mức nào.',formula:'Doanh thu bán chịu / Phải thu bình quân',read:'Vòng quay tăng nghĩa là tiền về nhanh hơn; vòng quay giảm trong khi doanh thu tăng mạnh cần kiểm tra chính sách tín dụng và chất lượng khách hàng.',metric:null},
{id:'interestCoverage',title:'Khả năng thanh toán lãi vay',aliases:['interest coverage','interest coverage ratio','kha nang tra lai vay','bao phu lai vay'],definition:'Chỉ số này cho biết lợi nhuận hoạt động có thể trang trải chi phí lãi vay bao nhiêu lần.',formula:'EBIT / Chi phí lãi vay',read:'Mức càng cao thì vùng đệm trả lãi càng lớn. Khi xuống gần 1, lợi nhuận hoạt động chỉ vừa đủ trả lãi và rủi ro tài chính tăng mạnh.',metric:null},
{id:'operatingMargin',title:'Biên lợi nhuận hoạt động',aliases:['operating margin','bien loi nhuan hoat dong','bien ebit'],definition:'Biên lợi nhuận hoạt động cho biết 100 đồng doanh thu tạo ra bao nhiêu đồng lợi nhuận từ hoạt động trước chi phí tài chính và thuế.',formula:'Lợi nhuận hoạt động / Doanh thu thuần × 100%',read:'Biên tăng cho thấy hoạt động cốt lõi tạo lợi nhuận tốt hơn; biên giảm thường phản ánh giá vốn hoặc chi phí vận hành tăng nhanh hơn doanh thu.',metric:null},
{id:'ebit',title:'EBIT',aliases:['ebit','earnings before interest and taxes'],definition:'EBIT là lợi nhuận trước lãi vay và thuế, dùng để nhìn kết quả hoạt động trước ảnh hưởng của cấu trúc vay nợ và thuế.',formula:'Lợi nhuận trước thuế + Chi phí lãi vay',read:'EBIT tăng cùng doanh thu cho thấy hoạt động chính đang mở rộng; nếu EBIT tăng nhưng OCF yếu, cần kiểm tra vốn lưu động.',metric:null},
{id:'nopat',title:'NOPAT',aliases:['nopat','net operating profit after tax'],definition:'NOPAT là lợi nhuận hoạt động sau thuế giả định doanh nghiệp không chịu ảnh hưởng của cấu trúc vay nợ.',formula:'EBIT × (1 - Thuế suất)',read:'NOPAT thường được dùng cùng vốn đầu tư để tính ROIC và đánh giá khả năng tạo giá trị từ hoạt động cốt lõi.',metric:null},
{id:'ev',title:'Enterprise Value (EV)',aliases:['enterprise value','ev','gia tri doanh nghiep'],definition:'EV ước tính giá trị toàn bộ hoạt động doanh nghiệp thuộc cả cổ đông và chủ nợ.',formula:'Vốn hóa + Nợ vay - Tiền và tương đương tiền',read:'EV phù hợp khi so các doanh nghiệp có cấu trúc nợ khác nhau vì nó cộng phần vốn của chủ nợ vào giá trị thị trường của cổ đông.',metric:null},
{id:'evEbitda',title:'EV/EBITDA',aliases:['ev ebitda','ev/ebitda'],definition:'EV/EBITDA cho biết thị trường định giá toàn bộ doanh nghiệp gấp bao nhiêu lần EBITDA một năm.',formula:'Enterprise Value / EBITDA',read:'Chỉ số thấp hơn doanh nghiệp cùng ngành có thể phản ánh định giá thấp hơn, nhưng cần đọc cùng tăng trưởng, CAPEX, chất lượng dòng tiền và chu kỳ ngành.',metric:null},
{id:'peg',title:'PEG',aliases:['peg','price earnings growth'],definition:'PEG điều chỉnh P/E theo tốc độ tăng trưởng lợi nhuận để đặt mức định giá cạnh tốc độ tăng trưởng.',formula:'P/E / Tốc độ tăng trưởng EPS',read:'PEG quanh 1 thường được dùng như một mốc tham khảo; không nên dùng nếu lợi nhuận biến động mạnh hoặc tăng trưởng ngắn hạn bất thường.',metric:null},
{id:'dividendYield',title:'Tỷ suất cổ tức',aliases:['dividend yield','ty suat co tuc','loi suat co tuc'],definition:'Tỷ suất cổ tức cho biết tiền cổ tức tiền mặt một năm tương đương bao nhiêu phần trăm giá cổ phiếu.',formula:'Cổ tức tiền mặt mỗi cổ phiếu / Giá cổ phiếu × 100%',read:'Tỷ suất cao tạo dòng tiền cho cổ đông nhưng cần kiểm tra khả năng duy trì cổ tức từ lợi nhuận và FCF.',metric:null},
{id:'payoutRatio',title:'Tỷ lệ chi trả cổ tức',aliases:['payout ratio','ty le chi tra co tuc'],definition:'Tỷ lệ chi trả cổ tức cho biết doanh nghiệp dùng bao nhiêu phần trăm lợi nhuận để trả cổ tức.',formula:'Cổ tức / Lợi nhuận sau thuế thuộc cổ đông',read:'Tỷ lệ cao phù hợp với doanh nghiệp trưởng thành; tỷ lệ quá cao trong khi FCF yếu làm khả năng duy trì cổ tức kém bền hơn.',metric:null},
{id:'bvps',title:'BVPS',aliases:['bvps','book value per share','gia tri so sach moi co phieu'],definition:'BVPS là phần vốn chủ sở hữu thuộc về mỗi cổ phiếu đang lưu hành.',formula:'Vốn chủ sở hữu thuộc cổ đông / Số cổ phiếu lưu hành',read:'BVPS tăng cho thấy giá trị sổ sách trên mỗi cổ phần tăng; với ngân hàng, BVPS thường được đọc cùng P/B và ROE.',metric:null},
{id:'marketCap',title:'Vốn hóa thị trường',aliases:['market cap','market capitalization','von hoa','von hoa thi truong'],definition:'Vốn hóa là giá trị thị trường của toàn bộ cổ phiếu đang lưu hành tại mức giá hiện tại.',formula:'Giá cổ phiếu × Số cổ phiếu đang lưu hành',read:'Vốn hóa phản ánh quy mô thị trường của phần vốn cổ đông, khác với EV vì chưa cộng nợ vay và chưa trừ tiền mặt.',metric:null},
{id:'freeFloat',title:'Free float',aliases:['free float','co phieu tu do chuyen nhuong'],definition:'Free float là phần cổ phiếu có khả năng giao dịch tự do trên thị trường, không nằm trong các khoản nắm giữ bị hạn chế hoặc mang tính chiến lược dài hạn.',formula:'Cổ phiếu tự do chuyển nhượng / Tổng cổ phiếu lưu hành',read:'Free float thấp có thể làm thanh khoản mỏng và giá nhạy hơn với lệnh lớn.',metric:null},
{id:'beta',title:'Beta',aliases:['beta','he so beta'],definition:'Beta đo mức độ lợi suất cổ phiếu thường biến động cùng thị trường.',formula:'Cov(lợi suất cổ phiếu, lợi suất thị trường) / Var(lợi suất thị trường)',read:'Beta lớn hơn 1 nghĩa là cổ phiếu thường dao động mạnh hơn thị trường; beta dưới 1 thường ổn định hơn trong cùng giai đoạn đo.',metric:null},
{id:'sharpe',title:'Sharpe ratio',aliases:['sharpe','sharpe ratio'],definition:'Sharpe ratio đo phần lợi suất vượt lãi suất phi rủi ro trên mỗi đơn vị biến động.',formula:'(Lợi suất danh mục - Lãi suất phi rủi ro) / Độ lệch chuẩn lợi suất',read:'Sharpe cao hơn nghĩa là mức lợi suất đạt được tốt hơn so với lượng biến động đã chấp nhận trong giai đoạn đo.',metric:null},
{id:'vwap',title:'VWAP',aliases:['vwap','volume weighted average price','gia trung binh theo khoi luong'],definition:'VWAP là giá giao dịch bình quân có trọng số theo khối lượng trong phiên hoặc khoảng thời gian.',formula:'Tổng (Giá × Khối lượng) / Tổng khối lượng',read:'Giá trên VWAP cho thấy phần lớn khối lượng đã giao dịch ở mức thấp hơn giá hiện tại; giá dưới VWAP cho thấy phần lớn khối lượng đã giao dịch ở mức cao hơn.',metric:null},
{id:'cci',title:'CCI',aliases:['cci','commodity channel index'],definition:'CCI đo độ lệch của giá điển hình so với mức trung bình trong một khoảng thời gian.',formula:'(Typical Price - SMA của Typical Price) / (0,015 × Mean Deviation)',read:'CCI trên +100 cho thấy giá đang mạnh hơn rõ rệt so với nền gần đây; dưới -100 cho thấy trạng thái yếu mạnh theo chiều ngược lại.',metric:null},
{id:'roc',title:'ROC',aliases:['roc','rate of change'],definition:'ROC đo phần trăm thay đổi của giá so với N nến trước.',formula:'(Giá hiện tại / Giá N nến trước - 1) × 100%',read:'ROC dương và tăng cho thấy xung lực tăng mạnh dần; ROC âm cho thấy giá thấp hơn mốc N nến trước.',metric:null},
{id:'willr',title:'Williams %R',aliases:['williams %r','williams r','willr'],definition:'Williams %R đo vị trí giá đóng cửa trong biên cao-thấp của N nến, trên thang từ -100 đến 0.',formula:'-100 × (Highest High - Close) / (Highest High - Lowest Low)',read:'Gần 0 nghĩa là giá nằm sát vùng cao của biên; gần -100 nghĩa là giá nằm sát vùng thấp của biên.',metric:null},
{id:'supportResistance',title:'Hỗ trợ và kháng cự',aliases:['ho tro khang cu','support resistance','support','resistance'],definition:'Hỗ trợ là vùng giá nơi lực mua từng đủ mạnh để chặn nhịp giảm; kháng cự là vùng giá nơi lực bán từng chặn nhịp tăng.',formula:'Xác định từ đỉnh/đáy trước, vùng tích lũy, đường trung bình và cụm khối lượng',read:'Vùng giá có nhiều lần phản ứng và khối lượng lớn thường đáng chú ý hơn một mức giá đơn lẻ.',metric:null},
{id:'breakout',title:'Breakout',aliases:['breakout','pha vo','vuot khang cu'],definition:'Breakout là khi giá vượt ra khỏi một vùng tích lũy hoặc kháng cự quan trọng.',formula:'Giá đóng cửa vượt vùng cản; thường đọc cùng khối lượng và độ rộng biên',read:'Breakout đi kèm khối lượng cao và giữ được trên vùng vừa vượt có chất lượng tốt hơn một cú xuyên cản ngắn rồi quay lại.',metric:null},
{id:'gap',title:'Gap giá',aliases:['gap','khoang trong gia','gap up','gap down'],definition:'Gap là khoảng trống giữa vùng giá của hai phiên hoặc hai nến liên tiếp khi không có giao dịch ở khoảng giá nằm giữa.',formula:'So biên cao-thấp của hai nến liên tiếp',read:'Gap cho thấy thay đổi nhanh trong kỳ vọng; mức ý nghĩa phụ thuộc vị trí xu hướng, khối lượng và việc gap có bị lấp sau đó hay không.',metric:null},
{id:'nim',title:'NIM',aliases:['nim','net interest margin','bien lai rong'],definition:'NIM cho biết ngân hàng tạo được bao nhiêu thu nhập lãi ròng trên mỗi đồng tài sản sinh lãi bình quân.',formula:'Thu nhập lãi thuần / Tài sản sinh lãi bình quân × 100%',read:'NIM tăng thường hỗ trợ lợi nhuận ngân hàng; cần đọc cùng chi phí vốn, chất lượng tín dụng và tỷ lệ nợ xấu.',metric:null},
{id:'npl',title:'Nợ xấu / NPL',aliases:['npl','no xau','non performing loan'],definition:'NPL là tỷ lệ các khoản vay thuộc nhóm nợ xấu trên tổng dư nợ cho vay.',formula:'Nợ nhóm 3-5 / Tổng dư nợ × 100%',read:'NPL tăng cho thấy chất lượng tín dụng xấu đi và có thể kéo chi phí dự phòng lên.',metric:null},
{id:'casa',title:'CASA',aliases:['casa','current account savings account','tien gui khong ky han'],definition:'CASA là tỷ trọng tiền gửi không kỳ hạn trong tổng tiền gửi khách hàng của ngân hàng.',formula:'Tiền gửi không kỳ hạn / Tổng tiền gửi khách hàng × 100%',read:'CASA cao giúp ngân hàng có nguồn vốn chi phí thấp hơn, qua đó hỗ trợ NIM nếu các yếu tố khác không đổi.',metric:null},
{id:'cir',title:'CIR / Cost-to-Income',aliases:['cir','cost to income','cost income ratio','chi phi tren thu nhap'],definition:'CIR đo chi phí hoạt động cần bỏ ra để tạo một đồng tổng thu nhập hoạt động của ngân hàng.',formula:'Chi phí hoạt động / Tổng thu nhập hoạt động × 100%',read:'CIR giảm thường phản ánh hiệu quả vận hành cải thiện. Cần tách tác động từ tăng thu nhập, tiết giảm chi phí và các khoản thu bất thường.' ,metric:null},
{id:'ldr',title:'LDR / Loan-to-Deposit',aliases:['ldr','loan to deposit','du no tren tien gui','cho vay tren tien gui'],definition:'LDR so dư nợ cho vay với tiền gửi khách hàng, giúp đánh giá mức độ sử dụng nguồn vốn huy động cho tín dụng.',formula:'Dư nợ cho vay khách hàng / Tiền gửi khách hàng × 100%',read:'LDR cao có thể hỗ trợ hiệu quả sử dụng vốn nhưng làm bộ đệm thanh khoản mỏng hơn. Cần đọc cùng CASA, tăng trưởng huy động, thanh khoản liên ngân hàng và quy định áp dụng.' ,metric:null},
{id:'llr',title:'Bao phủ nợ xấu / LLR',aliases:['llr','loan loss reserve coverage','bao phu no xau','ty le bao phu no xau'],definition:'Tỷ lệ bao phủ nợ xấu so dự phòng rủi ro tín dụng với quy mô nợ xấu, phản ánh bộ đệm dự phòng hiện có.',formula:'Dự phòng rủi ro tín dụng / Nợ xấu × 100%',read:'Tỷ lệ cao tạo bộ đệm tốt hơn trước tổn thất tín dụng, nhưng xu hướng cần đọc cùng NPL, nợ nhóm 2, chi phí tín dụng và tốc độ xử lý nợ.' ,metric:null},
{id:'car',title:'CAR / Tỷ lệ an toàn vốn',aliases:['car','capital adequacy ratio','an toan von','ty le an toan von'],definition:'CAR đo quy mô vốn tự có so với tài sản có rủi ro, phản ánh khả năng hấp thụ tổn thất và dư địa tăng trưởng tài sản.',formula:'Vốn tự có / Tài sản có rủi ro × 100%',read:'CAR cao hơn ngưỡng yêu cầu tạo dư địa tăng trưởng và bộ đệm rủi ro tốt hơn; cần chú ý chất lượng cấu phần vốn và tốc độ tăng tài sản có rủi ro.' ,metric:null},
{id:'creditCost',title:'Credit cost / Chi phí tín dụng',aliases:['credit cost','chi phi tin dung','chi phi du phong tren du no'],definition:'Credit cost đo chi phí dự phòng tín dụng ghi nhận trong kỳ so với quy mô dư nợ bình quân.',formula:'Chi phí dự phòng tín dụng / Dư nợ cho vay bình quân × 100%',read:'Credit cost tăng thường làm giảm lợi nhuận ngắn hạn nhưng có thể phản ánh ngân hàng chủ động tăng bộ đệm. Cần đọc cùng NPL, nợ nhóm 2 và LLR.' ,metric:null},
{id:'costOfFunds',title:'Cost of funds / Chi phí vốn',aliases:['cost of funds','cost of fund','chi phi von','gia von huy dong'],definition:'Cost of funds phản ánh mức chi phí lãi bình quân mà ngân hàng phải trả cho các nguồn vốn huy động.',formula:'Chi phí lãi / Nguồn vốn chịu lãi bình quân × 100%',read:'Chi phí vốn giảm, nếu lợi suất tài sản không giảm tương ứng, thường hỗ trợ NIM. CASA, cơ cấu kỳ hạn huy động và mặt bằng lãi suất là các động lực chính.' ,metric:null},
{id:'nii',title:'Thu nhập lãi thuần / NII',aliases:['nii','net interest income','thu nhap lai thuan'],definition:'NII là chênh lệch giữa thu nhập lãi từ tài sản sinh lãi và chi phí lãi của nguồn vốn trong kỳ.',formula:'Thu nhập lãi - Chi phí lãi',read:'NII tăng có thể đến từ tăng trưởng tín dụng, NIM cải thiện hoặc cả hai; cần tách hiệu ứng quy mô khỏi hiệu ứng biên.' ,metric:null},
{id:'toiBank',title:'Tổng thu nhập hoạt động / TOI',aliases:['toi','total operating income','tong thu nhap hoat dong'],definition:'TOI là tổng thu nhập hoạt động của ngân hàng trước chi phí hoạt động và dự phòng, thường gồm thu nhập lãi thuần và các nguồn ngoài lãi.',formula:'Thu nhập lãi thuần + Thu nhập ngoài lãi',read:'TOI tăng bền vững khi cả nguồn thu cốt lõi và thu ngoài lãi cùng cải thiện; cần loại các khoản bất thường khi đánh giá chất lượng tăng trưởng.' ,metric:null}
];
const byId=Object.fromEntries(C.map(x=>[x.id,x]));
function tokens(s){return norm(s).split(' ').filter(x=>x.length>1);}
function edit(a,b){a=norm(a);b=norm(b);if(a===b)return 0;if(!a)return b.length;if(!b)return a.length;const prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let left=i,diag=i-1;prev[0]=i;for(let j=1;j<=b.length;j++){const up=prev[j],next=Math.min(up+1,left+1,diag+(a[i-1]===b[j-1]?0:1));diag=up;prev[j]=next;left=next;}}return prev[b.length];}
function scoreConcept(q,c){
 const s=norm(q),qt=tokens(s);let score=0;
 const bounded=(phrase)=>(' '+s+' ').includes(' '+phrase+' ');
 for(const alias of [c.title,...(c.aliases||[])]){
  const n=norm(alias),at=tokens(n);if(!n)continue;
  // Vietnamese first-person 'tôi' is not the finance acronym TOI.
  if(n==='toi'&&!/\bTOI\b/.test(String(q)))continue;
  if(s===n){score=Math.max(score,40);continue;}
  // A label is evidence only when its entire phrase appears on token boundaries.
  // Never match a short acronym by edit distance: "tai"/"toi" must stay distinct.
  if(bounded(n)){score=Math.max(score,30+Math.min(8,at.length*2));continue;}
  const overlap=at.filter(t=>qt.includes(t)).length;
  if(at.length>=2&&overlap===at.length){
   score=Math.max(score,16+Math.min(8,at.length*2));continue;
  }
  if(at.length>=2&&at.every(t=>qt.some(w=>w===t||(t.length>=5&&w.length>=5&&edit(w,t)===1)))){
   score=Math.max(score,15+Math.min(6,at.length));continue;
  }
  // Whole-word typo only, never fuzzy-match 2–3 character acronyms.
  if(at.length===1&&at[0].length>=5&&qt.length===1&&edit(qt[0],at[0])===1)
   score=Math.max(score,15);
 }
 return score;
}
function search(question,limit=5){return C.map(c=>({c,score:scoreConcept(question,c)})).filter(x=>x.score>=3).sort((a,b)=>b.score-a.score||a.c.title.localeCompare(b.c.title,'vi')).slice(0,limit);}
function find(question){const ranked=search(question,1);return ranked[0]?.score>=15?ranked[0].c:null;}
function explainLabel(label){const s=norm(label);
 if(/doanh thu|thu nhap ban hang/.test(s))return'Doanh thu là giá trị doanh nghiệp ghi nhận từ hàng hóa hoặc dịch vụ đã cung cấp trong kỳ, trước khi trừ các nhóm chi phí.';
 if(/gia von/.test(s))return'Giá vốn là chi phí trực tiếp gắn với hàng hóa hoặc dịch vụ đã tạo ra doanh thu trong kỳ.';
 if(/loi nhuan gop/.test(s))return'Lợi nhuận gộp là phần doanh thu còn lại sau khi trừ giá vốn, trước chi phí bán hàng, quản lý, tài chính và thuế.';
 if(/loi nhuan/.test(s))return'Lợi nhuận cho biết phần giá trị còn lại sau các nhóm chi phí tương ứng trong kỳ; cần đọc cùng dòng tiền để kiểm tra mức độ chuyển thành tiền thực.';
 if(/khau hao|hao mon/.test(s))return'Khấu hao phân bổ nguyên giá tài sản cố định vào chi phí qua thời gian sử dụng; đây là chi phí kế toán nhưng không phải khoản chi tiền mới trong kỳ.';
 if(/du phong/.test(s))return'Dự phòng là khoản doanh nghiệp ghi nhận trước cho tổn thất hoặc nghĩa vụ có khả năng phát sinh, làm giảm lợi nhuận hiện tại để phản ánh rủi ro tốt hơn.';
 if(/thue thu nhap hoan lai|thue hoan lai/.test(s))return'Thuế thu nhập hoãn lại phát sinh khi thời điểm ghi nhận doanh thu, chi phí hoặc giá trị tài sản theo kế toán khác với thời điểm tính thuế.';
 if(/loi the thuong mai|goodwill/.test(s))return'Lợi thế thương mại là phần giá mua một doanh nghiệp cao hơn giá trị hợp lý của tài sản thuần nhận được khi mua lại.';
 if(/tai san co dinh/.test(s))return'Tài sản cố định là nhà xưởng, máy móc, thiết bị và tài sản dài hạn được dùng trong nhiều kỳ kinh doanh.';
 if(/tai san ngan han/.test(s))return'Tài sản ngắn hạn là các nguồn lực dự kiến chuyển thành tiền, bán hoặc sử dụng trong chu kỳ kinh doanh ngắn, thường gồm tiền, phải thu và tồn kho.';
 if(/tai san/.test(s))return'Tài sản là các nguồn lực kinh tế doanh nghiệp đang kiểm soát và kỳ vọng tạo lợi ích trong tương lai.';
 if(/no ngan han/.test(s))return'Nợ ngắn hạn là các nghĩa vụ phải thanh toán trong chu kỳ kinh doanh ngắn hoặc trong khoảng một năm.';
 if(/no phai tra|no vay/.test(s))return'Nợ phản ánh nghĩa vụ doanh nghiệp phải thanh toán cho ngân hàng, nhà cung cấp, trái chủ hoặc các bên khác.';
 if(/von dieu le|von gop/.test(s))return'Vốn góp là phần vốn cổ đông đã góp vào doanh nghiệp theo giá trị ghi nhận kế toán.';
 if(/loi nhuan sau thue chua phan phoi|loi nhuan giu lai/.test(s))return'Lợi nhuận giữ lại là phần lợi nhuận sau thuế tích lũy chưa được chia hết cho cổ đông và đang được giữ lại trong doanh nghiệp.';
 if(/von chu/.test(s))return'Vốn chủ sở hữu là phần giá trị thuộc cổ đông sau khi lấy tổng tài sản trừ toàn bộ nợ phải trả.';
 if(/tien va tuong duong tien/.test(s))return'Tiền và tương đương tiền là nguồn thanh khoản có thể sử dụng gần như ngay lập tức để thanh toán hoặc đầu tư.';
 if(/phai thu/.test(s))return'Khoản phải thu là tiền khách hàng hoặc đối tác còn phải thanh toán cho doanh nghiệp; tăng nhanh hơn doanh thu làm dòng tiền bị giữ lại lâu hơn.';
 if(/hang ton kho|ton kho/.test(s))return'Hàng tồn kho là nguyên vật liệu, sản phẩm dở dang và hàng hóa chưa bán; cần đọc tốc độ tăng cùng doanh thu và vòng quay tồn kho.';
 if(/tien gui khach hang/.test(s))return'Tiền gửi khách hàng là nguồn vốn ngân hàng nhận từ khách hàng và là một cấu phần chính của nguồn vốn huy động.';
 if(/cho vay khach hang|du no/.test(s))return'Cho vay khách hàng là dư nợ tín dụng ngân hàng đã cấp cho khách hàng; quy mô tăng cần đọc cùng NIM, nợ xấu và dự phòng.';
 if(/thu nhap lai thuan/.test(s))return'Thu nhập lãi thuần là phần chênh giữa thu nhập lãi từ tài sản sinh lãi và chi phí lãi trả cho nguồn vốn.';
 if(/chi phi.*thu nhap|cir/.test(s))return'CIR đo chi phí hoạt động trên tổng thu nhập hoạt động; tỷ lệ giảm thường phản ánh hiệu quả vận hành tốt hơn.';
 if(/du no.*tien gui|ldr|loan to deposit/.test(s))return'LDR so dư nợ cho vay với tiền gửi khách hàng; mức cao hơn cần được đọc cùng thanh khoản, CASA và tăng trưởng huy động.';
 if(/bao phu no xau|llr/.test(s))return'Tỷ lệ bao phủ nợ xấu so dự phòng rủi ro với nợ xấu, phản ánh bộ đệm dự phòng trước tổn thất tín dụng.';
 if(/an toan von|capital adequacy|car/.test(s))return'CAR đo vốn tự có so với tài sản có rủi ro, phản ánh bộ đệm vốn và dư địa tăng trưởng.';
 if(/chi phi tin dung|credit cost/.test(s))return'Credit cost đo chi phí dự phòng tín dụng so với dư nợ bình quân; cần đọc cùng NPL, nợ nhóm 2 và mức bao phủ.';
 if(/chi phi von|cost of funds?/.test(s))return'Chi phí vốn phản ánh lãi suất bình quân ngân hàng phải trả cho các nguồn vốn chịu lãi; CASA và mặt bằng lãi suất là các động lực chính.';
 if(/dong tien|luu chuyen tien/.test(s))return'Dòng tiền ghi nhận tiền thực thu và thực chi trong kỳ, khác với lợi nhuận kế toán vốn có thể bao gồm doanh thu hoặc chi phí chưa thu/chi tiền.';
 if(/chi phi lai vay|lai vay/.test(s))return'Chi phí lãi vay là khoản doanh nghiệp trả cho vốn vay; khi tăng nhanh hơn EBIT, vùng đệm trả lãi thu hẹp.';
 if(/chi phi/.test(s))return'Chi phí là nguồn lực doanh nghiệp đã sử dụng để tạo doanh thu, vận hành hoạt động hoặc tài trợ vốn trong kỳ.';
 if(/co phieu luu hanh/.test(s))return'Cổ phiếu lưu hành là số cổ phiếu thực tế đang thuộc sở hữu nhà đầu tư, dùng làm mẫu số cho EPS và nhiều chỉ tiêu trên mỗi cổ phần.';
 if(/tang truong/.test(s))return'Tăng trưởng đo tốc độ thay đổi của một chỉ tiêu so với mốc trước hoặc cùng kỳ.';
 if(/ty suat|ty so|bien|vong quay/.test(s))return'Đây là tỷ lệ so sánh hai đại lượng để đo hiệu quả, khả năng thanh toán, tốc độ luân chuyển hoặc cấu trúc tài chính qua thời gian.';
 return'Đây là một khoản mục trong dữ liệu FinQuery. Giá trị của nó cần được đọc theo xu hướng nhiều kỳ, tỷ trọng trong báo cáo và quan hệ với dòng tiền hoặc lợi nhuận liên quan.';}
window.FinQueryKnowledge={concepts:C,byId,find,search,scoreConcept,explainLabel,norm};
})();