(function(){'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const BASE=document.documentElement.dataset.hosting==='pages'?new URL('market/',location.href).href:'https://raw.githubusercontent.com/NCKHtop1/vmews-risk-analytics/financial-market-data/market/';
const fmt=n=>Number.isFinite(n)?new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(n):'—';
const date=s=>s&&Number.isFinite(Date.parse(s))?new Date(s).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',dateStyle:'short',timeStyle:'short'}):'chưa xác định';
const safeURL=u=>{try{const p=new URL(u);return p.protocol==='https:'&&!p.username&&!p.password&&['vnexpress.net','baodautu.vn','vietnamnet.vn','cafef.vn','vneconomy.vn'].some(h=>p.hostname===h||p.hostname.endsWith('.'+h))?p.href:'';}catch{return '';}};
let watch=[];try{const v=JSON.parse(localStorage.getItem('finquery-watchlist')||'[]');if(Array.isArray(v))watch=v.filter(s=>/^[A-Z]{3}$/.test(s));}catch{}

const state={symbol:'',companies:[],quotes:{},drivers:{symbols:{}},news:null,bars:[],sourceBars:[],interval:'day',chartType:'candles',history:null,count:120,end:0,request:0,watchOnly:false,sort:'symbol',newsMode:'company',driverOpen:'',refreshing:false,initialized:false};
const companyLogoUrl=symbol=>'https://storage.googleapis.com/cdn-entrade/company/'+encodeURIComponent(symbol);
const companyLogoFallback=symbol=>'https://cdn.simplize.vn/simplizevn/logo/'+encodeURIComponent(symbol)+'.jpeg';
const companyLogoFallback2=symbol=>'https://companiesmarketcap.com/img/company-logos/64/'+encodeURIComponent(symbol)+'.VN.png';
function placeholderLogo(symbol){const label=String(symbol||'VN').slice(0,3).toUpperCase(),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#eef6ff"/><stop offset="1" stop-color="#e8e8ff"/></linearGradient></defs><rect width="64" height="64" rx="17" fill="url(#g)"/><circle cx="49" cy="15" r="10" fill="#ffffff88"/><text x="32" y="39" text-anchor="middle" font-family="Arial,sans-serif" font-size="18" font-weight="700" fill="#315dcc">${label}</text></svg>`;return'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg);}
function logoHTML(symbol,name,size='sm'){return `<span class="ticker-logo ticker-logo-${size}"><img src="${companyLogoUrl(symbol)}" data-logo-stage="0" data-logo-alt="${companyLogoFallback(symbol)}" data-logo-alt2="${companyLogoFallback2(symbol)}" data-logo-placeholder="${placeholderLogo(symbol)}" alt="${esc(name||symbol)} logo" loading="lazy" decoding="async"><b>${esc(symbol)}</b></span>`;}
async function get(file){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),15000);try{const r=await fetch(BASE+file+'?v='+Math.floor(Date.now()/60000),{signal:ctl.signal,cache:'no-cache'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(t);}}
function old(s){return !s||!Number.isFinite(Date.parse(s))||Date.now()-Date.parse(s)>30*60*1000;}
function quoteTime(q){return q?.sourceTime?date(q.sourceTime)+(old(q.sourceTime)||q.status==='retained'?' · Bản gần nhất':''):q?'Nguồn chưa có giờ · Lấy '+date(q.collectedAt):'Chưa có';}
function showQuote(){const link=$('forecast-link');const url=new URL(link.href);url.searchParams.set('symbol',state.symbol);link.href=url.href;link.textContent='Xem dự báo '+state.symbol+' ↗';$('forecast-symbol').textContent=state.symbol;const nativeTitle=$('native-chart-title');if(nativeTitle)nativeTitle.textContent='Biểu đồ FinQuery · '+state.symbol;$('market-symbol').textContent=state.symbol;const q=state.quotes[state.symbol];$('watch-toggle').textContent=(watch.includes(state.symbol)?'★ Đang theo dõi':'☆ Theo dõi');$('watch-toggle').setAttribute('aria-pressed',String(watch.includes(state.symbol)));$('quote-price').textContent=q?fmt(q.price)+' đ':'Chưa có giá';$('quote-change').textContent=q?`${q.changePct>0?'+':''}${fmt(q.changePct)}%`:'—';$('quote-change').className=q?.changePct>0?'price-up':q?.changePct<0?'price-down':'price-flat';$('quote-time').textContent=q?`${q.source||'Vietcap'} · snapshot 15 phút · Lấy lúc ${date(q.collectedAt)}${q.sourceTime?' · Thời điểm nguồn '+date(q.sourceTime):' · Nguồn chưa xác định thời điểm khớp lệnh'}${old(q.sourceTime||q.collectedAt)||q.status==='retained'?' · Bản đã lưu':''}`:'Chưa tải được bảng giá. Bấm cập nhật để thử lại.';}
function factorTone(v){return v>8?'driver-positive':v<-8?'driver-negative':'driver-neutral';}
function driverSummary(d){if(!d)return'<span class="driver-missing">Đang tính…</span>';const top=d.factors?.[0];return `<button type="button" class="driver-button ${factorTone(d.score)}" data-driver="${esc(d.symbol)}" aria-expanded="${state.driverOpen===d.symbol}"><strong>${d.score>0?'+':''}${fmt(d.score)}</strong><span>${esc(top?.label||'Tín hiệu hỗn hợp')}</span></button>`;}
function driverDetail(d){if(!d)return'';const factors=(d.factors||[]).map(f=>`<div class="driver-factor"><span>${esc(f.label)} <small>trọng số ${Math.round((f.weight||0)*100)}%</small></span><b class="${factorTone(f.contribution)}">${f.contribution>0?'+':''}${fmt(f.contribution)}</b></div>`).join('');const metrics=[['Thị trường',Number.isFinite(d.marketMedianChangePct)?(d.marketMedianChangePct>0?'+':'')+fmt(d.marketMedianChangePct)+'%':'—'],['Sức mạnh tương đối',Number.isFinite(d.relativeStrengthPct)?(d.relativeStrengthPct>0?'+':'')+fmt(d.relativeStrengthPct)+'%':'—'],['KL / TB20',Number.isFinite(d.volumeRatio20)?fmt(d.volumeRatio20)+'x':'—'],['Động lượng 5P',Number.isFinite(d.momentum5dPct)?(d.momentum5dPct>0?'+':'')+fmt(d.momentum5dPct)+'%':'—'],['Biến động 20P',Number.isFinite(d.volatility20dPct)?fmt(d.volatility20dPct)+'%':'—']].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');const headlines=(d.headlines||[]).slice(0,3).map(h=>{const u=safeURL(h.url);return u?`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(h.title)} <small>${esc(h.source||'Nguồn')}</small></a>`:'';}).join('');return `<tr class="driver-row"><td colspan="8"><div class="driver-panel"><div class="driver-panel-head"><div><strong>Phân rã biến động · ${esc(d.symbol)}</strong><p>${esc(d.summary||'')}</p></div><span>Mức xác nhận dữ liệu: ${esc(d.confidence||'—')} · ${fmt(d.confidenceScore)}/100</span></div><div class="driver-metrics">${metrics}</div><div class="driver-factors">${factors}</div>${headlines?`<div class="driver-headlines"><span>Tin liên quan gần nhất</span>${headlines}</div>`:''}</div></td></tr>`;}
function board(){let list=state.companies.filter(c=>(!state.watchOnly||watch.includes(c.symbol))&&(`${c.symbol} ${c.name}`).toLocaleLowerCase('vi').includes($('market-filter').value.toLocaleLowerCase('vi')));list.sort((a,b)=>state.sort==='change'?(state.quotes[b.symbol]?.changePct??-Infinity)-(state.quotes[a.symbol]?.changePct??-Infinity):a.symbol.localeCompare(b.symbol));$('market-count').textContent=`${list.length} / ${state.companies.length} mã`;$('market-rows').innerHTML=list.map(c=>{const q=state.quotes[c.symbol],d=state.drivers?.symbols?.[c.symbol],delta=Number.isFinite(q?.price)&&Number.isFinite(q?.reference)?q.price-q.reference:null,deltaText=Number.isFinite(delta)?`${delta>0?'+':''}${fmt(delta)} đ · ${q.changePct>0?'+':''}${fmt(q.changePct)}%`:'—';const main=`<tr${c.symbol===state.symbol?' class="selected"':''}><td><button class="star-button" data-watch="${c.symbol}" aria-label="${watch.includes(c.symbol)?'Bỏ theo dõi':'Theo dõi'} ${c.symbol}" aria-pressed="${watch.includes(c.symbol)}">${watch.includes(c.symbol)?'★':'☆'}</button></td><th><button class="ticker-link ticker-with-logo" data-market-symbol="${c.symbol}" title="${esc(c.name)}">${logoHTML(c.symbol,c.name)}<span>${c.symbol}</span></button></th><td><strong>${fmt(q?.price)}</strong></td><td>${fmt(q?.reference)}</td><td class="${q?.changePct>0?'price-up':q?.changePct<0?'price-down':'price-flat'}">${deltaText}</td><td>${fmt(q?.volume)}</td><td>${driverSummary(d)}</td><td>${quoteTime(q)}</td></tr>`;return main+(state.driverOpen===c.symbol?driverDetail(d):'');}).join('')||'<tr><td colspan="8">Chưa có mã phù hợp. Bấm ☆ để lưu doanh nghiệp quan tâm.</td></tr>';}
function toggleWatch(symbol){watch=watch.includes(symbol)?watch.filter(s=>s!==symbol):[...watch,symbol];try{localStorage.setItem('finquery-watchlist',JSON.stringify(watch));}catch{}showQuote();board();chartController.select(state.symbol,watch);}
const NEWS_LABELS={all:'Tin kinh tế mới nhất',finance:'Tài chính',market:'Thị trường',rates:'Lãi suất',stocks:'Chứng khoán',banking:'Ngân hàng',investment:'Đầu tư',macro:'Kinh tế vĩ mô'};
const COMPANY_NEWS_ALIASES={
 MBB:['MBB','MBBANK','MB BANK','NGÂN HÀNG QUÂN ĐỘI','NGÂN HÀNG TMCP QUÂN ĐỘI','MILITARY COMMERCIAL JOINT STOCK BANK','MB'],
 VCB:['VCB','VIETCOMBANK','NGÂN HÀNG NGOẠI THƯƠNG'],TCB:['TCB','TECHCOMBANK','NGÂN HÀNG KỸ THƯƠNG'],VPB:['VPB','VPBANK','VIỆT NAM THỊNH VƯỢNG'],CTG:['CTG','VIETINBANK','NGÂN HÀNG CÔNG THƯƠNG'],BID:['BID','BIDV','NGÂN HÀNG ĐẦU TƯ VÀ PHÁT TRIỂN'],HDB:['HDB','HDBANK'],STB:['STB','SACOMBANK'],ACB:['ACB','Á CHÂU'],FPT:['FPT','FPT CORPORATION','CÔNG TY CỔ PHẦN FPT'],VIC:['VIC','VINGROUP','TẬP ĐOÀN VINGROUP']
};
function normNewsText(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase();}
function exactToken(hay,token){const escaped=String(token).replace(/[.*+?^$\{\}()|[\]\\]/g,'\\$&');return new RegExp('(^|[^a-z0-9])'+escaped+'([^a-z0-9]|$)','i').test(hay);}
function companyAliases(symbol){const company=state.companies.find(x=>x.symbol===symbol),aliases=[symbol,...(COMPANY_NEWS_ALIASES[symbol]||[])];if(company?.name)aliases.push(company.name);return [...new Set(aliases.map(normNewsText).filter(x=>x.length>=2))];}
function companyNewsScore(item,symbol=state.symbol){const title=normNewsText(item?.title),summary=normNewsText(item?.summary),aliases=companyAliases(symbol);let score=(item?.symbols||[]).includes(symbol)?1:0;for(const alias of aliases){const short=alias.length<=3,bankShort=symbol==='MBB'&&alias==='mb';const titleHit=short?exactToken(title,alias):title.includes(alias),summaryHit=short?exactToken(summary,alias):summary.includes(alias);if(titleHit){if(bankShort&&!/ngan hang|lai suat|tin dung|tien gui|bank/.test(title))continue;score=Math.max(score,bankShort?7:9);}if(summaryHit)score=Math.max(score,short?5:6);}return score;}
function strictCompanyNews(items,symbol=state.symbol,limit=50){return(items||[]).map(item=>({item,score:companyNewsScore(item,symbol)})).filter(x=>x.score>=7).sort((a,b)=>b.score-a.score||Date.parse(b.item.publishedAt)-Date.parse(a.item.publishedAt)).slice(0,limit).map(x=>x.item);}
function sectorNews(items,symbol=state.symbol,limit=40){const direct=new Set(strictCompanyNews(items,symbol,100).map(x=>x.url||x.title));return(items||[]).filter(item=>!direct.has(item.url||item.title)&&(item.topics||inferredTopics(item)).some(t=>['market','stocks','rates','banking','macro','finance'].includes(t))).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,limit);}
function inferredTopics(r){const s=(r.title||'').toLocaleLowerCase('vi-VN'),t=[];if(/tài chính|trái phiếu|tỷ giá|bảo hiểm|ngân sách/.test(s))t.push('finance');if(/thị trường|giá vàng|giá dầu|hàng hóa|bất động sản/.test(s))t.push('market');if(/lãi suất|tiền gửi|cho vay|tín dụng/.test(s))t.push('rates');if(/chứng khoán|cổ phiếu|vn-?index|hose|hnx|upcom|phái sinh/.test(s))t.push('stocks');if(/ngân hàng|tín dụng|tiền gửi/.test(s))t.push('banking');if(/đầu tư|fdi|giải ngân|dự án|quỹ đầu tư/.test(s))t.push('investment');if(/gdp|cpi|lạm phát|kinh tế|xuất khẩu|nhập khẩu|tăng trưởng/.test(s))t.push('macro');return t;}
function news(){
 const data=state.news,items=data?.items||[];let rows;
 if(state.newsMode==='all')rows=items.slice();
 else if(state.newsMode==='company')rows=strictCompanyNews(items,state.symbol,50);
 else rows=items.filter(r=>{const topics=Array.isArray(r.topics)&&r.topics.length?r.topics:inferredTopics(r);return topics.includes(state.newsMode);});
 rows.sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt));
 $('news-title').textContent=state.newsMode==='company'?'Tin doanh nghiệp · '+state.symbol:(NEWS_LABELS[state.newsMode]||'Tin kinh tế mới nhất');
 $('news-status').textContent=data?'Kiểm tra '+date(data.checkedAt)+' · '+(data.sources||[]).filter(s=>s.status==='ok').length+'/'+(data.sources||[]).length+' nguồn phản hồi · '+rows.length+' bài phù hợp'+(data.status==='retained'?' · Đang dùng tin đã lưu':''):'Chưa tải được tin tức.';
 const limit=state.newsMode==='company'?50:80;
 $('news-list').innerHTML=rows.slice(0,limit).map(r=>{const url=safeURL(r.url);return url?'<article class="news-item"><p>'+(state.newsMode==='company'?'TIN DOANH NGHIỆP · ':'')+esc(r.source)+' <span>· '+esc(date(r.publishedAt))+'</span></p><a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(r.title)+' <span aria-hidden="true">↗</span></a></article>':'';}).join('')||(state.newsMode==='company'?'<p class="market-empty">Chưa có tin doanh nghiệp '+esc(state.symbol)+' đủ mức liên quan trong nguồn hiện tại. Có thể chọn “Ngân hàng”, “Thị trường” hoặc “Tin kinh tế” để xem bối cảnh ngành.</p>':'<p class="market-empty">Chưa tìm thấy tin phù hợp trong 30 ngày gần đây.</p>');
}
async function refresh(){if(state.refreshing)return;state.refreshing=true;$('market-refresh').disabled=true;$('market-refresh-status').textContent='Đang tải giá, hệ số và tin…';const previousNewsMax=Math.max(0,...(state.news?.items||[]).map(x=>Date.parse(x.publishedAt)||0)),results=await Promise.allSettled([get('quotes.json'),get('news.json'),get('drivers.json')]);if(results[0].status==='fulfilled'&&results[0].value.quotes){for(const [symbol,q]of Object.entries(results[0].value.quotes)){const old=state.quotes[symbol];if(!old?.sourceTime||!q.sourceTime||Date.parse(q.sourceTime)>=Date.parse(old.sourceTime))state.quotes[symbol]=q;}}if(results[1].status==='fulfilled'&&Array.isArray(results[1].value.items))state.news=results[1].value;if(results[2].status==='fulfilled'&&results[2].value.symbols)state.drivers=results[2].value;showQuote();board();news();const currentQuote=state.quotes[state.symbol];if(currentQuote)chartController.snapshot(currentQuote);if(state.initialized&&previousNewsMax){const fresh=(state.news?.items||[]).filter(x=>(Date.parse(x.publishedAt)||0)>previousNewsMax).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt));const relevant=strictCompanyNews(fresh,state.symbol,1)[0];if(relevant)chartController.noteNews(relevant);}state.initialized=true;window.FinQueryAI?.sync(state.symbol);$('market-refresh-status').textContent=results.some(r=>r.status==='rejected')?'Một phần dữ liệu chưa tải được; giữ bản gần nhất nếu có.':'Đã đồng bộ snapshot, tín hiệu và tin mới nhất.';state.refreshing=false;$('market-refresh').disabled=false;}
window.FinancialMarket={select(symbol,companies){state.companies=companies;state.symbol=symbol;showQuote();board();news();chartController.select(symbol,watch);window.FinQueryAI?.sync(symbol);},context(){const all=(state.news?.items||[]).slice().sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)),items=strictCompanyNews(all,state.symbol,15),marketNews=sectorNews(all,state.symbol,40);return{symbol:state.symbol,quote:state.quotes[state.symbol]||null,driver:state.drivers?.symbols?.[state.symbol]||null,market:{generatedAt:state.drivers?.generatedAt||null,medianChangePct:state.drivers?.marketMedianChangePct??null},technical:chartController?.technicalContext?.()||null,news:items,sectorNews:marketNews,marketNews};},newsScore:(item,symbol)=>companyNewsScore(item,symbol||state.symbol)};
$('watch-toggle').addEventListener('click',()=>toggleWatch(state.symbol));$('market-rows').addEventListener('error',e=>{const img=e.target;if(img.tagName!=='IMG'||!img.closest('.ticker-logo'))return;const stage=Number(img.dataset.logoStage||0);if(stage===0&&img.dataset.logoAlt){img.dataset.logoStage='1';img.src=img.dataset.logoAlt;return;}if(stage===1&&img.dataset.logoAlt2){img.dataset.logoStage='2';img.src=img.dataset.logoAlt2;return;}if(stage<=2&&img.dataset.logoPlaceholder){img.dataset.logoStage='3';img.src=img.dataset.logoPlaceholder;return;}img.hidden=true;},true);$('market-rows').addEventListener('click',e=>{const star=e.target.closest('[data-watch]'),ticker=e.target.closest('[data-market-symbol]'),driver=e.target.closest('[data-driver]');if(star)toggleWatch(star.dataset.watch);if(driver){state.driverOpen=state.driverOpen===driver.dataset.driver?'':driver.dataset.driver;board();return;}if(ticker){$('ticker').value=ticker.dataset.marketSymbol;$('company-form').requestSubmit();}});$('market-filter').addEventListener('input',board);$('watch-only').addEventListener('change',e=>{state.watchOnly=e.target.checked;board();});$('market-sort').addEventListener('change',e=>{state.sort=e.target.value;board();});$('market-refresh').addEventListener('click',()=>{refresh();if(state.symbol)chartController.load(true);});$('news-mode').addEventListener('change',e=>{state.newsMode=e.target.value;news();});
const chartController=window.FinChart.create(BASE,q=>{const previous=state.quotes[q.symbol];if(previous?.sourceTime&&Date.parse(previous.sourceTime)>Date.parse(q.sourceTime))return;state.quotes[q.symbol]={...previous,...q,changePct:Number.isFinite(q.changePct)?q.changePct:(q.reference||previous?.reference)>0?(q.price/(q.reference||previous.reference)-1)*100:null,unit:'VND',source:'WebSocket',status:'ok',collectedAt:new Date().toISOString()};showQuote();board();});
refresh();setInterval(()=>{if(!document.hidden)refresh();},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
})();
