(function(){'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const BASE=document.documentElement.dataset.hosting==='pages'?new URL('market/',location.href).href:'https://raw.githubusercontent.com/NCKHtop1/vmews-risk-analytics/financial-market-data/market/';
const fmt=n=>Number.isFinite(n)?new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(n):'—';
const date=s=>s&&Number.isFinite(Date.parse(s))?new Date(s).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',dateStyle:'short',timeStyle:'short'}):'chưa xác định';
const safeURL=u=>{try{const p=new URL(u);return p.protocol==='https:'&&!p.username&&!p.password&&['vnexpress.net','baodautu.vn','vietnamnet.vn','cafef.vn'].some(h=>p.hostname===h||p.hostname.endsWith('.'+h))?p.href:'';}catch{return '';}};
let watch=[];try{const v=JSON.parse(localStorage.getItem('finquery-watchlist')||'[]');if(Array.isArray(v))watch=v.filter(s=>/^[A-Z]{3}$/.test(s));}catch{}

const state={symbol:'',companies:[],quotes:{},news:null,bars:[],sourceBars:[],interval:'day',chartType:'candles',history:null,count:120,end:0,request:0,watchOnly:false,sort:'symbol',newsMode:'company',refreshing:false};
async function get(file){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),15000);try{const r=await fetch(BASE+file+'?v='+Math.floor(Date.now()/60000),{signal:ctl.signal,cache:'no-cache'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(t);}}
function old(s){return !s||!Number.isFinite(Date.parse(s))||Date.now()-Date.parse(s)>30*60*1000;}
function quoteTime(q){return q?.sourceTime?date(q.sourceTime)+(old(q.sourceTime)||q.status==='retained'?' · Bản gần nhất':''):q?'Nguồn chưa có giờ · Lấy '+date(q.collectedAt):'Chưa có';}
function showQuote(){const link=$('forecast-link');const url=new URL(link.href);url.searchParams.set('symbol',state.symbol);link.href=url.href;link.textContent='Xem dự báo '+state.symbol+' ↗';$('forecast-symbol').textContent=state.symbol;const q=state.quotes[state.symbol];$('market-symbol').textContent=state.symbol;$('watch-toggle').textContent=(watch.includes(state.symbol)?'★ Đang theo dõi':'☆ Theo dõi');$('watch-toggle').setAttribute('aria-pressed',String(watch.includes(state.symbol)));$('quote-price').textContent=q?fmt(q.price)+' đ':'Chưa có giá';$('quote-change').textContent=q?`${q.changePct>0?'+':''}${fmt(q.changePct)}%`:'—';$('quote-change').className=q?.changePct>0?'price-up':q?.changePct<0?'price-down':'price-flat';$('quote-time').textContent=q?`${q.source||'Vietcap'} · Lấy lúc ${date(q.collectedAt)}${q.sourceTime?' · Thời điểm nguồn '+date(q.sourceTime):' · Nguồn chưa xác định thời điểm khớp lệnh'}${old(q.sourceTime||q.collectedAt)||q.status==='retained'?' · Bản đã lưu':''}`:'Chưa tải được bảng giá. Bấm cập nhật để thử lại.';}
function board(){let list=state.companies.filter(c=>(!state.watchOnly||watch.includes(c.symbol))&&(`${c.symbol} ${c.name}`).toLocaleLowerCase('vi').includes($('market-filter').value.toLocaleLowerCase('vi')));list.sort((a,b)=>state.sort==='change'?(state.quotes[b.symbol]?.changePct??-Infinity)-(state.quotes[a.symbol]?.changePct??-Infinity):a.symbol.localeCompare(b.symbol));$('market-count').textContent=`${list.length} / ${state.companies.length} mã`;$('market-rows').innerHTML=list.map(c=>{const q=state.quotes[c.symbol];return `<tr${c.symbol===state.symbol?' class="selected"':''}><td><button class="star-button" data-watch="${c.symbol}" aria-label="${watch.includes(c.symbol)?'Bỏ theo dõi':'Theo dõi'} ${c.symbol}" aria-pressed="${watch.includes(c.symbol)}">${watch.includes(c.symbol)?'★':'☆'}</button></td><th><button class="ticker-link" data-market-symbol="${c.symbol}" title="${esc(c.name)}">${c.symbol}</button></th><td>${fmt(q?.price)}</td><td class="${q?.changePct>0?'price-up':q?.changePct<0?'price-down':'price-flat'}">${q?.changePct>0?'+':''}${fmt(q?.changePct)}${Number.isFinite(q?.changePct)?'%':''}</td><td>${fmt(q?.volume)}</td><td>${quoteTime(q)}</td></tr>`;}).join('')||'<tr><td colspan="6">Chưa có mã phù hợp. Bấm ☆ để lưu doanh nghiệp quan tâm.</td></tr>';}
function toggleWatch(symbol){watch=watch.includes(symbol)?watch.filter(s=>s!==symbol):[...watch,symbol];try{localStorage.setItem('finquery-watchlist',JSON.stringify(watch));$('watch-status').textContent='Danh sách được lưu trên trình duyệt này.';}catch{$('watch-status').textContent='Trình duyệt không cho lưu; danh sách chỉ giữ trong lần mở này.';}showQuote();board();chartController.select(state.symbol,watch);}
function news(){const data=state.news, rows=(data?.items||[]).filter(r=>state.newsMode==='all'||r.symbols?.includes(state.symbol)).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt));$('news-title').textContent=state.newsMode==='all'?'Tin kinh tế mới nhất':`Tin doanh nghiệp · ${state.symbol}`;$('news-status').textContent=data?`Kiểm tra ${date(data.checkedAt)} · ${(data.sources||[]).filter(s=>s.status==='ok').length}/${(data.sources||[]).length} nguồn phản hồi${data.status==='retained'?' · Đang dùng tin đã lưu':''}`:'Chưa tải được tin tức.';$('news-list').innerHTML=rows.slice(0,30).map(r=>{const url=safeURL(r.url);return url?`<article class="news-item"><p>${esc(r.source)} <span>· ${esc(date(r.publishedAt))}</span></p><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)} <span aria-hidden="true">↗</span></a></article>`:'';}).join('')||`<p class="market-empty">Chưa tìm thấy tin phù hợp trong 30 ngày gần đây. Chọn “Tin kinh tế” để xem những bài mới nhất từ các nguồn đang cập nhật.</p>`;}
async function refresh(){if(state.refreshing)return;state.refreshing=true;$('market-refresh').disabled=true;$('market-refresh-status').textContent='Đang tải giá và tin…';const results=await Promise.allSettled([get('quotes.json'),get('news.json')]);if(results[0].status==='fulfilled'&&results[0].value.quotes){for(const [symbol,q]of Object.entries(results[0].value.quotes)){const old=state.quotes[symbol];if(!old?.sourceTime||!q.sourceTime||Date.parse(q.sourceTime)>=Date.parse(old.sourceTime))state.quotes[symbol]=q;}}if(results[1].status==='fulfilled'&&Array.isArray(results[1].value.items))state.news=results[1].value;showQuote();board();news();$('market-refresh-status').textContent=results.some(r=>r.status==='rejected')?'Một phần dữ liệu chưa tải được; giữ bản gần nhất nếu có.':'Đã tải bản công bố gần nhất.';state.refreshing=false;$('market-refresh').disabled=false;}
window.FinancialMarket={select(symbol,companies){state.companies=companies;const changed=state.symbol!==symbol;state.symbol=symbol;showQuote();board();news();chartController.select(symbol,watch);}};
$('watch-toggle').addEventListener('click',()=>toggleWatch(state.symbol));$('market-rows').addEventListener('click',e=>{const star=e.target.closest('[data-watch]'),ticker=e.target.closest('[data-market-symbol]');if(star)toggleWatch(star.dataset.watch);if(ticker){$('ticker').value=ticker.dataset.marketSymbol;$('company-form').requestSubmit();}});$('market-filter').addEventListener('input',board);$('watch-only').addEventListener('change',e=>{state.watchOnly=e.target.checked;board();});$('market-sort').addEventListener('change',e=>{state.sort=e.target.value;board();});$('market-refresh').addEventListener('click',()=>{refresh();if(state.symbol)chartController.load(true);});$('news-mode').addEventListener('change',e=>{state.newsMode=e.target.value;news();});
const chartController=window.FinChart.create(BASE,q=>{const previous=state.quotes[q.symbol];if(previous?.sourceTime&&Date.parse(previous.sourceTime)>Date.parse(q.sourceTime))return;state.quotes[q.symbol]={...previous,...q,changePct:Number.isFinite(q.changePct)?q.changePct:(q.reference||previous?.reference)>0?(q.price/(q.reference||previous.reference)-1)*100:null,unit:'VND',source:'WebSocket',status:'ok',collectedAt:new Date().toISOString()};showQuote();board();});
refresh();
})();
