(function(){'use strict';
const $=id=>document.getElementById(id);
const ENDPOINT='https://vmews-risk-analytics-sojd.vercel.app/api/solution-ai';
const state={busy:false,messages:[],symbol:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const tokens=s=>[...new Set(norm(s).split(/\s+/).filter(x=>x.length>2&&!/^(cua|cho|voi|nay|kia|nhung|dang|theo|phan|tich|giup|tinh|hinh)$/.test(x)))];
const fmt=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(Number(n)):'—';
function safeMarkdown(text){let s=esc(text);s=s.replace(/^### (.+)$/gm,'<h4>$1</h4>').replace(/^## (.+)$/gm,'<h3>$1</h3>').replace(/^# (.+)$/gm,'<h3>$1</h3>');s=s.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');const lines=s.split('\n'),out=[];let list=false;for(const line of lines){if(/^[-•] /.test(line)){if(!list){out.push('<ul>');list=true;}out.push('<li>'+line.replace(/^[-•] /,'')+'</li>');}else{if(list){out.push('</ul>');list=false;}if(line.trim())out.push('<p>'+line+'</p>');} }if(list)out.push('</ul>');return out.join('');}
function add(role,text,meta=''){const box=$('research-ai-messages');if(!box)return;const article=document.createElement('article');article.className='research-ai-message '+role;article.innerHTML=`<strong>${role==='assistant'?'FinQuery AI':'Bạn'}</strong><div>${role==='assistant'?safeMarkdown(text):'<p>'+esc(text)+'</p>'}</div>${meta?'<small>'+esc(meta)+'</small>':''}`;box.append(article);box.scrollTop=box.scrollHeight;}
function rawFinancial(){try{return window.FinancialReportContext?.raw?.()||null;}catch{return null;}}
function financialEvidence(question){const raw=rawFinancial(),data=raw?.data;if(!data)return null;const qs=tokens(question),mentioned=[...String(question).matchAll(/20\d{2}(?:\s*[-/]?\s*Q[1-4])?/gi)].map(m=>m[0].toUpperCase().replace(/\s+/g,'').replace(/(20\d{2})[-/]?Q([1-4])/,'$1-Q$2'));const all=[...new Set((data.periods||data.years||[]).map(String))].sort();let periods=data.periodType==='quarter'?all.slice(-16):all;if(mentioned.length)periods=[...new Set([...periods,...all.filter(p=>mentioned.includes(p)||mentioned.includes(p.replace('-','')))])].sort();const priority=/tong cong tai san|tong tai san|no phai tra|von chu so huu|doanh thu thuan|thu nhap lai thuan|tong thu nhap hoat dong|loi nhuan.*sau thue|lai.*sau thue|luu chuyen.*kinh doanh|dong tien.*kinh doanh|eps|lai co ban tren co phieu|roe|roa|bien loi nhuan|no.*tai san|tang truong/;const sections=(data.sections||[]).map(section=>{const scored=(section.rows||[]).map(row=>{const n=norm(row.label),match=qs.reduce((a,t)=>a+(n.includes(t)?1:0),0),important=priority.test(n)?8:0;return{row,score:important+match*4};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,qs.length?35:24).map(x=>({id:x.row.id,label:x.row.label,unit:x.row.unit,values:Object.fromEntries(periods.filter(p=>p in (x.row.values||{})).map(p=>[p,x.row.values[p]]))}));return scored.length?{id:section.id,name:section.name,basis:section.basis||null,rows:scored}:null;}).filter(Boolean);return{symbol:raw.symbol,name:raw.name,mode:raw.mode,updatedAt:raw.updatedAt,availablePeriods:all,selectedPeriods:raw.selectedPeriods,sections};}
function localSummary(question,ctx){const m=ctx.marketSnapshot,d=ctx.movementDrivers,f=ctx.localFinancialData;const lines=[];if(m?.quote){const q=m.quote;lines.push(`**${ctx.symbol}** hiện ở ${fmt(q.price)} đồng, biến động ${Number(q.changePct)>=0?'+':''}${fmt(q.changePct)}% tại snapshot gần nhất.`);}if(d){lines.push(`Điểm động lực tổng ${d.score>0?'+':''}${fmt(d.score)}/100, độ tin cậy bằng chứng ${d.confidence} (${fmt(d.confidenceScore)}/100).`);for(const x of (d.factors||[]).slice(0,4))lines.push(`- ${x.label}: đóng góp ${x.contribution>0?'+':''}${fmt(x.contribution)}, trọng số ${Math.round((x.weight||0)*100)}%.`);if(d.news72hCount)lines.push(`Có ${d.news72hCount} tin gắn với mã trong 72 giờ gần đây; điểm tin ${d.newsScore>0?'+':''}${fmt(d.newsScore)}.`);}if(f?.sections?.length){const rows=f.sections.flatMap(s=>s.rows).slice(0,10);lines.push('**Dữ liệu BCTC liên quan:**');for(const r of rows){const last=Object.entries(r.values||{}).filter(([,v])=>v!==null&&v!==undefined).at(-1);if(last)lines.push(`- ${r.label}: ${fmt(last[1])} ${r.unit||''} (${last[0]}).`);}}if(!lines.length)lines.push('Chưa có đủ dữ liệu cục bộ để tổng hợp câu hỏi này.');lines.push('Máy chủ AI chưa phản hồi nên đây là bản tổng hợp cục bộ, chưa bổ sung suy luận từ mô hình ngôn ngữ.');return lines.join('\n');}
function buildContext(question){const market=window.FinancialMarket?.context?.()||{};const finance=financialEvidence(question);return{scope:'financial-report',symbol:market.symbol||finance?.symbol||state.symbol,company:finance?.name||null,generatedAt:new Date().toISOString(),marketSnapshot:{quote:market.quote||null,market:market.market||null},movementDrivers:market.driver||null,localFinancialData:finance,recentNews:(market.news||[]).slice(0,12).map(n=>({title:n.title,source:n.source,publishedAt:n.publishedAt,url:n.url,topics:n.topics||[]}))};}
async function ask(question){if(state.busy||!question.trim())return;state.busy=true;const send=$('research-ai-send'),status=$('research-ai-status');if(send)send.disabled=true;if(status)status.textContent='Đang phân tích dữ liệu và nguồn…';add('user',question);const ctx=buildContext(question),sources=(ctx.recentNews||[]).filter(x=>/^https?:\/\//.test(x.url||'')).slice(0,8).map(x=>({title:x.title,url:x.url,publisher:x.source,publishedAt:x.publishedAt}));try{const res=await fetch(ENDPOINT,{method:'POST',mode:'cors',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,context:ctx,history:state.messages.slice(-8),sources})});const body=await res.json().catch(()=>({}));if(!res.ok)throw Error(body.message||body.error||('HTTP '+res.status));const answer=String(body.answer||'').trim();if(!answer)throw Error('AI không trả nội dung');add('assistant',answer,`${body.provider||'AI'} · ${body.model||''}`);state.messages.push({role:'user',content:question},{role:'assistant',content:answer});if(status)status.textContent=`${body.provider||'AI'} · đã nối dữ liệu cục bộ`;}catch(e){const fallback=localSummary(question,ctx);add('assistant',fallback,'Fallback cục bộ · '+String(e.message||'AI chưa sẵn sàng'));state.messages.push({role:'user',content:question},{role:'assistant',content:fallback});if(status)status.textContent='AI máy chủ chưa sẵn sàng · đang dùng dữ liệu cục bộ';}finally{state.busy=false;if(send)send.disabled=false;}}
async function health(){const status=$('research-ai-status');try{const r=await fetch(ENDPOINT,{mode:'cors',cache:'no-store'}),d=await r.json();if(r.ok&&d.ready){status.textContent=`${d.provider} · ${d.model}`;}else status.textContent='AI máy chủ chưa cấu hình · có fallback cục bộ';}catch{if(status)status.textContent='Có fallback cục bộ';}}
function sync(symbol){state.symbol=symbol||'';const p=$('research-ai-context');if(p)p.textContent=`${state.symbol||'VN100'} · giá · hệ số biến động · BCTC · chỉ số · tin chính thống`;}
window.FinQueryAI={sync,ask};
const form=$('research-ai-form'),input=$('research-ai-question');form?.addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(q){input.value='';ask(q);}});document.querySelectorAll('[data-ai-prompt]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.aiPrompt||'';input.focus();form.requestSubmit();}));health();sync(window.FinancialMarket?.context?.().symbol||new URLSearchParams(location.search).get('symbol')||'MBB');
})();