/* Minimal dependency-free OOXML writer. Numeric cells stay numeric; no formulas or notes. */
(function(root){
'use strict';
const enc=new TextEncoder();
const xml=s=>String(s??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function col(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
const crcTable=Array.from({length:256},(_,i)=>{for(let k=0;k<8;k++)i=(i&1)?0xedb88320^(i>>>1):i>>>1;return i>>>0;});
function crc(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function header(size,vals){const out=new Uint8Array(size),d=new DataView(out.buffer);for(const [pos,val,width] of vals)width===2?d.setUint16(pos,val,true):d.setUint32(pos,val,true);return out;}
function zip(entries){const parts=[],central=[];let offset=0;for(const [name,text] of entries){const n=enc.encode(name),b=enc.encode(text),c=crc(b);const h=header(30,[[0,0x04034b50,4],[4,20,2],[6,0x800,2],[12,0x21,2],[14,c,4],[18,b.length,4],[22,b.length,4],[26,n.length,2]]);parts.push(h,n,b);central.push(header(46,[[0,0x02014b50,4],[4,20,2],[6,20,2],[8,0x800,2],[14,0x21,2],[16,c,4],[20,b.length,4],[24,b.length,4],[28,n.length,2],[42,offset,4]]),n);offset+=h.length+n.length+b.length;}
const cd=central.reduce((s,x)=>s+x.length,0);parts.push(...central,header(22,[[0,0x06054b50,4],[8,entries.length,2],[10,entries.length,2],[12,cd,4],[16,offset,4]]));const output=new Uint8Array(parts.reduce((s,p)=>s+p.length,0));let at=0;for(const p of parts){output.set(p,at);at+=p.length;}return output;}
const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
const styles=`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="${ns}"><numFmts count="2"><numFmt numFmtId="164" formatCode="#,##0.00;(#,##0.00);&quot;-&quot;"/><numFmt numFmtId="165" formatCode="#,##0;(#,##0);&quot;-&quot;"/></numFmts><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFEDEDED"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"><color rgb="FFDDDDDD"/></left><right style="thin"><color rgb="FFDDDDDD"/></right><top style="thin"><color rgb="FFDDDDDD"/></top><bottom style="thin"><color rgb="FFDDDDDD"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="7"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1"/><xf numFmtId="165" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1"/><xf numFmtId="164" fontId="1" fillId="0" borderId="1" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
function workbook(data,years,reportIds){
if(!years.length||!reportIds.length)throw Error('Chọn kỳ và báo cáo trước khi tải.');
const reports=data.sections.filter(s=>reportIds.includes(s.id));if(reports.length!==reportIds.length)throw Error('Loại báo cáo không hợp lệ.');
for(const s of reports)if(years.some(y=>!(s.periods||s.years).includes(y)))throw Error('Kỳ đã chọn chưa có đủ dữ liệu cho báo cáo này.');
const groups=[['BCTC',reports.filter(s=>!['ratios','derived_ratios','notes'].includes(s.id))],['Chi_so',reports.filter(s=>['ratios','derived_ratios'].includes(s.id))],['Thuyet_minh',reports.filter(s=>s.id==='notes')]].filter(([,s])=>s.length);
const sheets=groups.map(([name,sections])=>{const rows=[];const add=(values,style=0)=>{const idx=rows.length+1;rows.push(`<row r="${idx}" ht="${idx===1?28:idx===4?25:Math.max(22,Math.ceil(String(values[0]??'').length/78)*17)}" customHeight="1">${values.map((v,c)=>{const st=Array.isArray(style)?style[c]:style;return v==null?`<c r="${col(c)}${idx}" s="${st}"/>`:typeof v==='number'&&Number.isFinite(v)?`<c r="${col(c)}${idx}" s="${st}"><v>${v}</v></c>`:`<c r="${col(c)}${idx}" s="${st}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`;}).join('')}</row>`);};
add([`${data.symbol} - ${data.name||data.symbol}`],1);add([name==='Chi_so'?'CHỈ SỐ TÀI CHÍNH':'Đơn vị: triệu đồng']);add([]);add(['CHỈ TIÊU',...years.map(p=>String(p).includes('-Q')?'Q'+String(p).at(-1)+'/'+String(p).slice(0,4):p)],2);
for(const section of sections){add([section.name.toUpperCase(),...years.map(()=>null)],2);for(const row of section.rows){let label=row.label;if(row.unit&&row.unit!=='triệu đồng'&&!label.toLowerCase().includes(row.unit.toLowerCase()))label+=` (${row.unit})`;add([label,...years.map(y=>row.values[String(y)]??null)],[row.bold?2:3,...years.map(()=>['đồng/cp','cổ phiếu'].includes(row.unit)?5:row.bold?6:4)]);}}
return [name,`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${ns}"><sheetViews><sheetView showGridLines="0" workbookViewId="0"><pane xSplit="1" ySplit="4" topLeftCell="B5" activePane="bottomRight" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="22"/><cols><col min="1" max="1" width="82" customWidth="1"/><col min="2" max="${years.length+1}" width="20" customWidth="1"/></cols><sheetData>${rows.join('')}</sheetData><mergeCells count="2"><mergeCell ref="A1:${col(years.length)}1"/><mergeCell ref="A2:${col(years.length)}2"/></mergeCells><pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>`];});
return zip([
['[Content_Types].xml',`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`],
['_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],
['xl/workbook.xml',`<?xml version="1.0"?><workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map(([n],i)=>`<sheet name="${n}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`],
['xl/_rels/workbook.xml.rels',`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`],
['xl/styles.xml',styles],...sheets.map(([,s],i)=>[`xl/worksheets/sheet${i+1}.xml`,s])]);
}
root.FinancialXlsx={workbook};if(typeof module!=='undefined')module.exports=root.FinancialXlsx;
})(typeof window==='undefined'?globalThis:window);
