const fs=require('fs'),path=require('path');
const model=JSON.parse(fs.readFileSync('data/forecast-model-v10.json','utf8'));
const news=JSON.parse(fs.readFileSync('data/research-news-v10.json','utf8'));
const sent=JSON.parse(fs.readFileSync('data/sentiment-v10.json','utf8'));
const ev=JSON.parse(fs.readFileSync('data/news-event-study.json','utf8'));
const html=fs.readFileSync('forecast-final.html','utf8'),ui=fs.readFileSync('forecast-final-v10.js','utf8');
const finite=x=>x!==null&&x!==undefined&&x!==''&&Number.isFinite(Number(x));
let passed=0;const ok=(cond,msg)=>{if(!cond)throw Error(msg);passed++};
// TC01 identity and actual HOSE breadth.
ok(model.version==='VMEWS-FORECAST-10.1.0'&&model.promotion?.status==='PASS','TC01 model/promotion');
ok(model.universe?.symbols>=350&&model.universe?.rows>=150000,'TC01 HOSE coverage');
// TC02 strict numerical train/live parity.
const forbidden=['relRet1','relRet5','relRet20','rankRet5','rankRet20','rankTechnical','breadth1','breadth5','breadth20','trend20Share','riskShare','csad1','csad5','dispersion20','marketRet1','marketRet5','marketRet20','marketTechnical','vixLevel','vixRet20','usdVndRet20','dxyRet20','us10yRet20','brentRet20'];
ok(model.governance?.crossSectionalFeaturesInNumericalModel===false,'TC02 parity governance');ok(!forbidden.some(k=>model.featureNames.includes(k)),'TC02 live-only numerical feature');
// TC03 parameter dimensions and independent calibration contracts.
for(const h of ['3','5']){const z=model.horizons[h];ok(z.status==='PASS'&&z.gates.rankingApproved&&z.gates.directionApproved&&z.gates.alphaCalibrationApproved,`TC03 gates ${h}`);for(const k of ['impute','mean','std'])ok(z[k].length===model.featureNames.length&&z[k].every(finite),`TC03 ${h} ${k}`);ok(z.alphaModel.coef.length===model.featureNames.length&&z.directionModel.coef.length===model.featureNames.length,`TC03 coef ${h}`);for(const [name,bs] of [['alpha',z.alphaCalibrationBuckets],['direction',z.directionCalibrationBuckets]]){ok(bs.length>=6,`TC03 ${name} buckets ${h}`);let prev=-Infinity;for(const b of bs){ok(finite(b.lo)&&finite(b.hi)&&b.lo<=b.hi&&b.lo>=prev-1e-12,`TC03 bucket order ${h}`);ok(b.n>=30&&b.positiveRate>=0&&b.positiveRate<=1&&b.q20<=b.q80,`TC03 bucket stats ${h}`);prev=b.hi;}}}
// TC04 sealed chronology, bootstrap and regime stability.
for(const h of ['3','5']){const a=model.horizons[h].sealedAudit;ok(a.n>=10000&&a.alphaIC>.02&&a.alphaSpread>.002,`TC04 sealed ranking ${h}`);ok(a.bootstrap.ic95[0]>0&&a.bootstrap.spread95[0]>0,`TC04 bootstrap ${h}`);ok(a.directionBalancedAccuracy>.515&&a.directionMCC>.02,`TC04 direction ${h}`);ok(model.horizons[h].gates.betterThanMomentumRank,`TC04 baseline ${h}`);for(const seg of ['firstHalf','secondHalf','bear','bull']){const s=a.segments?.[seg];ok(s&&s.n>=500&&s.alphaIC>.005,`TC04 regime ${h} ${seg}`)}}
// TC05 corporate-action chart guard and no connected forecast path.
function adjusted(c){const a=new Array(c.length);a[a.length-1]=c.at(-1);for(let i=c.length-2;i>=0;i--){let z=Math.log(c[i+1]/c[i]);if(Math.abs(z)>.22)z=0;a[i]=a[i+1]/Math.exp(z)}return a}const ca=adjusted([100,100,50,51,52]);ok(Math.max(...ca.slice(1).map((x,i)=>Math.abs(x/ca[i]-1)))<.05,'TC05 corporate action continuity');ok(ui.includes('Math.abs(z)>.22')&&ui.includes('displayClose')&&!ui.includes('lineTo(xf(z.h),y(z.m))'),'TC05 chart contract');
// TC06 real local-history inference on browser feature implementation.
global.window=global;eval(fs.readFileSync('forecast-v4-core.js','utf8'));const sigmoid=x=>1/(1+Math.exp(-Math.max(-35,Math.min(35,x)))),lin=(m,x)=>(+m.intercept||0)+x.reduce((s,v,i)=>s+(+m.coef[i]||0)*v,0),bucket=(bs,x)=>bs.find(b=>x>=b.lo&&x<=b.hi)||(x<bs[0].lo?bs[0]:bs.at(-1));let tested=[];for(const dir of ['data/hose-fallbacks','data/deep-alerts']){if(!fs.existsSync(dir))continue;for(const fn of fs.readdirSync(dir).filter(x=>x.endsWith('.json')&&!x.includes('manifest'))){if(tested.length>=20)break;let d;try{d=JSON.parse(fs.readFileSync(path.join(dir,fn),'utf8'))}catch{continue}const hist=d.history||[];if(hist.length<520)continue;const B=VMEWSForecastV4.features(hist),f=B.fs.at(-1);if(!f)continue;for(const h of ['3','5']){const z=model.horizons[h],v=model.featureNames.map((k,i)=>{let x=finite(f[k])?+f[k]:+z.impute[i];const sd=Math.abs(+z.std[i])<1e-12?1:+z.std[i];return(x-(+z.mean[i]))/sd}),a=lin(z.alphaModel,v),ds=sigmoid(lin(z.directionModel,v));ok(finite(a)&&Math.abs(a)<.25&&ds>0&&ds<1&&bucket(z.alphaCalibrationBuckets,a)&&bucket(z.directionCalibrationBuckets,ds),`TC06 inference ${fn} ${h}`)}tested.push(d.symbol||fn.replace('.json',''))}}ok(tested.length>=5,'TC06 local coverage');
// TC07 accumulated news breadth, dedupe, event taxonomy and non-thin fallback evidence.
ok(news.version==='VMEWS-NEWS-11.0.0'&&news.universe>=350&&news.coverage?.FRT?.used>=20,'TC07 news coverage');const withNews=Object.values(news.coverage||{}).filter(x=>x.used>=1).length,totalNews=Object.values(news.coverage||{}).reduce((s,x)=>s+(+x.used||0),0);ok(withNews>=350&&totalNews>=3000,'TC07 broad news coverage');const sources=new Set(['OFFICIAL','MAINSTREAM','RUMOR_UNVERIFIED','CLARIFICATION']),events=new Set(['REGULATORY','EARNINGS','OWNERSHIP','CORPORATE_ACTION','FINANCING','OPERATIONS_MA','ANALYST','MARKET_FLOW','GENERAL']);for(const [sym,items] of Object.entries(news.symbols||{})){const titles=items.map(x=>String(x.title||'').replace(/\s+/g,' ').trim().toLowerCase());ok(titles.length===new Set(titles).size,`TC07 duplicates ${sym}`);for(const x of items)ok(sources.has(x.sourceClass)&&events.has(x.event)&&x.sourceQuality>=0&&x.sourceQuality<=1&&x.materiality>=0&&x.materiality<=1&&x.firstSeenAt,`TC07 taxonomy ${sym}`)}
// TC08 supervised sentiment exists, covers HOSE, and remains context-only until prospective PIT archive is mature.
ok(sent.version==='VMEWS-SENTIMENT-11.0.0'&&Object.keys(sent.symbols||{}).length>=350&&sent.symbols?.FRT?.n>=20,'TC08 sentiment coverage');ok(!model.featureNames.some(k=>/sentiment|news/i.test(k)),'TC08 sentiment leakage');for(const z of Object.values(sent.symbols||{})){ok(z.n<=60&&z.n>=1,'TC08 item cap');ok(['TÍCH CỰC','TRUNG TÍNH','TIÊU CỰC'].includes(z.state),'TC08 state')}
// TC09 event study, unsupervised clusters, hierarchical pooling, T+2 confirmation and rumor pre-move diagnostics.
ok(ev.version==='VMEWS-NEWS-EVENT-STUDY-1.3.0'&&ev.pointInTimeEligibleForNumericalForecast===false,'TC09 event governance');ok(ev.events>=2500&&ev.symbolsWithPrice>=340&&Object.keys(ev.clusters||{}).length>=8,'TC09 event coverage');ok(ev.rumorStudy?.n>=10&&finite(ev.rumorStudy?.preEvent?.['2']?.meanAR)&&finite(ev.rumorStudy?.horizons?.['5']?.meanAR)&&finite(ev.rumorStudy?.preMoveShare2),'TC09 rumor diagnostics');const selected=Object.values(ev.symbols||{}).filter(z=>z?.selectedEvidence?.stats?.horizons?.['5']).length;ok(selected>=340,'TC09 pooled evidence coverage');const frt=ev.symbols?.FRT;ok(frt?.latestEvent&&frt.latestEvent.cluster!==undefined&&frt.latestEvent.historicalSameCluster&&frt.selectedEvidence?.scope,'TC09 FRT evidence');
// TC10 clean user-facing contract; failed flow and fake absolute probability removed.
for(const s of ['Đọc hướng đi ngắn hạn cùng trạng thái rủi ro','Hệ thống tách riêng khả năng xếp hạng tương đối','Mô hình chỉ vẽ các horizon','Khối ngoại / tự doanh'])ok(!html.includes(s),`TC10 filler ${s}`);ok(!ui.includes('/flow?')&&!ui.includes('P(tăng)'),'TC10 deprecated UI');ok(ui.includes("x!==null&&x!==undefined&&x!==''")&&ui.includes('directionCalibrationBuckets')&&ui.includes('alphaCalibrationBuckets'),'TC10 strict UI');
console.log(JSON.stringify({ok:true,testCases:10,assertions:passed,model:model.version,symbols:model.universe.symbols,rows:model.universe.rows,localSymbolsTested:tested,newsSymbolsWithNews:withNews,totalNews,FRTNews:news.coverage.FRT,eventStudyEvents:ev.events,hierarchicalEvidenceSymbols:selected,rumors:ev.rumorStudy.n,absoluteScenario:model.promotion.absoluteScenario,T3:model.horizons['3'].sealedAudit,T5:model.horizons['5'].sealedAudit}));
