import json,math,pathlib
from datetime import datetime,timezone
ROOT=pathlib.Path('.');DATA=ROOT/'data';failures=[];passes=[]
def check(name,condition,detail=''):(passes if condition else failures).append(name if condition else {'name':name,'detail':str(detail)[:1200]})
def load(name):
    p=DATA/name;check(f'{name} exists',p.exists(),p);return json.loads(p.read_text(encoding='utf-8')) if p.exists() else {}
def finite_json(x):
    if isinstance(x,float):return math.isfinite(x)
    if isinstance(x,dict):return all(finite_json(v) for v in x.values())
    if isinstance(x,list):return all(finite_json(v) for v in x)
    return True
model=load('forecast-model-v12.json');current=load('forecast-current-v12.json');dash=load('forecast-dashboard-v12.json');back=load('forecast-backtest-v12.json');audit=load('data-audit-v12.json')
for name,z in [('forecast-model-v12.json',model),('forecast-current-v12.json',current),('forecast-dashboard-v12.json',dash),('forecast-backtest-v12.json',back),('data-audit-v12.json',audit)]:check(f'{name} finite JSON',finite_json(z))
# Phase 1: current data coverage and source hierarchy
current_passed=int(audit.get('currentSymbolsPassed') or 0);current_failed=int(audit.get('currentSymbolsFailed') or 0);current_cov=float(audit.get('currentRouteCoverageRatio') or 0);routes=audit.get('routes') or {};check('DATA current coverage >= 330',current_passed>=330,{'passed':current_passed,'failed':current_failed,'routes':routes});check('DATA current route coverage >= 95%',current_cov>=.95,current_cov);attempted=sum(any(x.get('stage')=='VNSTOCK_PRIMARY' for x in z.get('attempts',[])) for s,z in (audit.get('symbols') or {}).items() if s in (current.get('symbols') or {}));check('DATA VNStock primary attempted across current universe',attempted>=current_passed*.95,attempted);check('DATA index route available',bool((audit.get('index') or {}).get('rows')),audit.get('index'))
# Survivorship hardening: only confirmed VCI STO lineage; no guessed delisted exchange.
u=audit.get('universeAudit') or {};disc=(u.get('discovery') or {}).get('vnstockReference') or {};mapping=disc.get('productGroupMappingEvidence') or {};hsx=mapping.get('HSX') or {};check('UNIVERSE Vnstock HSX product-group mapping complete',int(hsx.get('rows') or 0)>=350 and int(hsx.get('matchingProductGroup') or 0)==int(hsx.get('rows') or -1),hsx);check('UNIVERSE former-HSX candidates discovered',int(disc.get('confirmedFormerHOSE') or 0)>=2,disc.get('confirmedFormerHOSESymbols'));check('UNIVERSE validated historical-only cohort >= 1',int(u.get('historicalOnlyCount') or 0)>=1,u.get('historicalOnly'));historical=set((u.get('historicalOnly') or {}).keys());check('UNIVERSE historical-only excluded from current forecast',not historical.intersection(current.get('symbols') or {}),historical.intersection(current.get('symbols') or {}));check('UNIVERSE unknown former exchange not guessed','NULL/UPX/STX' in str(disc.get('rule') or ''),disc.get('rule'))
# Entity/event/rumor corpus
entity=audit.get('entityFilter') or {};check('ENTITY gate version present',str(entity.get('version','')).startswith('VMEWS-ENTITY-GATE-12'),entity.get('version'));check('ENTITY gate evaluated >= 10000 candidates',int(entity.get('input') or 0)>=10000,entity.get('input'));check('ENTITY contaminated candidates rejected',int(entity.get('rejected') or 0)>0,entity.get('rejected'));check('ENTITY retained coverage >= 55%',float(entity.get('acceptanceRate') or 0)>=.55,entity.get('acceptanceRate'));check('ENTITY HCM audited','HCM' in (entity.get('perSymbol') or {}));check('ENTITY CDC audited','CDC' in (entity.get('perSymbol') or {}));check('ENTITY ambiguous dictionary includes language collisions',all(x in set(entity.get('ambiguousSymbols') or []) for x in ['HCM','CDC','GTA','THG','VIP','FIT','NHA']),entity.get('ambiguousSymbols'))
streams=entity.get('streamCoverage') or {};check('EVENT official stream >= 500',int(streams.get('OFFICIAL') or 0)>=500,streams);check('EVENT narrative stream >= 5000',int(streams.get('MAIN') or 0)>=5000,streams);check('RUMOR stream >= 20',int(streams.get('RUMOR') or 0)>=20,streams)
ev=audit.get('eventCoverage') or {};check('EVENT symbols >= 300',int(ev.get('symbols') or 0)>=300,ev);check('EVENT articles >= 10000 after entity gate',int(ev.get('articles') or 0)>=10000,ev);check('EVENT official classified >= 500',int(ev.get('official') or 0)>=500,ev);check('EVENT matured outcomes >= 10000',int(ev.get('eventOutcomes') or 0)>=10000,ev);check('RUMOR corpus >= 20 after entity gate',int(ev.get('rumors') or 0)>=20,ev);check('EVENT archive mode explicitly disclosed',ev.get('archiveMode')=='RETROSPECTIVE_PUBLICATION_TIME_ALIGNED',ev.get('archiveMode'))
# Leakage / PIT governance
features=model.get('featureNames') or []
for bad in ['futureReturn','actualReturn','confirmT2','newsFollowsPrice','matureDate5','actualRawPrice']:check(f'PIT forbidden model feature absent: {bad}',bad not in features)
gov=model.get('governance') or {};check('PIT publication-time governance declared','publishedAt' in str(gov.get('eventPIT')),gov.get('eventPIT'));check('OOF stacking governance declared','OOF' in str(gov.get('stacking')),gov.get('stacking'));check('sealed audit governance declared','sealed' in str(gov.get('sealedAudit')).lower(),gov.get('sealedAudit'));check('survivorship governance declared','former-HSX' in str(gov.get('survivorship')),gov.get('survivorship'))
# Flow availability is explicit; missing != neutral evidence.
fc=audit.get('flowCoverage') or {};check('FLOW foreign coverage >= 15%',float(fc.get('foreignCoverage') or 0)>=.15,fc);check('FLOW missingness explicit','foreignAvailable' in features and 'propAvailable' in features)
# ML / calibration / stability: every direct price horizon must pass.
horizons=model.get('horizons') or {};check('ML direct horizons 1-5 exist',all(str(h) in horizons for h in range(1,6)),list(horizons))
for h in range(1,6):
    z=horizons.get(str(h),{});active=z.get('activeExperts') or [];sealed=z.get('sealedAudit') or {};check(f'MODEL T+{h} NUMERICAL active','NUMERICAL' in active,active);check(f'MODEL T+{h} REGIME active','REGIME' in active,active);check(f'MODEL T+{h} price gate PASS',z.get('priceStatus')=='PASS',z.get('priceGates'));check(f'MODEL T+{h} audit n >= 5000',int(sealed.get('n') or 0)>=5000,sealed.get('n'));check(f'MODEL T+{h} rank IC > 0.02',float(sealed.get('rankIC') or 0)>.02,sealed.get('rankIC'));check(f'MODEL T+{h} spread > 0.10%',float(sealed.get('spread') or 0)>.001,sealed.get('spread'));check(f'MODEL T+{h} IC days >= 20',int(sealed.get('icDays') or 0)>=20,sealed.get('icDays'));check(f'MODEL T+{h} daily IC majority nonnegative',float(sealed.get('icPositiveDayShare') or 0)>=.50,sealed.get('icPositiveDayShare'));check(f'MODEL T+{h} IC bootstrap populated',isinstance(sealed.get('icBootstrap95'),list) and len(sealed.get('icBootstrap95'))==2,sealed.get('icBootstrap95'));check(f'MODEL T+{h} calibration coverage 52-72%',.52<=float(sealed.get('coverage20_80') or 0)<=.72,sealed.get('coverage20_80'));check(f'MODEL T+{h} scenario rank IC positive',float(sealed.get('scenarioRankIC') or 0)>.01,sealed.get('scenarioRankIC'))
    regimes=z.get('regimeAudit') or {};check(f'MODEL T+{h} regime audit breadth strong','BREADTH_STRONG' in regimes,regimes.keys());check(f'MODEL T+{h} regime audit breadth weak','BREADTH_WEAK' in regimes,regimes.keys());check(f'MODEL T+{h} regime audit by year',bool(regimes.get('BY_YEAR')),regimes.get('BY_YEAR'))
    promotions=z.get('expertPromotion') or {}
    for name in ['EVENT','FLOW','FUNDAMENTAL_EVENT','RUMOR']:
        p=promotions.get(name);check(f'MODEL T+{h} expert selection evaluates {name}',isinstance(p,dict),promotions.keys())
        if isinstance(p,dict) and p.get('promoted'):check(f'MODEL T+{h} promoted {name} passed evidence gate',p.get('evidenceGatePassed') is True,p)
    for name in active:check(f'MODEL T+{h} ablation available {name}',name in (z.get('ablation') or {}),z.get('ablation'))
promotion=model.get('promotion') or {};direct=promotion.get('directPriceHorizons') or [];check('MODEL promotion PASS',promotion.get('status')=='PASS',promotion);check('MODEL all T+1..T+5 price horizons promoted',direct==[1,2,3,4,5],direct)
# Current numerical outputs and validation identity.
symbols=current.get('symbols') or {};check('CURRENT symbols >= 320',len(symbols)>=320,len(symbols))
for s,z in list(symbols.items())[:100]:
    close=float(z.get('close') or 0);check(f'CURRENT {s} close > 0',close>0,close)
    for h in range(1,6):
        q=(z.get('horizons') or {}).get(str(h),{});check(f'CURRENT {s} T+{h} price validated',q.get('priceValidated') is True,q.get('validationStatus'))
        if not q:continue
        er=float(q.get('expectedReturn'));ep=float(q.get('expectedPrice'));lo=float(q.get('q20'));hi=float(q.get('q80'));pup=float(q.get('probUp'));check(f'CURRENT {s} T+{h} expected price identity',abs(ep-close*math.exp(er))<=max(1.,ep*1e-9));check(f'CURRENT {s} T+{h} quantile order',lo<=er<=hi,(lo,er,hi));check(f'CURRENT {s} T+{h} probability numeric',0<=pup<=1,pup)
# Historical cut-point trace: what was known at T0, forecast, raw future, adjusted realized return.
cases=back.get('cases') or {}
for h in range(1,6):
    a=cases.get(str(h)) or [];check(f'BACKTEST T+{h} cases >= 50',len(a)>=50,len(a))
    for x in a[:80]:
        origin=float(x.get('originPrice') or 0);pred=float(x.get('predictedReturn') or 0);ep=float(x.get('expectedPrice') or 0);check(f'BACKTEST T+{h} origin valid',bool(x.get('originDate')) and origin>0,x);check(f'BACKTEST T+{h} expected price identity',abs(ep-origin*math.exp(pred))<=max(1.,ep*1e-9));check(f'BACKTEST T+{h} raw future retained',finite_json(x.get('actualRawPrice')) and finite_json(x.get('realizedComparablePrice')),(x.get('actualRawPrice'),x.get('realizedComparablePrice')));c=x.get('contextAtOrigin') or {};check(f'BACKTEST T+{h} T0 context retained',all(k in c for k in ['prior20','breadth20','newsN20','rumorN20','foreignAvailable','propAvailable']),c.keys())
# Dashboard/current only, no historical-delisted leakage.
check('DASH charts cover current universe',len(dash.get('charts') or {})>=len(symbols)*.95,(len(dash.get('charts') or {}),len(symbols)));check('DASH excludes historical-only symbols',not historical.intersection(dash.get('symbols') or {}),historical.intersection(dash.get('symbols') or {}))
for s,a in list((dash.get('charts') or {}).items())[:60]:check(f'DASH {s} chart >= 80 rows',len(a)>=80,len(a));check(f'DASH {s} chart chronological',not a or all(a[i]['date']<a[i+1]['date'] for i in range(len(a)-1)))
phase={'version':'VMEWS-PHASE-GATES-12.2.0','generatedAt':datetime.now(timezone.utc).isoformat(),'tests':len(passes)+len(failures),'passed':len(passes),'failed':len(failures),'failures':failures,'phases':{k:not any(str(x['name']).startswith(prefix) for x in failures) for k,prefix in [('data','DATA'),('universe','UNIVERSE'),('entity','ENTITY'),('event','EVENT'),('rumor','RUMOR'),('flow','FLOW'),('ml','MODEL'),('current','CURRENT'),('backtest','BACKTEST'),('dashboard','DASH')]}};phase['status']='PASS' if not failures else 'FAIL';(DATA/'phase-gates-v12.json').write_text(json.dumps(phase,ensure_ascii=False,indent=2,allow_nan=False),encoding='utf-8');print(json.dumps(phase,ensure_ascii=False,indent=2));raise SystemExit(1 if failures else 0)
