import { chromium } from 'playwright';

const base=process.env.V12_BROWSER_URL || 'http://127.0.0.1:8000/forecast-final.html?symbol=FPT';
const allowedOrigin=new URL(base).origin;
const browser=await chromium.launch({headless:true});
const errors=[];const failed=[];const external=[];const cdnInjectedTelemetry=[];const approvedLiveMainData=[];
const isKnownCdnInjectedTelemetry=(u)=>{try{const x=new URL(u);return x.hostname==='static.cloudflareinsights.com'&&x.pathname.startsWith('/beacon.min.js')}catch{return false}};
const isApprovedLiveMainData=(u)=>{try{const x=new URL(u);return x.protocol==='https:'&&x.hostname==='raw.githubusercontent.com'&&x.pathname.startsWith('/NCKHtop1/vmews-risk-analytics/main/data/')}catch{return false}};
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text())});page.on('pageerror',err=>errors.push(String(err)));page.on('requestfailed',req=>failed.push(`${req.method()} ${req.url()} ${req.failure()?.errorText||''}`));page.on('request',req=>{const u=req.url();if(/^https?:/.test(u)&&new URL(u).origin!==allowedOrigin){if(isKnownCdnInjectedTelemetry(u))cdnInjectedTelemetry.push(u);else if(req.method()==='GET'&&isApprovedLiveMainData(u))approvedLiveMainData.push(u);else external.push(u)}});
await page.goto(base,{waitUntil:'networkidle',timeout:60000});
await page.waitForFunction(()=>document.querySelectorAll('#forecastCards .forecastCard').length===5&&/RETURN T\+[1-5]/.test(document.querySelector('#modelBadge')?.textContent||''),null,{timeout:30000});
await page.waitForFunction(()=>document.querySelector('#researchWorkbench')&&document.querySelector('#taCanvas'),null,{timeout:15000});
const stale=await page.evaluate(async()=>{const B=await window.__VMEWS_LOAD_BASE__();return window.__VMEWS_FRESHNESS__?.inspect(B.dash.symbols.FPT).stale===true});
if(!stale){
await page.waitForFunction(()=>{const cards=document.querySelectorAll('#signalDeck .signalCard').length,position=document.querySelector('#carouselPosition')?.textContent||'';return cards>=1&&cards<=10&&!/^00\s*\/\s*00$/.test(position.trim())},null,{timeout:30000});
const leaderCards=page.locator('#signalDeck .signalCard');const leaderCount=await leaderCards.count();if(leaderCount<1||leaderCount>10)throw new Error(`leaderboard must contain 1-10 cards, got ${leaderCount}`);const carouselPosition=(await page.locator('#carouselPosition').innerText()).trim();if(!/^\d{2} \/ \d{2}$/.test(carouselPosition)||carouselPosition==='00 / 00')throw new Error(`leader carousel position invalid: ${carouselPosition}`);const pulseForecast=(await page.locator('#marketPulse .pulseCard').nth(1).innerText()).trim();const pulseMatch=pulseForecast.match(/(\d+)\s*\/\s*(\d+)/);if(!pulseMatch||Number(pulseMatch[2])<1)throw new Error(`HOSE forecast coverage is empty: ${pulseForecast}`);
}else{
  if(await page.locator('#signalDeck .signalCard').count())throw new Error('stale forecasts must not drive the leaderboard');
  if(!(await page.locator('#decision').innerText()).includes('ĐANG CẬP NHẬT'))throw new Error('stale session must be visible');
}
const badge=(await page.locator('#modelBadge').innerText()).trim();if(!/^HOSE · \d{4}-\d{2}-\d{2} · RETURN T\+[1-5](?: · .+)?$/.test(badge))throw new Error(`model badge state invalid: ${badge}`);
const decision=(await page.locator('#decision').innerText()).trim();if(!decision||decision==='—'||decision.includes('LOCKED'))throw new Error(`decision invalid: ${decision}`);
for(const id of ['#close','#risk']){const t=(await page.locator(id).innerText()).trim();if(!t||t==='—')throw new Error(`${id} empty`)}
const returnSummary=/^[+-]?\d+(?:\.\d+)?%$/;for(const id of ['#t1','#t3','#t5']){const t=(await page.locator(id).innerText()).trim();if(t!=='—'&&!returnSummary.test(t))throw new Error(`${id} is neither a released return forecast nor an explicit abstention: ${t}`)}
const cards=page.locator('#forecastCards .forecastCard');if(await cards.count()!==5)throw new Error(`expected 5 forecast cards, got ${await cards.count()}`);
let returnForecasts=0,abstainedForecasts=0;for(let i=0;i<5;i++){const t=(await cards.nth(i).innerText()).trim();const lines=t.split(/\n+/).map(x=>x.trim()).filter(Boolean);const hasHorizon=lines.some(x=>x===`T+${i+1}`||x.startsWith(`T+${i+1} ·`));const hasReturn=lines.some(x=>/^[+-]?\d+(?:\.\d+)?%$/.test(x))&&t.includes('RETURN KỲ VỌNG');const hasRange=t.includes('Return Q20–Q80');const withheld=stale?(t.includes('ĐANG CẬP NHẬT')&&t.includes('Chờ dữ liệu phiên')):(t.includes('CHƯA ĐẠT KIỂM ĐỊNH')&&t.includes('Kỳ này không phát hành return'));if(stale&&hasReturn)throw new Error('stale return forecast is exposed');if(hasReturn){returnForecasts++;if(!hasRange)throw new Error(`released return card ${i+1} lacks return range: ${t}`)}else if(withheld){abstainedForecasts++}else{throw new Error(`forecast card ${i+1} is neither released nor explicitly withheld: ${t}`)}if(!hasHorizon||t.includes('LOCKED'))throw new Error(`forecast card ${i+1} has invalid state: ${t}`)}if(!stale&&returnForecasts<1)throw new Error('expected at least one independently validated return forecast');if(returnForecasts+abstainedForecasts!==5)throw new Error(`forecast card accounting mismatch: released=${returnForecasts} abstained=${abstainedForecasts}`);
if(!(await page.locator('#validation').getAttribute('hidden')!==null)||!(await page.locator('#backtest').getAttribute('hidden')!==null)||!(await page.locator('#eventImpactPanel').getAttribute('hidden')!==null))throw new Error('validation/backtest/event-impact must remain hidden from the public dashboard');
const visible=await page.locator('body').innerText();for(const banned of ['VNStock ưu tiên cho OHLCV Việt Nam','không nội suy','whisker =','Completed EOD snapshot','không phát lệnh mua/bán','Missing rumor không được coi là neutral signal','Tâm điểm VN30','ĐIỂM ĐÃ QUA GATE','ĐIỂM ĐỘ TIN CẬY THẤP','ĐỘ TIN CẬY ĐIỂM THẤP','không phải chênh vài trăm đồng','MÁY CHỦ AI DỰ PHÒNG','máy-chủ-của-bạn','Kết nối máy chủ'])if(visible.includes(banned))throw new Error(`banned visible copy: ${banned}`);
const canvas=page.locator('#chart');const box=await canvas.boundingBox();if(!box)throw new Error('chart canvas has no box');if(await page.locator('#tooltip').count()!==1)throw new Error('chart tooltip surface missing');
const ta=page.locator('#taCanvas');const taBox=await ta.boundingBox();if(!taBox||taBox.width<500||taBox.height<250)throw new Error(`TA canvas invalid: ${JSON.stringify(taBox)}`);
const taText=(await page.locator('#researchWorkbench').innerText()).trim();for(const token of ['PHÂN TÍCH BỔ SUNG','Kỹ thuật · Dòng tiền · Tài chính','Tín hiệu nổi bật','RSI 14','MACD','Khối ngoại','Lợi nhuận sau thuế'])if(!taText.includes(token))throw new Error(`TA/context workbench missing ${token}: ${taText}`);
const checks=page.locator('#taControls input[type=checkbox]');if(await checks.count()<6)throw new Error('TA indicator controls missing');await checks.nth(2).check();await page.waitForTimeout(80);if(!(await checks.nth(2).isChecked()))throw new Error('TA indicator toggle not interactive');
const ctxText=(await page.locator('#marketContext').innerText()).trim();if(!ctxText||ctxText.includes('đang được cập nhật'))throw new Error(`current context not materialized: ${ctxText}`);for(const token of ['Khối ngoại','Tự doanh','Doanh thu','Lợi nhuận sau thuế'])if(!ctxText.includes(token))throw new Error(`current context missing ${token}: ${ctxText}`);
const newsCount=await page.locator('#news .newsItem').count();const newsText=(await page.locator('#news').innerText()).trim();if(newsCount<1&&!/Chưa ghi nhận|Không có event|Không có sự kiện/i.test(newsText))throw new Error(`event intelligence neither rendered items nor a valid empty state: ${newsText}`);
const sourceText=await page.locator('#sourceAudit').innerText();for(const token of ['Giá thị trường','Tin đã đối chiếu','Dòng tiền khối ngoại','Dòng tiền tự doanh','Danh mục quỹ','Tài chính doanh nghiệp','Tín hiệu cộng đồng'])if(!sourceText.includes(token))throw new Error(`source audit missing ${token}: ${sourceText}`);
const hiddenInternal=await page.evaluate(()=>({validation:document.querySelector('#validation')?.hidden===true,backtest:document.querySelector('#backtest')?.hidden===true,eventImpact:document.querySelector('#eventImpactPanel')?.hidden===true}));if(!hiddenInternal.validation||!hiddenInternal.backtest||!hiddenInternal.eventImpact)throw new Error(`internal validation surfaces unexpectedly visible: ${JSON.stringify(hiddenInternal)}`);
const vcb=page.locator('#quick button',{hasText:'VCB'});if(await vcb.count()){await vcb.first().click();await page.waitForFunction(()=>document.querySelector('#chartTitle')?.textContent?.startsWith('VCB'));if(new URL(page.url()).searchParams.get('symbol')!=='VCB')throw new Error('symbol navigation did not update URL');await page.waitForFunction(()=>document.querySelector('#marketContext')?.textContent?.includes('VCB'),null,{timeout:5000})}
await page.screenshot({path:'v12-browser-desktop.png',fullPage:true});
if(errors.length)throw new Error(`browser console errors: ${errors.join(' | ')}`);if(failed.length)throw new Error(`failed requests: ${failed.join(' | ')}`);if(external.length)throw new Error(`unexpected external runtime requests: ${external.join(' | ')}`);
const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});const mobileErrors=[];mobile.on('console',m=>{if(m.type()==='error')mobileErrors.push(m.text())});mobile.on('pageerror',e=>mobileErrors.push(String(e)));await mobile.goto(base,{waitUntil:'networkidle',timeout:60000});await mobile.waitForFunction(()=>document.querySelectorAll('#forecastCards .forecastCard').length===5&&document.querySelector('#researchWorkbench'),null,{timeout:30000});
if(!stale)await mobile.waitForFunction(()=>document.querySelectorAll('#signalDeck .signalCard').length>=1,null,{timeout:30000});const dims=await mobile.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,chart:document.querySelector('#chart')?.getBoundingClientRect().width,wrap:document.querySelector('.chartWrap')?.getBoundingClientRect().width,proof:document.querySelector('#methodProof')?.getBoundingClientRect().width,ta:document.querySelector('#researchWorkbench')?.getBoundingClientRect().width,taCanvas:document.querySelector('#taCanvas')?.getBoundingClientRect().width,leaders:document.querySelectorAll('#signalDeck .signalCard').length}));if(dims.sw>dims.cw+3)throw new Error(`mobile document horizontal overflow ${JSON.stringify(dims)}`);for(const k of ['chart','ta','taCanvas'])if(!dims[k]||dims[k]>dims.cw+3)throw new Error(`mobile ${k} overflow ${JSON.stringify(dims)}`);if(await mobile.locator('#forecastCards .forecastCard').count()!==5)throw new Error('mobile forecast cards missing');if(stale?dims.leaders!==0:(dims.leaders<1||dims.leaders>10))throw new Error(`mobile leaderboard invalid: ${JSON.stringify(dims)}`);await mobile.screenshot({path:'v12-browser-mobile.png',fullPage:true});if(mobileErrors.length)throw new Error(`mobile console errors: ${mobileErrors.join(' | ')}`);
console.log(JSON.stringify({browserSmoke:'PASS',url:base,allowedOrigin,badge,decision,newsCount,internalValidation:'HIDDEN',taContext:'PASS',desktop:{width:1440,height:1000},mobile:dims,approvedLiveMainDataRequests:approvedLiveMainData.length,externalRuntimeRequests:external.length,cdnInjectedTelemetryRequests:cdnInjectedTelemetry.length,consoleErrors:errors.length},null,2));
await browser.close();
